package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcQryInstrumentField extends StructObject {
	public CThostFtdcQryInstrumentField() {
		super();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(0) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({31})
	@Field(0)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 0).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(1) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({9})
	@Field(1)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 1).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(2) 
	private Pointer<Byte> ExchangeInstID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({31})
	@Field(2)
	public void setExchangeInstID(String exchangeInstID) {
		this.io.getPointerField(this, 2).setCString(exchangeInstID);
	}

	public String getExchangeInstID() {
		return ExchangeInstID().getCString();
	}

	/**
	 * \u4ea7\u54c1\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(3) 
	private Pointer<Byte> ProductID() {
		return this.io.getPointerField(this, 3);
	}

	@Array({31})
	@Field(3)
	public void setProductID(String productID) {
		this.io.getPointerField(this, 3).setCString(productID);
	}

	public String getProductID() {
		return ProductID().getCString();
	}

	public CThostFtdcQryInstrumentField(Pointer pointer) {
		super(pointer);
	}

}

