package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcCFMMCBrokerKeyField extends StructObject {
	public CThostFtdcCFMMCBrokerKeyField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u7edf\u4e00\u7f16\u7801
	 */
	@Array({11}) 
	@Field(1) 
	private Pointer<Byte> ParticipantID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({11})
	@Field(1)
	public void setParticipantID(String participantID) {
		this.io.getPointerField(this, 1).setCString(participantID);
	}

	public String getParticipantID() {
		return ParticipantID().getCString();
	}

	/**
	 * \u5bc6\u94a5\u751f\u6210\u65e5\u671f
	 */
	@Array({9}) 
	@Field(2) 
	private Pointer<Byte> CreateDate() {
		return this.io.getPointerField(this, 2);
	}

	@Array({9})
	@Field(2)
	public void setCreateDate(String createDate) {
		this.io.getPointerField(this, 2).setCString(createDate);
	}

	public String getCreateDate() {
		return CreateDate().getCString();
	}

	/**
	 * \u5bc6\u94a5\u751f\u6210\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(3) 
	private Pointer<Byte> CreateTime() {
		return this.io.getPointerField(this, 3);
	}

	@Array({9})
	@Field(3)
	public void setCreateTime(String createTime) {
		this.io.getPointerField(this, 3).setCString(createTime);
	}

	public String getCreateTime() {
		return CreateTime().getCString();
	}

	/**
	 * \u5bc6\u94a5\u7f16\u53f7
	 */
	@Field(4) 
	private int KeyID() {
		return this.io.getIntField(this, 4);
	}

	public int getKeyID() {
		return KeyID();
	}

	/**
	 * \u5bc6\u94a5\u7f16\u53f7
	 */
	@Field(4) 
	private CThostFtdcCFMMCBrokerKeyField KeyID(int KeyID) {
		this.io.setIntField(this, 4, KeyID);
		return this;
	}

	public void setKeyID(int keyID) {
		KeyID(keyID);
	}

	/**
	 * \u52a8\u6001\u5bc6\u94a5
	 */
	@Array({21}) 
	@Field(5) 
	private Pointer<Byte> CurrentKey() {
		return this.io.getPointerField(this, 5);
	}

	@Array({21})
	@Field(5)
	public void setCurrentKey(String currentKey) {
		this.io.getPointerField(this, 5).setCString(currentKey);
	}

	public String getCurrentKey() {
		return CurrentKey().getCString();
	}

	/**
	 * \u52a8\u6001\u5bc6\u94a5\u7c7b\u578b
	 */
	@Field(6) 
	private byte KeyKind() {
		return this.io.getByteField(this, 6);
	}

	public char getKeyKind() {
		return (char)KeyKind();
	}

	/**
	 * \u52a8\u6001\u5bc6\u94a5\u7c7b\u578b
	 */
	@Field(6) 
	private CThostFtdcCFMMCBrokerKeyField KeyKind(byte KeyKind) {
		this.io.setByteField(this, 6, KeyKind);
		return this;
	}

	public void setKeyKind(char keyKind) {
		KeyKind((byte)keyKind);
	}

	public CThostFtdcCFMMCBrokerKeyField(Pointer pointer) {
		super(pointer);
	}

}

