package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcExchangeMarginRateAdjustField extends StructObject {
	public CThostFtdcExchangeMarginRateAdjustField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(1) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({31})
	@Field(1)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 1).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Field(2) 
	private byte HedgeFlag() {
		return this.io.getByteField(this, 2);
	}

	public char getHedgeFlag() {
		return (char)HedgeFlag();
	}

	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Field(2) 
	private CThostFtdcExchangeMarginRateAdjustField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 2, HedgeFlag);
		return this;
	}

	public void setHedgeFlag(char hedgeFlag) {
		HedgeFlag((byte)hedgeFlag);
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(3) 
	private double LongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 3);
	}

	public double getLongMarginRatioByMoney() {
		return LongMarginRatioByMoney();
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(3) 
	private CThostFtdcExchangeMarginRateAdjustField LongMarginRatioByMoney(double LongMarginRatioByMoney) {
		this.io.setDoubleField(this, 3, LongMarginRatioByMoney);
		return this;
	}

	public void setLongMarginRatioByMoney(double longMarginRatioByMoney) {
		LongMarginRatioByMoney(longMarginRatioByMoney);
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(4) 
	private double LongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 4);
	}

	public double getLongMarginRatioByVolume() {
		return LongMarginRatioByVolume();
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(4) 
	private CThostFtdcExchangeMarginRateAdjustField LongMarginRatioByVolume(double LongMarginRatioByVolume) {
		this.io.setDoubleField(this, 4, LongMarginRatioByVolume);
		return this;
	}

	public void setLongMarginRatioByVolume(double longMarginRatioByVolume) {
		LongMarginRatioByVolume(longMarginRatioByVolume);
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(5) 
	private double ShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 5);
	}

	public double getShortMarginRatioByMoney() {
		return ShortMarginRatioByMoney();
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(5) 
	private CThostFtdcExchangeMarginRateAdjustField ShortMarginRatioByMoney(double ShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 5, ShortMarginRatioByMoney);
		return this;
	}

	public void setShortMarginRatioByMoney(double shortMarginRatioByMoney) {
		ShortMarginRatioByMoney(shortMarginRatioByMoney);
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(6) 
	private double ShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 6);
	}

	public double getShortMarginRatioByVolume() {
		return ShortMarginRatioByVolume();
	}

	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(6) 
	private CThostFtdcExchangeMarginRateAdjustField ShortMarginRatioByVolume(double ShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 6, ShortMarginRatioByVolume);
		return this;
	}

	public void setShortMarginRatioByVolume(double shortMarginRatioByVolume) {
		ShortMarginRatioByVolume(shortMarginRatioByVolume);
	}

	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(7) 
	private double ExchLongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 7);
	}

	public double getExchLongMarginRatioByMoney() {
		return ExchLongMarginRatioByMoney();
	}

	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(7) 
	private CThostFtdcExchangeMarginRateAdjustField ExchLongMarginRatioByMoney(double ExchLongMarginRatioByMoney) {
		this.io.setDoubleField(this, 7, ExchLongMarginRatioByMoney);
		return this;
	}

	public void setExchLongMarginRatioByMoney(double exchLongMarginRatioByMoney) {
		ExchLongMarginRatioByMoney(exchLongMarginRatioByMoney);
	}

	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(8) 
	private double ExchLongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 8);
	}

	public double getExchLongMarginRatioByVolume() {
		return ExchLongMarginRatioByVolume();
	}

	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(8) 
	private CThostFtdcExchangeMarginRateAdjustField ExchLongMarginRatioByVolume(double ExchLongMarginRatioByVolume) {
		this.io.setDoubleField(this, 8, ExchLongMarginRatioByVolume);
		return this;
	}

	public void setExchLongMarginRatioByVolume(double exchLongMarginRatioByVolume) {
		ExchLongMarginRatioByVolume(exchLongMarginRatioByVolume);
	}

	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(9) 
	private double ExchShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 9);
	}

	public double getExchShortMarginRatioByMoney() {
		return ExchShortMarginRatioByMoney();
	}

	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(9) 
	private CThostFtdcExchangeMarginRateAdjustField ExchShortMarginRatioByMoney(double ExchShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 9, ExchShortMarginRatioByMoney);
		return this;
	}

	public void setExchShortMarginRatioByMoney(double exchShortMarginRatioByMoney) {
		ExchShortMarginRatioByMoney(exchShortMarginRatioByMoney);
	}

	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(10) 
	private double ExchShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 10);
	}

	public double getExchShortMarginRatioByVolume() {
		return ExchShortMarginRatioByVolume();
	}

	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(10) 
	private CThostFtdcExchangeMarginRateAdjustField ExchShortMarginRatioByVolume(double ExchShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 10, ExchShortMarginRatioByVolume);
		return this;
	}

	public void setExchShortMarginRatioByVolume(double exchShortMarginRatioByVolume) {
		ExchShortMarginRatioByVolume(exchShortMarginRatioByVolume);
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(11) 
	private double NoLongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 11);
	}

	public double getNoLongMarginRatioByMoney() {
		return NoLongMarginRatioByMoney();
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(11) 
	private CThostFtdcExchangeMarginRateAdjustField NoLongMarginRatioByMoney(double NoLongMarginRatioByMoney) {
		this.io.setDoubleField(this, 11, NoLongMarginRatioByMoney);
		return this;
	}

	public void setNoLongMarginRatioByMoney(double noLongMarginRatioByMoney) {
		NoLongMarginRatioByMoney(noLongMarginRatioByMoney);
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(12) 
	private double NoLongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 12);
	}

	public double getNoLongMarginRatioByVolume() {
		return NoLongMarginRatioByVolume();
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(12) 
	private CThostFtdcExchangeMarginRateAdjustField NoLongMarginRatioByVolume(double NoLongMarginRatioByVolume) {
		this.io.setDoubleField(this, 12, NoLongMarginRatioByVolume);
		return this;
	}

	public void setNoLongMarginRatioByVolume(double noLongMarginRatioByVolume) {
		NoLongMarginRatioByVolume(noLongMarginRatioByVolume);
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(13) 
	private double NoShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 13);
	}

	public double getNoShortMarginRatioByMoney() {
		return NoShortMarginRatioByMoney();
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(13) 
	private CThostFtdcExchangeMarginRateAdjustField NoShortMarginRatioByMoney(double NoShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 13, NoShortMarginRatioByMoney);
		return this;
	}

	public void setNoShortMarginRatioByMoney(double noShortMarginRatioByMoney) {
		NoShortMarginRatioByMoney(noShortMarginRatioByMoney);
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(14) 
	private double NoShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 14);
	}

	public double getNoShortMarginRatioByVolume() {
		return NoShortMarginRatioByVolume();
	}

	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(14) 
	private CThostFtdcExchangeMarginRateAdjustField NoShortMarginRatioByVolume(double NoShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 14, NoShortMarginRatioByVolume);
		return this;
	}

	public void setNoShortMarginRatioByVolume(double noShortMarginRatioByVolume) {
		NoShortMarginRatioByVolume(noShortMarginRatioByVolume);
	}

	public CThostFtdcExchangeMarginRateAdjustField(Pointer pointer) {
		super(pointer);
	}

}

