package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcReturnResultField extends StructObject {
	public CThostFtdcReturnResultField() {
		super();
	}

	/**
	 * \u8fd4\u56de\u4ee3\u7801
	 */
	@Array({7}) 
	@Field(0) 
	private Pointer<Byte> ReturnCode() {
		return this.io.getPointerField(this, 0);
	}

	@Array({7})
	@Field(0)
	public void setReturnCode(String returnCode) {
		this.io.getPointerField(this, 0).setCString(returnCode);
	}

	public String getReturnCode() {
		return ReturnCode().getCString();
	}

	/**
	 * \u8fd4\u56de\u7801\u63cf\u8ff0
	 */
	@Array({129}) 
	@Field(1) 
	private Pointer<Byte> DescrInfoForReturnCode() {
		return this.io.getPointerField(this, 1);
	}

	@Array({129})
	@Field(1)
	public void setDescrInfoForReturnCode(String descrInfoForReturnCode) {
		this.io.getPointerField(this, 1).setCString(descrInfoForReturnCode);
	}

	public String getDescrInfoForReturnCode() {
		return DescrInfoForReturnCode().getCString();
	}

	public CThostFtdcReturnResultField(Pointer pointer) {
		super(pointer);
	}

}

