package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcSyncingInstrumentTradingRightField extends StructObject {
	public CThostFtdcSyncingInstrumentTradingRightField() {
		super();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(0) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({31})
	@Field(0)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 0).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u8303\u56f4
	 */
	@Field(1) 
	private byte InvestorRange() {
		return this.io.getByteField(this, 1);
	}

	public char getInvestorRange() {
		return (char)InvestorRange();
	}

	/**
	 * \u6295\u8d44\u8005\u8303\u56f4
	 */
	@Field(1) 
	private CThostFtdcSyncingInstrumentTradingRightField InvestorRange(byte InvestorRange) {
		this.io.setByteField(this, 1, InvestorRange);
		return this;
	}

	public void setInvestorRange(char investorRange) {
		InvestorRange((byte)investorRange);
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(2) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({11})
	@Field(2)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 2).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(3) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 3);
	}

	@Array({13})
	@Field(3)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 3).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6743\u9650
	 */
	@Field(4) 
	private byte TradingRight() {
		return this.io.getByteField(this, 4);
	}

	public char getTradingRight() {
		return (char)TradingRight();
	}

	/**
	 * \u4ea4\u6613\u6743\u9650
	 */
	@Field(4) 
	private CThostFtdcSyncingInstrumentTradingRightField TradingRight(byte TradingRight) {
		this.io.setByteField(this, 4, TradingRight);
		return this;
	}

	public void setTradingRight(char tradingRight) {
		TradingRight((byte)tradingRight);
	}

	public CThostFtdcSyncingInstrumentTradingRightField(Pointer pointer) {
		super(pointer);
	}

}

