package sims2016derive.quotationtranscode.context.struct;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcInstrumentField extends StructObject {
    public CThostFtdcInstrumentField() {
        super();
    }

    /**
     * \u5408\u7ea6\u4ee3\u7801
     */
    @Array({ 31 })
    @Field(0)
    private Pointer<Byte> InstrumentID() {
        return this.io.getPointerField(this, 0);
    }

    @Array({ 31 })
    @Field(0)
    public void setInstrumentID(String instrumentID) {
        this.io.getPointerField(this, 0).setCString(instrumentID);
    }

    public String getInstrumentID() {
        return InstrumentID().getCString();
    }

    /**
     * \u4ea4\u6613\u6240\u4ee3\u7801
     */
    @Array({ 9 })
    @Field(1)
    private Pointer<Byte> ExchangeID() {
        return this.io.getPointerField(this, 1);
    }

    @Array({ 9 })
    @Field(1)
    public void setExchangeID(String exchangeID) {
        this.io.getPointerField(this, 1).setCString(exchangeID);
    }

    public String getExchangeID() {
        return ExchangeID().getCString();
    }

    /**
     * \u5408\u7ea6\u540d\u79f0
     */
    @Array({ 21 })
    @Field(2)
    private Pointer<Byte> InstrumentName() {
        return this.io.getPointerField(this, 2);
    }

    @Array({ 21 })
    @Field(2)
    public void setInstrumentName(String instrumentName) {
        this.io.getPointerField(this, 2).setCString(instrumentName);
    }

    public String getInstrumentName() {
        return InstrumentName().getCString();
    }

    /**
     * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801
     */
    @Array({ 31 })
    @Field(3)
    private Pointer<Byte> ExchangeInstID() {
        return this.io.getPointerField(this, 3);
    }

    @Array({ 31 })
    @Field(3)
    public void setExchangeInstID(String exchangeInstID) {
        this.io.getPointerField(this, 3).setCString(exchangeInstID);
    }

    public String getExchangeInstID() {
        return ExchangeInstID().getCString();
    }

    /**
     * \u4ea7\u54c1\u4ee3\u7801
     */
    @Array({ 31 })
    @Field(4)
    private Pointer<Byte> ProductID() {
        return this.io.getPointerField(this, 4);
    }

    @Array({ 31 })
    @Field(4)
    public void setProductID(String productID) {
        this.io.getPointerField(this, 4).setCString(productID);
    }

    public String getProductID() {
        return ProductID().getCString();
    }

    /**
     * \u4ea7\u54c1\u7c7b\u578b
     */
    @Field(5)
    private byte ProductClass() {
        return this.io.getByteField(this, 5);
    }

    public char getProductClass() {
        return (char) ProductClass();
    }

    /**
     * \u4ea7\u54c1\u7c7b\u578b
     */
    @Field(5)
    private CThostFtdcInstrumentField ProductClass(byte ProductClass) {
        this.io.setByteField(this, 5, ProductClass);
        return this;
    }

    public void setProductClass(char productClass) {
        ProductClass((byte) productClass);
    }

    /**
     * \u4ea4\u5272\u5e74\u4efd
     */
    @Field(6)
    private int DeliveryYear() {
        return this.io.getIntField(this, 6);
    }

    public int getDeliveryYear() {
        return DeliveryYear();
    }

    /**
     * \u4ea4\u5272\u5e74\u4efd
     */
    @Field(6)
    private CThostFtdcInstrumentField DeliveryYear(int DeliveryYear) {
        this.io.setIntField(this, 6, DeliveryYear);
        return this;
    }

    public void setDeliveryYear(int deliveryYear) {
        DeliveryYear(deliveryYear);
    }

    /**
     * \u4ea4\u5272\u6708
     */
    @Field(7)
    private int DeliveryMonth() {
        return this.io.getIntField(this, 7);
    }

    public int getDeliveryMonth() {
        return DeliveryMonth();
    }

    /**
     * \u4ea4\u5272\u6708
     */
    @Field(7)
    private CThostFtdcInstrumentField DeliveryMonth(int DeliveryMonth) {
        this.io.setIntField(this, 7, DeliveryMonth);
        return this;
    }

    public void setDeliveryMonth(int deliveryMonth) {
        DeliveryMonth(deliveryMonth);
    }

    /**
     * \u5e02\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
     */
    @Field(8)
    private int MaxMarketOrderVolume() {
        return this.io.getIntField(this, 8);
    }

    public int getMaxMarketOrderVolume() {
        return MaxMarketOrderVolume();
    }

    /**
     * \u5e02\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
     */
    @Field(8)
    private CThostFtdcInstrumentField MaxMarketOrderVolume(int MaxMarketOrderVolume) {
        this.io.setIntField(this, 8, MaxMarketOrderVolume);
        return this;
    }

    public void setMaxMarketOrderVolume(int maxMarketOrderVolume) {
        MaxMarketOrderVolume(maxMarketOrderVolume);
    }

    /**
     * \u5e02\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
     */
    @Field(9)
    private int MinMarketOrderVolume() {
        return this.io.getIntField(this, 9);
    }

    public int getMinMarketOrderVolume() {
        return MinMarketOrderVolume();
    }

    /**
     * \u5e02\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
     */
    @Field(9)
    private CThostFtdcInstrumentField MinMarketOrderVolume(int MinMarketOrderVolume) {
        this.io.setIntField(this, 9, MinMarketOrderVolume);
        return this;
    }

    public void setMinMarketOrderVolume(int minMarketOrderVolume) {
        MinMarketOrderVolume(minMarketOrderVolume);
    }

    /**
     * \u9650\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
     */
    @Field(10)
    private int MaxLimitOrderVolume() {
        return this.io.getIntField(this, 10);
    }

    public int getMaxLimitOrderVolume() {
        return MaxLimitOrderVolume();
    }

    /**
     * \u9650\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
     */
    @Field(10)
    private CThostFtdcInstrumentField MaxLimitOrderVolume(int MaxLimitOrderVolume) {
        this.io.setIntField(this, 10, MaxLimitOrderVolume);
        return this;
    }

    public void setMaxLimitOrderVolume(int maxLimitOrderVolume) {
        MaxLimitOrderVolume(maxLimitOrderVolume);
    }

    /**
     * \u9650\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
     */
    @Field(11)
    private int MinLimitOrderVolume() {
        return this.io.getIntField(this, 11);
    }

    public int getMinLimitOrderVolume() {
        return MinLimitOrderVolume();
    }

    /**
     * \u9650\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
     */
    @Field(11)
    private CThostFtdcInstrumentField MinLimitOrderVolume(int MinLimitOrderVolume) {
        this.io.setIntField(this, 11, MinLimitOrderVolume);
        return this;
    }

    public void setMinLimitOrderVolume(int minLimitOrderVolume) {
        MinLimitOrderVolume(minLimitOrderVolume);
    }

    /**
     * \u5408\u7ea6\u6570\u91cf\u4e58\u6570
     */
    @Field(12)
    private int VolumeMultiple() {
        return this.io.getIntField(this, 12);
    }

    public int getVolumeMultiple() {
        return VolumeMultiple();
    }

    /**
     * \u5408\u7ea6\u6570\u91cf\u4e58\u6570
     */
    @Field(12)
    private CThostFtdcInstrumentField VolumeMultiple(int VolumeMultiple) {
        this.io.setIntField(this, 12, VolumeMultiple);
        return this;
    }

    public void setVolumeMultiple(int volumeMultiple) {
        VolumeMultiple(volumeMultiple);
    }

    /**
     * \u6700\u5c0f\u53d8\u52a8\u4ef7\u4f4d
     */
    @Field(13)
    private double PriceTick() {
        return this.io.getDoubleField(this, 13);
    }

    public double getPriceTick() {
        return PriceTick();
    }

    /**
     * \u6700\u5c0f\u53d8\u52a8\u4ef7\u4f4d
     */
    @Field(13)
    private CThostFtdcInstrumentField PriceTick(double PriceTick) {
        this.io.setDoubleField(this, 13, PriceTick);
        return this;
    }

    public void setPriceTick(double priceTick) {
        PriceTick(priceTick);
    }

    /**
     * \u521b\u5efa\u65e5
     */
    @Array({ 9 })
    @Field(14)
    private Pointer<Byte> CreateDate() {
        return this.io.getPointerField(this, 14);
    }

    @Array({ 9 })
    @Field(14)
    public void setCreateDate(String createDate) {
        this.io.getPointerField(this, 14).setCString(createDate);
    }

    public String getCreateDate() {
        return CreateDate().getCString();
    }

    /**
     * \u4e0a\u5e02\u65e5
     */
    @Array({ 9 })
    @Field(15)
    private Pointer<Byte> OpenDate() {
        return this.io.getPointerField(this, 15);
    }

    @Array({ 9 })
    @Field(15)
    public void setOpenDate(String openDate) {
        this.io.getPointerField(this, 15).setCString(openDate);
    }

    public String getOpenDate() {
        return OpenDate().getCString();
    }

    /**
     * \u5230\u671f\u65e5
     */
    @Array({ 9 })
    @Field(16)
    private Pointer<Byte> ExpireDate() {
        return this.io.getPointerField(this, 16);
    }

    @Array({ 9 })
    @Field(16)
    public void setExpireDate(String expireDate) {
        this.io.getPointerField(this, 16).setCString(expireDate);
    }

    public String getExpireDate() {
        return ExpireDate().getCString();
    }

    /**
     * \u5f00\u59cb\u4ea4\u5272\u65e5
     */
    @Array({ 9 })
    @Field(17)
    private Pointer<Byte> StartDelivDate() {
        return this.io.getPointerField(this, 17);
    }

    @Array({ 9 })
    @Field(17)
    public void setStartDelivDate(String startDelivDate) {
        this.io.getPointerField(this, 17).setCString(startDelivDate);
    }

    public String getStartDelivDate() {
        return StartDelivDate().getCString();
    }

    /**
     * \u7ed3\u675f\u4ea4\u5272\u65e5
     */
    @Array({ 9 })
    @Field(18)
    private Pointer<Byte> EndDelivDate() {
        return this.io.getPointerField(this, 18);
    }

    @Array({ 9 })
    @Field(18)
    public void setEndDelivDate(String endDelivDate) {
        this.io.getPointerField(this, 18).setCString(endDelivDate);
    }

    public String getEndDelivDate() {
        return EndDelivDate().getCString();
    }

    /**
     * \u5408\u7ea6\u751f\u547d\u5468\u671f\u72b6\u6001
     */
    @Field(19)
    private byte InstLifePhase() {
        return this.io.getByteField(this, 19);
    }

    public char getInstLifePhase() {
        return (char) InstLifePhase();
    }

    /**
     * \u5408\u7ea6\u751f\u547d\u5468\u671f\u72b6\u6001
     */
    @Field(19)
    private CThostFtdcInstrumentField InstLifePhase(byte InstLifePhase) {
        this.io.setByteField(this, 19, InstLifePhase);
        return this;
    }

    public void setInstLifePhase(char instLifePhase) {
        InstLifePhase((byte) instLifePhase);
    }

    /**
     * \u5f53\u524d\u662f\u5426\u4ea4\u6613
     */
    @Field(20)
    private int IsTrading() {
        return this.io.getIntField(this, 20);
    }

    public int getIsTrading() {
        return IsTrading();
    }

    /**
     * \u5f53\u524d\u662f\u5426\u4ea4\u6613
     */
    @Field(20)
    private CThostFtdcInstrumentField IsTrading(int IsTrading) {
        this.io.setIntField(this, 20, IsTrading);
        return this;
    }

    public void setIsTrading(int isTrading) {
        IsTrading(isTrading);
    }

    /**
     * \u6301\u4ed3\u7c7b\u578b
     */
    @Field(21)
    private byte PositionType() {
        return this.io.getByteField(this, 21);
    }

    public char getPositionType() {
        return (char) PositionType();
    }

    /**
     * \u6301\u4ed3\u7c7b\u578b
     */
    @Field(21)
    private CThostFtdcInstrumentField PositionType(byte PositionType) {
        this.io.setByteField(this, 21, PositionType);
        return this;
    }

    public void setPositionType(char positionType) {
        PositionType((byte) positionType);
    }

    /**
     * \u6301\u4ed3\u65e5\u671f\u7c7b\u578b
     */
    @Field(22)
    private byte PositionDateType() {
        return this.io.getByteField(this, 22);
    }

    public char getPositionDateType() {
        return (char) PositionDateType();
    }

    /**
     * \u6301\u4ed3\u65e5\u671f\u7c7b\u578b
     */
    @Field(22)
    private CThostFtdcInstrumentField PositionDateType(byte PositionDateType) {
        this.io.setByteField(this, 22, PositionDateType);
        return this;
    }

    public void setPositionDateType(char positionDateType) {
        PositionDateType((byte) positionDateType);
    }

    /**
     * \u591a\u5934\u4fdd\u8bc1\u91d1\u7387
     */
    @Field(23)
    private double LongMarginRatio() {
        return this.io.getDoubleField(this, 23);
    }

    public double getLongMarginRatio() {
        return LongMarginRatio();
    }

    /**
     * \u591a\u5934\u4fdd\u8bc1\u91d1\u7387
     */
    @Field(23)
    private CThostFtdcInstrumentField LongMarginRatio(double LongMarginRatio) {
        this.io.setDoubleField(this, 23, LongMarginRatio);
        return this;
    }

    public void setLongMarginRatio(double longMarginRatio) {
        LongMarginRatio(longMarginRatio);
    }

    /**
     * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
     */
    @Field(24)
    private double ShortMarginRatio() {
        return this.io.getDoubleField(this, 24);
    }

    public double getShortMarginRatio() {
        return ShortMarginRatio();
    }

    /**
     * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
     */
    @Field(24)
    private CThostFtdcInstrumentField ShortMarginRatio(double ShortMarginRatio) {
        this.io.setDoubleField(this, 24, ShortMarginRatio);
        return this;
    }

    public void setShortMarginRatio(double shortMarginRatio) {
        ShortMarginRatio(shortMarginRatio);
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public CThostFtdcInstrumentField(Pointer pointer) {
        super(pointer);
    }

    @Override
    public String toString() {
        return "CThostFtdcInstrumentField ["
                + "InstrumentID=" + getInstrumentID() 
                + ", ExchangeID=" + getExchangeID() 
                + ", InstrumentName=" + getInstrumentName()
                + ", ExchangeInstID=" + getExchangeInstID() 
                + ", ProductID=" + getProductID() 
                + ", ProductClass=" + getProductClass() 
                + ", DeliveryYear=" + getDeliveryYear() 
                + ", DeliveryMonth=" + getDeliveryMonth() 
                + ", MaxMarketOrderVolume=" + getMaxMarketOrderVolume()
                + ", MinMarketOrderVolume=" + getMinMarketOrderVolume() 
                + ", MaxLimitOrderVolume=" + getMaxLimitOrderVolume() 
                + ", MinLimitOrderVolume=" + getMinLimitOrderVolume() 
                + ", VolumeMultiple=" + getVolumeMultiple() 
                + ", PriceTick=" + getPriceTick() 
                + ", CreateDate=" + getCreateDate() 
                + ", OpenDate=" + getOpenDate() 
                + ", ExpireDate=" + getExpireDate() 
                + ", StartDelivDate=" + getStartDelivDate()
                + ", EndDelivDate=" + getEndDelivDate() 
                + ", InstLifePhase=" + getInstLifePhase() 
                + ", IsTrading=" + getIsTrading() 
                + ", PositionType=" + getPositionType() 
                + ", PositionDateType=" + getPositionDateType() 
                + ", LongMarginRatio=" + getLongMarginRatio()
                + ", ShortMarginRatio=" + getShortMarginRatio() + "]";
    }

}
