package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcMarketDataAveragePriceField extends StructObject {
	public CThostFtdcMarketDataAveragePriceField() {
		super();
	}

	/**
	 * \u5f53\u65e5\u5747\u4ef7
	 */
	@Field(0) 
	private double AveragePrice() {
		return this.io.getDoubleField(this, 0);
	}

	public double getAveragePrice() {
		return AveragePrice();
	}

	/**
	 * \u5f53\u65e5\u5747\u4ef7
	 */
	@Field(0) 
	private CThostFtdcMarketDataAveragePriceField AveragePrice(double AveragePrice) {
		this.io.setDoubleField(this, 0, AveragePrice);
		return this;
	}

	public void setAveragePrice(double averagePrice) {
		AveragePrice(averagePrice);
	}

	public CThostFtdcMarketDataAveragePriceField(Pointer pointer) {
		super(pointer);
	}

}

