package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcBrokerUserEventField extends StructObject {
	public CThostFtdcBrokerUserEventField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u7528\u6237\u4ee3\u7801
	 */
	@Array({16}) 
	@Field(1) 
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({16})
	@Field(1)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 1).setCString(userID);
	}

	public String getUserID() {
		return UserID().getCString();
	}

	/**
	 * \u7528\u6237\u4e8b\u4ef6\u7c7b\u578b
	 */
	@Field(2) 
	private byte UserEventType() {
		return this.io.getByteField(this, 2);
	}

	public char getUserEventType() {
		return (char)UserEventType();
	}

	/**
	 * \u7528\u6237\u4e8b\u4ef6\u7c7b\u578b
	 */
	@Field(2) 
	private CThostFtdcBrokerUserEventField UserEventType(byte UserEventType) {
		this.io.setByteField(this, 2, UserEventType);
		return this;
	}

	public void setUserEventType(char userEventType) {
		UserEventType((byte)userEventType);
	}

	/**
	 * \u7528\u6237\u4e8b\u4ef6\u5e8f\u53f7
	 */
	@Field(3) 
	private int EventSequenceNo() {
		return this.io.getIntField(this, 3);
	}

	public int getEventSequenceNo() {
		return EventSequenceNo();
	}

	/**
	 * \u7528\u6237\u4e8b\u4ef6\u5e8f\u53f7
	 */
	@Field(3) 
	private CThostFtdcBrokerUserEventField EventSequenceNo(int EventSequenceNo) {
		this.io.setIntField(this, 3, EventSequenceNo);
		return this;
	}

	public void setEventSequenceNo(int eventSequenceNo) {
		EventSequenceNo(eventSequenceNo);
	}

	/**
	 * \u4e8b\u4ef6\u53d1\u751f\u65e5\u671f
	 */
	@Array({9}) 
	@Field(4) 
	private Pointer<Byte> EventDate() {
		return this.io.getPointerField(this, 4);
	}

	@Array({9})
	@Field(4)
	public void setEventDate(String eventDate) {
		this.io.getPointerField(this, 4).setCString(eventDate);
	}

	public String getEventDate() {
		return EventDate().getCString();
	}

	/**
	 * \u4e8b\u4ef6\u53d1\u751f\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(5) 
	private Pointer<Byte> EventTime() {
		return this.io.getPointerField(this, 5);
	}

	@Array({9})
	@Field(5)
	public void setEventTime(String eventTime) {
		this.io.getPointerField(this, 5).setCString(eventTime);
	}

	public String getEventTime() {
		return EventTime().getCString();
	}

	/**
	 * \u7528\u6237\u4e8b\u4ef6\u4fe1\u606f
	 */
	@Array({1025}) 
	@Field(6) 
	private Pointer<Byte> UserEventInfo() {
		return this.io.getPointerField(this, 6);
	}

	@Array({1025})
	@Field(6)
	public void setUserEventInfo(String userEventInfo) {
		this.io.getPointerField(this, 6).setCString(userEventInfo);
	}

	public String getUserEventInfo() {
		return UserEventInfo().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(7) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 7);
	}

	@Array({13})
	@Field(7)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 7).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(8) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 8);
	}

	@Array({31})
	@Field(8)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 8).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	public CThostFtdcBrokerUserEventField(Pointer pointer) {
		super(pointer);
	}

}

