package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcReqRepealField extends StructObject {
	public CThostFtdcReqRepealField() {
		super();
	}

	/**
	 * \u51b2\u6b63\u65f6\u95f4\u95f4\u9694
	 */
	@Field(0) 
	private int RepealTimeInterval() {
		return this.io.getIntField(this, 0);
	}

	public int getRepealTimeInterval() {
		return RepealTimeInterval();
	}

	/**
	 * \u51b2\u6b63\u65f6\u95f4\u95f4\u9694
	 */
	@Field(0) 
	private CThostFtdcReqRepealField RepealTimeInterval(int RepealTimeInterval) {
		this.io.setIntField(this, 0, RepealTimeInterval);
		return this;
	}

	public void setRepealTimeInterval(int repealTimeInterval) {
		RepealTimeInterval(repealTimeInterval);
	}

	/**
	 * \u5df2\u7ecf\u51b2\u6b63\u6b21\u6570
	 */
	@Field(1) 
	private int RepealedTimes() {
		return this.io.getIntField(this, 1);
	}

	public int getRepealedTimes() {
		return RepealedTimes();
	}

	/**
	 * \u5df2\u7ecf\u51b2\u6b63\u6b21\u6570
	 */
	@Field(1) 
	private CThostFtdcReqRepealField RepealedTimes(int RepealedTimes) {
		this.io.setIntField(this, 1, RepealedTimes);
		return this;
	}

	public void setRepealedTimes(int repealedTimes) {
		RepealedTimes(repealedTimes);
	}

	/**
	 * \u94f6\u884c\u51b2\u6b63\u6807\u5fd7
	 */
	@Field(2) 
	private byte BankRepealFlag() {
		return this.io.getByteField(this, 2);
	}

	public char getBankRepealFlag() {
		return (char)BankRepealFlag();
	}

	/**
	 * \u94f6\u884c\u51b2\u6b63\u6807\u5fd7
	 */
	@Field(2) 
	private CThostFtdcReqRepealField BankRepealFlag(byte BankRepealFlag) {
		this.io.setByteField(this, 2, BankRepealFlag);
		return this;
	}

	public void setBankRepealFlag(char bankRepealFlag) {
		BankRepealFlag((byte)bankRepealFlag);
	}

	/**
	 * \u671f\u5546\u51b2\u6b63\u6807\u5fd7
	 */
	@Field(3) 
	private byte BrokerRepealFlag() {
		return this.io.getByteField(this, 3);
	}

	public char getBrokerRepealFlag() {
		return (char)BrokerRepealFlag();
	}

	/**
	 * \u671f\u5546\u51b2\u6b63\u6807\u5fd7
	 */
	@Field(3) 
	private CThostFtdcReqRepealField BrokerRepealFlag(byte BrokerRepealFlag) {
		this.io.setByteField(this, 3, BrokerRepealFlag);
		return this;
	}

	public void setBrokerRepealFlag(char brokerRepealFlag) {
		BrokerRepealFlag((byte)brokerRepealFlag);
	}

	/**
	 * \u88ab\u51b2\u6b63\u5e73\u53f0\u6d41\u6c34\u53f7
	 */
	@Field(4) 
	private int PlateRepealSerial() {
		return this.io.getIntField(this, 4);
	}

	public int getPlateRepealSerial() {
		return PlateRepealSerial();
	}

	/**
	 * \u88ab\u51b2\u6b63\u5e73\u53f0\u6d41\u6c34\u53f7
	 */
	@Field(4) 
	private CThostFtdcReqRepealField PlateRepealSerial(int PlateRepealSerial) {
		this.io.setIntField(this, 4, PlateRepealSerial);
		return this;
	}

	public void setPlateRepealSerial(int plateRepealSerial) {
		PlateRepealSerial(plateRepealSerial);
	}

	/**
	 * \u88ab\u51b2\u6b63\u94f6\u884c\u6d41\u6c34\u53f7
	 */
	@Array({13}) 
	@Field(5) 
	private Pointer<Byte> BankRepealSerial() {
		return this.io.getPointerField(this, 5);
	}

	@Array({13})
	@Field(5)
	public void setBankRepealSerial(String bankRepealSerial) {
		this.io.getPointerField(this, 5).setCString(bankRepealSerial);
	}

	public String getBankRepealSerial() {
		return BankRepealSerial().getCString();
	}

	/**
	 * \u88ab\u51b2\u6b63\u671f\u8d27\u6d41\u6c34\u53f7
	 */
	@Field(6) 
	private int FutureRepealSerial() {
		return this.io.getIntField(this, 6);
	}

	public int getFutureRepealSerial() {
		return FutureRepealSerial();
	}

	/**
	 * \u88ab\u51b2\u6b63\u671f\u8d27\u6d41\u6c34\u53f7
	 */
	@Field(6) 
	private CThostFtdcReqRepealField FutureRepealSerial(int FutureRepealSerial) {
		this.io.setIntField(this, 6, FutureRepealSerial);
		return this;
	}

	public void setFutureRepealSerial(int futureRepealSerial) {
		FutureRepealSerial(futureRepealSerial);
	}

	/**
	 * \u4e1a\u52a1\u529f\u80fd\u7801
	 */
	@Array({7}) 
	@Field(7) 
	private Pointer<Byte> TradeCode() {
		return this.io.getPointerField(this, 7);
	}

	@Array({7})
	@Field(7)
	public void setTradeCode(String tradeCode) {
		this.io.getPointerField(this, 7).setCString(tradeCode);
	}

	public String getTradeCode() {
		return TradeCode().getCString();
	}

	/**
	 * \u94f6\u884c\u4ee3\u7801
	 */
	@Array({4}) 
	@Field(8) 
	private Pointer<Byte> BankID() {
		return this.io.getPointerField(this, 8);
	}

	@Array({4})
	@Field(8)
	public void setBankID(String bankID) {
		this.io.getPointerField(this, 8).setCString(bankID);
	}

	public String getBankID() {
		return BankID().getCString();
	}

	/**
	 * \u94f6\u884c\u5206\u652f\u673a\u6784\u4ee3\u7801
	 */
	@Array({5}) 
	@Field(9) 
	private Pointer<Byte> BankBranchID() {
		return this.io.getPointerField(this, 9);
	}

	@Array({5})
	@Field(9)
	public void setBankBranchID(String bankBranchID) {
		this.io.getPointerField(this, 9).setCString(bankBranchID);
	}

	public String getBankBranchID() {
		return BankBranchID().getCString();
	}

	/**
	 * \u671f\u5546\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(10) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 10);
	}

	@Array({11})
	@Field(10)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 10).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u671f\u5546\u5206\u652f\u673a\u6784\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(11) 
	private Pointer<Byte> BrokerBranchID() {
		return this.io.getPointerField(this, 11);
	}

	@Array({31})
	@Field(11)
	public void setBrokerBranchID(String brokerBranchID) {
		this.io.getPointerField(this, 11).setCString(brokerBranchID);
	}

	public String getBrokerBranchID() {
		return BrokerBranchID().getCString();
	}

	/**
	 * \u4ea4\u6613\u65e5\u671f
	 */
	@Array({9}) 
	@Field(12) 
	private Pointer<Byte> TradeDate() {
		return this.io.getPointerField(this, 12);
	}

	@Array({9})
	@Field(12)
	public void setTradeDate(String tradeDate) {
		this.io.getPointerField(this, 12).setCString(tradeDate);
	}

	public String getTradeDate() {
		return TradeDate().getCString();
	}

	/**
	 * \u4ea4\u6613\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(13) 
	private Pointer<Byte> TradeTime() {
		return this.io.getPointerField(this, 13);
	}

	@Array({9})
	@Field(13)
	public void setTradeTime(String tradeTime) {
		this.io.getPointerField(this, 13).setCString(tradeTime);
	}

	public String getTradeTime() {
		return TradeTime().getCString();
	}

	/**
	 * \u94f6\u884c\u6d41\u6c34\u53f7
	 */
	@Array({13}) 
	@Field(14) 
	private Pointer<Byte> BankSerial() {
		return this.io.getPointerField(this, 14);
	}

	@Array({13})
	@Field(14)
	public void setBankSerial(String bankSerial) {
		this.io.getPointerField(this, 14).setCString(bankSerial);
	}

	public String getBankSerial() {
		return BankSerial().getCString();
	}

	/**
	 * \u4ea4\u6613\u7cfb\u7edf\u65e5\u671f
	 */
	@Array({9}) 
	@Field(15) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 15);
	}

	@Array({9})
	@Field(15)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 15).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u94f6\u671f\u5e73\u53f0\u6d88\u606f\u6d41\u6c34\u53f7
	 */
	@Field(16) 
	private int PlateSerial() {
		return this.io.getIntField(this, 16);
	}

	public int getPlateSerial() {
		return PlateSerial();
	}

	/**
	 * \u94f6\u671f\u5e73\u53f0\u6d88\u606f\u6d41\u6c34\u53f7
	 */
	@Field(16) 
	private CThostFtdcReqRepealField PlateSerial(int PlateSerial) {
		this.io.setIntField(this, 16, PlateSerial);
		return this;
	}

	public void setPlateSerial(int plateSerial) {
		PlateSerial(plateSerial);
	}

	/**
	 * \u6700\u540e\u5206\u7247\u6807\u5fd7
	 */
	@Field(17) 
	private byte LastFragment() {
		return this.io.getByteField(this, 17);
	}

	public char getLastFragment() {
		return (char)LastFragment();
	}

	/**
	 * \u6700\u540e\u5206\u7247\u6807\u5fd7
	 */
	@Field(17) 
	private CThostFtdcReqRepealField LastFragment(byte LastFragment) {
		this.io.setByteField(this, 17, LastFragment);
		return this;
	}

	public void setLastFragment(char lastFragment) {
		LastFragment((byte)lastFragment);
	}

	/**
	 * \u4f1a\u8bdd\u53f7
	 */
	@Field(18) 
	private int SessionID() {
		return this.io.getIntField(this, 18);
	}

	public int getSessionID() {
		return SessionID();
	}

	/**
	 * \u4f1a\u8bdd\u53f7
	 */
	@Field(18) 
	private CThostFtdcReqRepealField SessionID(int SessionID) {
		this.io.setIntField(this, 18, SessionID);
		return this;
	}

	public void setSessionID(int sessionID) {
		SessionID(sessionID);
	}

	/**
	 * \u5ba2\u6237\u59d3\u540d
	 */
	@Array({51}) 
	@Field(19) 
	private Pointer<Byte> CustomerName() {
		return this.io.getPointerField(this, 19);
	}

	@Array({51})
	@Field(19)
	public void setCustomerName(String customerName) {
		this.io.getPointerField(this, 19).setCString(customerName);
	}

	public String getCustomerName() {
		return CustomerName().getCString();
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(20) 
	private byte IdCardType() {
		return this.io.getByteField(this, 20);
	}

	public char getIdCardType() {
		return (char)IdCardType();
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(20) 
	private CThostFtdcReqRepealField IdCardType(byte IdCardType) {
		this.io.setByteField(this, 20, IdCardType);
		return this;
	}

	public void setIdCardType(char idCardType) {
		IdCardType((byte)idCardType);
	}

	/**
	 * \u8bc1\u4ef6\u53f7\u7801
	 */
	@Array({51}) 
	@Field(21) 
	private Pointer<Byte> IdentifiedCardNo() {
		return this.io.getPointerField(this, 21);
	}

	@Array({51})
	@Field(21)
	public void setIdentifiedCardNo(String identifiedCardNo) {
		this.io.getPointerField(this, 21).setCString(identifiedCardNo);
	}

	public String getIdentifiedCardNo() {
		return IdentifiedCardNo().getCString();
	}

	/**
	 * \u5ba2\u6237\u7c7b\u578b
	 */
	@Field(22) 
	private byte CustType() {
		return this.io.getByteField(this, 22);
	}

	public char getCustType() {
		return (char)CustType();
	}

	/**
	 * \u5ba2\u6237\u7c7b\u578b
	 */
	@Field(22) 
	private CThostFtdcReqRepealField CustType(byte CustType) {
		this.io.setByteField(this, 22, CustType);
		return this;
	}

	public void setCustType(char custType) {
		CustType((byte)custType);
	}

	/**
	 * \u94f6\u884c\u5e10\u53f7
	 */
	@Array({41}) 
	@Field(23) 
	private Pointer<Byte> BankAccount() {
		return this.io.getPointerField(this, 23);
	}

	@Array({41})
	@Field(23)
	public void setBankAccount(String bankAccount) {
		this.io.getPointerField(this, 23).setCString(bankAccount);
	}

	public String getBankAccount() {
		return BankAccount().getCString();
	}

	/**
	 * \u94f6\u884c\u5bc6\u7801
	 */
	@Array({41}) 
	@Field(24) 
	private Pointer<Byte> BankPassWord() {
		return this.io.getPointerField(this, 24);
	}

	@Array({41})
	@Field(24)
	public void setBankPassWord(String bankPassWord) {
		this.io.getPointerField(this, 24).setCString(bankPassWord);
	}

	public String getBankPassWord() {
		return BankPassWord().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u5e10\u53f7
	 */
	@Array({13}) 
	@Field(25) 
	private Pointer<Byte> AccountID() {
		return this.io.getPointerField(this, 25);
	}

	@Array({13})
	@Field(25)
	public void setAccountID(String accountID) {
		this.io.getPointerField(this, 25).setCString(accountID);
	}

	public String getAccountID() {
		return AccountID().getCString();
	}

	/**
	 * \u671f\u8d27\u5bc6\u7801
	 */
	@Array({41}) 
	@Field(26) 
	private Pointer<Byte> Password() {
		return this.io.getPointerField(this, 26);
	}

	@Array({41})
	@Field(26)
	public void setPassword(String password) {
		this.io.getPointerField(this, 26).setCString(password);
	}

	public String getPassword() {
		return Password().getCString();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(27) 
	private int InstallID() {
		return this.io.getIntField(this, 27);
	}

	public int getInstallID() {
		return InstallID();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(27) 
	private CThostFtdcReqRepealField InstallID(int InstallID) {
		this.io.setIntField(this, 27, InstallID);
		return this;
	}

	public void setInstallID(int installID) {
		InstallID(installID);
	}

	/**
	 * \u671f\u8d27\u516c\u53f8\u6d41\u6c34\u53f7
	 */
	@Field(28) 
	private int FutureSerial() {
		return this.io.getIntField(this, 28);
	}

	public int getFutureSerial() {
		return FutureSerial();
	}

	/**
	 * \u671f\u8d27\u516c\u53f8\u6d41\u6c34\u53f7
	 */
	@Field(28) 
	private CThostFtdcReqRepealField FutureSerial(int FutureSerial) {
		this.io.setIntField(this, 28, FutureSerial);
		return this;
	}

	public void setFutureSerial(int futureSerial) {
		FutureSerial(futureSerial);
	}

	/**
	 * \u7528\u6237\u6807\u8bc6
	 */
	@Array({16}) 
	@Field(29) 
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 29);
	}

	@Array({16})
	@Field(29)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 29).setCString(userID);
	}

	public String getUserID() {
		return UserID().getCString();
	}

	/**
	 * \u9a8c\u8bc1\u5ba2\u6237\u8bc1\u4ef6\u53f7\u7801\u6807\u5fd7
	 */
	@Field(30) 
	private byte VerifyCertNoFlag() {
		return this.io.getByteField(this, 30);
	}

	public char getVerifyCertNoFlag() {
		return (char)VerifyCertNoFlag();
	}

	/**
	 * \u9a8c\u8bc1\u5ba2\u6237\u8bc1\u4ef6\u53f7\u7801\u6807\u5fd7
	 */
	@Field(30) 
	private CThostFtdcReqRepealField VerifyCertNoFlag(byte VerifyCertNoFlag) {
		this.io.setByteField(this, 30, VerifyCertNoFlag);
		return this;
	}

	public void setVerifyCertNoFlag(char verifyCertNoFlag) {
		VerifyCertNoFlag((byte)verifyCertNoFlag);
	}

	/**
	 * \u5e01\u79cd\u4ee3\u7801
	 */
	@Array({4}) 
	@Field(31) 
	private Pointer<Byte> CurrencyID() {
		return this.io.getPointerField(this, 31);
	}

	@Array({4})
	@Field(31)
	public void setCurrencyID(String currencyID) {
		this.io.getPointerField(this, 31).setCString(currencyID);
	}

	public String getCurrencyID() {
		return CurrencyID().getCString();
	}

	/**
	 * \u8f6c\u5e10\u91d1\u989d
	 */
	@Field(32) 
	private double TradeAmount() {
		return this.io.getDoubleField(this, 32);
	}

	public double getTradeAmount() {
		return TradeAmount();
	}

	/**
	 * \u8f6c\u5e10\u91d1\u989d
	 */
	@Field(32) 
	private CThostFtdcReqRepealField TradeAmount(double TradeAmount) {
		this.io.setDoubleField(this, 32, TradeAmount);
		return this;
	}

	public void setTradeAmount(double tradeAmount) {
		TradeAmount(tradeAmount);
	}

	/**
	 * \u671f\u8d27\u53ef\u53d6\u91d1\u989d
	 */
	@Field(33) 
	private double FutureFetchAmount() {
		return this.io.getDoubleField(this, 33);
	}

	public double getFutureFetchAmount() {
		return FutureFetchAmount();
	}

	/**
	 * \u671f\u8d27\u53ef\u53d6\u91d1\u989d
	 */
	@Field(33) 
	private CThostFtdcReqRepealField FutureFetchAmount(double FutureFetchAmount) {
		this.io.setDoubleField(this, 33, FutureFetchAmount);
		return this;
	}

	public void setFutureFetchAmount(double futureFetchAmount) {
		FutureFetchAmount(futureFetchAmount);
	}

	/**
	 * \u8d39\u7528\u652f\u4ed8\u6807\u5fd7
	 */
	@Field(34) 
	private byte FeePayFlag() {
		return this.io.getByteField(this, 34);
	}

	public char getFeePayFlag() {
		return (char)FeePayFlag();
	}

	/**
	 * \u8d39\u7528\u652f\u4ed8\u6807\u5fd7
	 */
	@Field(34) 
	private CThostFtdcReqRepealField FeePayFlag(byte FeePayFlag) {
		this.io.setByteField(this, 34, FeePayFlag);
		return this;
	}

	public void setFeePayFlag(char feePayFlag) {
		FeePayFlag((byte)feePayFlag);
	}

	/**
	 * \u5e94\u6536\u5ba2\u6237\u8d39\u7528
	 */
	@Field(35) 
	private double CustFee() {
		return this.io.getDoubleField(this, 35);
	}

	public double getCustFee() {
		return CustFee();
	}

	/**
	 * \u5e94\u6536\u5ba2\u6237\u8d39\u7528
	 */
	@Field(35) 
	private CThostFtdcReqRepealField CustFee(double CustFee) {
		this.io.setDoubleField(this, 35, CustFee);
		return this;
	}

	public void setCustFee(double custFee) {
		CustFee(custFee);
	}

	/**
	 * \u5e94\u6536\u671f\u8d27\u516c\u53f8\u8d39\u7528
	 */
	@Field(36) 
	private double BrokerFee() {
		return this.io.getDoubleField(this, 36);
	}

	public double getBrokerFee() {
		return BrokerFee();
	}

	/**
	 * \u5e94\u6536\u671f\u8d27\u516c\u53f8\u8d39\u7528
	 */
	@Field(36) 
	private CThostFtdcReqRepealField BrokerFee(double BrokerFee) {
		this.io.setDoubleField(this, 36, BrokerFee);
		return this;
	}

	public void setBrokerFee(double brokerFee) {
		BrokerFee(brokerFee);
	}

	/**
	 * \u53d1\u9001\u65b9\u7ed9\u63a5\u6536\u65b9\u7684\u6d88\u606f
	 */
	@Array({129}) 
	@Field(37) 
	private Pointer<Byte> Message() {
		return this.io.getPointerField(this, 37);
	}

	@Array({129})
	@Field(37)
	public void setMessage(String message) {
		this.io.getPointerField(this, 37).setCString(message);
	}

	public String getMessage() {
		return Message().getCString();
	}

	/**
	 * \u6458\u8981
	 */
	@Array({36}) 
	@Field(38) 
	private Pointer<Byte> Digest() {
		return this.io.getPointerField(this, 38);
	}

	@Array({36})
	@Field(38)
	public void setDigest(String digest) {
		this.io.getPointerField(this, 38).setCString(digest);
	}

	public String getDigest() {
		return Digest().getCString();
	}

	/**
	 * \u94f6\u884c\u5e10\u53f7\u7c7b\u578b
	 */
	@Field(39) 
	private byte BankAccType() {
		return this.io.getByteField(this, 39);
	}

	public char getBankAccType() {
		return (char)BankAccType();
	}

	/**
	 * \u94f6\u884c\u5e10\u53f7\u7c7b\u578b
	 */
	@Field(39) 
	private CThostFtdcReqRepealField BankAccType(byte BankAccType) {
		this.io.setByteField(this, 39, BankAccType);
		return this;
	}

	public void setBankAccType(char bankAccType) {
		BankAccType((byte)bankAccType);
	}

	/**
	 * \u6e20\u9053\u6807\u5fd7
	 */
	@Array({3}) 
	@Field(40) 
	private Pointer<Byte> DeviceID() {
		return this.io.getPointerField(this, 40);
	}

	@Array({3})
	@Field(40)
	public void setDeviceID(String deviceID) {
		this.io.getPointerField(this, 40).setCString(deviceID);
	}

	public String getDeviceID() {
		return DeviceID().getCString();
	}

	/**
	 * \u671f\u8d27\u5355\u4f4d\u5e10\u53f7\u7c7b\u578b
	 */
	@Field(41) 
	private byte BankSecuAccType() {
		return this.io.getByteField(this, 41);
	}

	public char getBankSecuAccType() {
		return (char)BankSecuAccType();
	}

	/**
	 * \u671f\u8d27\u5355\u4f4d\u5e10\u53f7\u7c7b\u578b
	 */
	@Field(41) 
	private CThostFtdcReqRepealField BankSecuAccType(byte BankSecuAccType) {
		this.io.setByteField(this, 41, BankSecuAccType);
		return this;
	}

	public void setBankSecuAccType(char bankSecuAccType) {
		BankSecuAccType((byte)bankSecuAccType);
	}

	/**
	 * \u671f\u8d27\u516c\u53f8\u94f6\u884c\u7f16\u7801
	 */
	@Array({33}) 
	@Field(42) 
	private Pointer<Byte> BrokerIDByBank() {
		return this.io.getPointerField(this, 42);
	}

	@Array({33})
	@Field(42)
	public void setBrokerIDByBank(String brokerIDByBank) {
		this.io.getPointerField(this, 42).setCString(brokerIDByBank);
	}

	public String getBrokerIDByBank() {
		return BrokerIDByBank().getCString();
	}

	/**
	 * \u671f\u8d27\u5355\u4f4d\u5e10\u53f7
	 */
	@Array({41}) 
	@Field(43) 
	private Pointer<Byte> BankSecuAcc() {
		return this.io.getPointerField(this, 43);
	}

	@Array({41})
	@Field(43)
	public void setBankSecuAcc(String bankSecuAcc) {
		this.io.getPointerField(this, 43).setCString(bankSecuAcc);
	}

	public String getBankSecuAcc() {
		return BankSecuAcc().getCString();
	}

	/**
	 * \u94f6\u884c\u5bc6\u7801\u6807\u5fd7
	 */
	@Field(44) 
	private byte BankPwdFlag() {
		return this.io.getByteField(this, 44);
	}

	public char getBankPwdFlag() {
		return (char)BankPwdFlag();
	}

	/**
	 * \u94f6\u884c\u5bc6\u7801\u6807\u5fd7
	 */
	@Field(44) 
	private CThostFtdcReqRepealField BankPwdFlag(byte BankPwdFlag) {
		this.io.setByteField(this, 44, BankPwdFlag);
		return this;
	}

	public void setBankPwdFlag(char bankPwdFlag) {
		BankPwdFlag((byte)bankPwdFlag);
	}

	/**
	 * \u671f\u8d27\u8d44\u91d1\u5bc6\u7801\u6838\u5bf9\u6807\u5fd7
	 */
	@Field(45) 
	private byte SecuPwdFlag() {
		return this.io.getByteField(this, 45);
	}

	public char getSecuPwdFlag() {
		return (char)SecuPwdFlag();
	}

	/**
	 * \u671f\u8d27\u8d44\u91d1\u5bc6\u7801\u6838\u5bf9\u6807\u5fd7
	 */
	@Field(45) 
	private CThostFtdcReqRepealField SecuPwdFlag(byte SecuPwdFlag) {
		this.io.setByteField(this, 45, SecuPwdFlag);
		return this;
	}

	public void setSecuPwdFlag(char secuPwdFlag) {
		SecuPwdFlag((byte)secuPwdFlag);
	}

	/**
	 * \u4ea4\u6613\u67dc\u5458
	 */
	@Array({17}) 
	@Field(46) 
	private Pointer<Byte> OperNo() {
		return this.io.getPointerField(this, 46);
	}

	@Array({17})
	@Field(46)
	public void setOperNo(String operNo) {
		this.io.getPointerField(this, 46).setCString(operNo);
	}

	public String getOperNo() {
		return OperNo().getCString();
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(47) 
	private int RequestID() {
		return this.io.getIntField(this, 47);
	}

	public int getRequestID() {
		return RequestID();
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(47) 
	private CThostFtdcReqRepealField RequestID(int RequestID) {
		this.io.setIntField(this, 47, RequestID);
		return this;
	}

	public void setRequestID(int requestID) {
		RequestID(requestID);
	}

	/**
	 * \u4ea4\u6613ID
	 */
	@Field(48) 
	private int TID() {
		return this.io.getIntField(this, 48);
	}

	public int getTID() {
		return TID();
	}

	/**
	 * \u4ea4\u6613ID
	 */
	@Field(48) 
	private CThostFtdcReqRepealField TID(int TID) {
		this.io.setIntField(this, 48, TID);
		return this;
	}

	public void setTID(int tID) {
		TID(tID);
	}

	/**
	 * \u8f6c\u8d26\u4ea4\u6613\u72b6\u6001
	 */
	@Field(49) 
	private byte TransferStatus() {
		return this.io.getByteField(this, 49);
	}

	public char getTransferStatus() {
		return (char)TransferStatus();
	}

	/**
	 * \u8f6c\u8d26\u4ea4\u6613\u72b6\u6001
	 */
	@Field(49) 
	private CThostFtdcReqRepealField TransferStatus(byte TransferStatus) {
		this.io.setByteField(this, 49, TransferStatus);
		return this;
	}

	public void setTransferStatus(char transferStatus) {
		TransferStatus((byte)transferStatus);
	}

	public CThostFtdcReqRepealField(Pointer pointer) {
		super(pointer);
	}

}

