package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcProductField extends StructObject {
	public CThostFtdcProductField() {
		super();
	}

	/**
	 * \u4ea7\u54c1\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(0) 
	private Pointer<Byte> ProductID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({31})
	@Field(0)
	public void setProductID(String productID) {
		this.io.getPointerField(this, 0).setCString(productID);
	}

	public String getProductID() {
		return ProductID().getCString();
	}

	/**
	 * \u4ea7\u54c1\u540d\u79f0
	 */
	@Array({21}) 
	@Field(1) 
	private Pointer<Byte> ProductName() {
		return this.io.getPointerField(this, 1);
	}

	@Array({21})
	@Field(1)
	public void setProductName(String productName) {
		this.io.getPointerField(this, 1).setCString(productName);
	}

	public String getProductName() {
		return ProductName().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(2) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({9})
	@Field(2)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 2).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u4ea7\u54c1\u7c7b\u578b
	 */
	@Field(3) 
	private byte ProductClass() {
		return this.io.getByteField(this, 3);
	}

	public char getProductClass() {
		return (char)ProductClass();
	}

	/**
	 * \u4ea7\u54c1\u7c7b\u578b
	 */
	@Field(3) 
	private CThostFtdcProductField ProductClass(byte ProductClass) {
		this.io.setByteField(this, 3, ProductClass);
		return this;
	}

	public void setProductClass(char productClass) {
		ProductClass((byte)productClass);
	}

	/**
	 * \u5408\u7ea6\u6570\u91cf\u4e58\u6570
	 */
	@Field(4) 
	private int VolumeMultiple() {
		return this.io.getIntField(this, 4);
	}

	public int getVolumeMultiple() {
		return VolumeMultiple();
	}

	/**
	 * \u5408\u7ea6\u6570\u91cf\u4e58\u6570
	 */
	@Field(4) 
	private CThostFtdcProductField VolumeMultiple(int VolumeMultiple) {
		this.io.setIntField(this, 4, VolumeMultiple);
		return this;
	}

	public void setVolumeMultiple(int volumeMultiple) {
		VolumeMultiple(volumeMultiple);
	}

	/**
	 * \u6700\u5c0f\u53d8\u52a8\u4ef7\u4f4d
	 */
	@Field(5) 
	private double PriceTick() {
		return this.io.getDoubleField(this, 5);
	}

	public double getPriceTick() {
		return PriceTick();
	}

	/**
	 * \u6700\u5c0f\u53d8\u52a8\u4ef7\u4f4d
	 */
	@Field(5) 
	private CThostFtdcProductField PriceTick(double PriceTick) {
		this.io.setDoubleField(this, 5, PriceTick);
		return this;
	}

	public void setPriceTick(double priceTick) {
		PriceTick(priceTick);
	}

	/**
	 * \u5e02\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
	 */
	@Field(6) 
	private int MaxMarketOrderVolume() {
		return this.io.getIntField(this, 6);
	}

	public int getMaxMarketOrderVolume() {
		return MaxMarketOrderVolume();
	}

	/**
	 * \u5e02\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
	 */
	@Field(6) 
	private CThostFtdcProductField MaxMarketOrderVolume(int MaxMarketOrderVolume) {
		this.io.setIntField(this, 6, MaxMarketOrderVolume);
		return this;
	}

	public void setMaxMarketOrderVolume(int maxMarketOrderVolume) {
		MaxMarketOrderVolume(maxMarketOrderVolume);
	}

	/**
	 * \u5e02\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
	 */
	@Field(7) 
	private int MinMarketOrderVolume() {
		return this.io.getIntField(this, 7);
	}

	public int getMinMarketOrderVolume() {
		return MinMarketOrderVolume();
	}

	/**
	 * \u5e02\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
	 */
	@Field(7) 
	private CThostFtdcProductField MinMarketOrderVolume(int MinMarketOrderVolume) {
		this.io.setIntField(this, 7, MinMarketOrderVolume);
		return this;
	}

	public void setMinMarketOrderVolume(int minMarketOrderVolume) {
		MinMarketOrderVolume(minMarketOrderVolume);
	}

	/**
	 * \u9650\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
	 */
	@Field(8) 
	private int MaxLimitOrderVolume() {
		return this.io.getIntField(this, 8);
	}

	public int getMaxLimitOrderVolume() {
		return MaxLimitOrderVolume();
	}

	/**
	 * \u9650\u4ef7\u5355\u6700\u5927\u4e0b\u5355\u91cf
	 */
	@Field(8) 
	private CThostFtdcProductField MaxLimitOrderVolume(int MaxLimitOrderVolume) {
		this.io.setIntField(this, 8, MaxLimitOrderVolume);
		return this;
	}

	public void setMaxLimitOrderVolume(int maxLimitOrderVolume) {
		MaxLimitOrderVolume(maxLimitOrderVolume);
	}

	/**
	 * \u9650\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
	 */
	@Field(9) 
	private int MinLimitOrderVolume() {
		return this.io.getIntField(this, 9);
	}

	public int getMinLimitOrderVolume() {
		return MinLimitOrderVolume();
	}

	/**
	 * \u9650\u4ef7\u5355\u6700\u5c0f\u4e0b\u5355\u91cf
	 */
	@Field(9) 
	private CThostFtdcProductField MinLimitOrderVolume(int MinLimitOrderVolume) {
		this.io.setIntField(this, 9, MinLimitOrderVolume);
		return this;
	}

	public void setMinLimitOrderVolume(int minLimitOrderVolume) {
		MinLimitOrderVolume(minLimitOrderVolume);
	}

	/**
	 * \u6301\u4ed3\u7c7b\u578b
	 */
	@Field(10) 
	private byte PositionType() {
		return this.io.getByteField(this, 10);
	}

	public char getPositionType() {
		return (char)PositionType();
	}

	/**
	 * \u6301\u4ed3\u7c7b\u578b
	 */
	@Field(10) 
	private CThostFtdcProductField PositionType(byte PositionType) {
		this.io.setByteField(this, 10, PositionType);
		return this;
	}

	public void setPositionType(char positionType) {
		PositionType((byte)positionType);
	}

	/**
	 * \u6301\u4ed3\u65e5\u671f\u7c7b\u578b
	 */
	@Field(11) 
	private byte PositionDateType() {
		return this.io.getByteField(this, 11);
	}

	public char getPositionDateType() {
		return (char)PositionDateType();
	}

	/**
	 * \u6301\u4ed3\u65e5\u671f\u7c7b\u578b
	 */
	@Field(11) 
	private CThostFtdcProductField PositionDateType(byte PositionDateType) {
		this.io.setByteField(this, 11, PositionDateType);
		return this;
	}

	public void setPositionDateType(char positionDateType) {
		PositionDateType((byte)positionDateType);
	}

	/**
	 * \u5e73\u4ed3\u5904\u7406\u7c7b\u578b
	 */
	@Field(12) 
	private byte CloseDealType() {
		return this.io.getByteField(this, 12);
	}

	public char getCloseDealType() {
		return (char)CloseDealType();
	}

	/**
	 * \u5e73\u4ed3\u5904\u7406\u7c7b\u578b
	 */
	@Field(12) 
	private CThostFtdcProductField CloseDealType(byte CloseDealType) {
		this.io.setByteField(this, 12, CloseDealType);
		return this;
	}

	public void setCloseDealType(char closeDealType) {
		CloseDealType((byte)closeDealType);
	}

	public CThostFtdcProductField(Pointer pointer) {
		super(pointer);
	}

}

