package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcExchangeSequenceField extends StructObject {
	public CThostFtdcExchangeSequenceField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(0) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9})
	@Field(0)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 0).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(1) 
	private int SequenceNo() {
		return this.io.getIntField(this, 1);
	}

	public int getSequenceNo() {
		return SequenceNo();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(1) 
	private CThostFtdcExchangeSequenceField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 1, SequenceNo);
		return this;
	}

	public void setSequenceNo(int sequenceNo) {
		SequenceNo(sequenceNo);
	}

	/**
	 * \u5408\u7ea6\u4ea4\u6613\u72b6\u6001
	 */
	@Field(2) 
	private byte MarketStatus() {
		return this.io.getByteField(this, 2);
	}

	public char getMarketStatus() {
		return (char)MarketStatus();
	}

	/**
	 * \u5408\u7ea6\u4ea4\u6613\u72b6\u6001
	 */
	@Field(2) 
	private CThostFtdcExchangeSequenceField MarketStatus(byte MarketStatus) {
		this.io.setByteField(this, 2, MarketStatus);
		return this;
	}

	public void setMarketStatus(char marketStatus) {
		MarketStatus((byte)marketStatus);
	}

	public CThostFtdcExchangeSequenceField(Pointer pointer) {
		super(pointer);
	}

}

