package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTradingAccountField extends StructObject {
	public CThostFtdcTradingAccountField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u5e10\u53f7
	 */
	@Array({13}) 
	@Field(1) 
	private Pointer<Byte> AccountID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({13})
	@Field(1)
	public void setAccountID(String accountID) {
		this.io.getPointerField(this, 1).setCString(accountID);
	}

	public String getAccountID() {
		return AccountID().getCString();
	}

	/**
	 * \u4e0a\u6b21\u8d28\u62bc\u91d1\u989d
	 */
	@Field(2) 
	private double PreMortgage() {
		return this.io.getDoubleField(this, 2);
	}

	public double getPreMortgage() {
		return PreMortgage();
	}

	/**
	 * \u4e0a\u6b21\u8d28\u62bc\u91d1\u989d
	 */
	@Field(2) 
	private CThostFtdcTradingAccountField PreMortgage(double PreMortgage) {
		this.io.setDoubleField(this, 2, PreMortgage);
		return this;
	}

	public void setPreMortgage(double preMortgage) {
		PreMortgage(preMortgage);
	}

	/**
	 * \u4e0a\u6b21\u4fe1\u7528\u989d\u5ea6
	 */
	@Field(3) 
	private double PreCredit() {
		return this.io.getDoubleField(this, 3);
	}

	public double getPreCredit() {
		return PreCredit();
	}

	/**
	 * \u4e0a\u6b21\u4fe1\u7528\u989d\u5ea6
	 */
	@Field(3) 
	private CThostFtdcTradingAccountField PreCredit(double PreCredit) {
		this.io.setDoubleField(this, 3, PreCredit);
		return this;
	}

	public void setPreCredit(double preCredit) {
		PreCredit(preCredit);
	}

	/**
	 * \u4e0a\u6b21\u5b58\u6b3e\u989d
	 */
	@Field(4) 
	private double PreDeposit() {
		return this.io.getDoubleField(this, 4);
	}

	public double getPreDeposit() {
		return PreDeposit();
	}

	/**
	 * \u4e0a\u6b21\u5b58\u6b3e\u989d
	 */
	@Field(4) 
	private CThostFtdcTradingAccountField PreDeposit(double PreDeposit) {
		this.io.setDoubleField(this, 4, PreDeposit);
		return this;
	}

	public void setPreDeposit(double preDeposit) {
		PreDeposit(preDeposit);
	}

	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(5) 
	private double PreBalance() {
		return this.io.getDoubleField(this, 5);
	}

	public double getPreBalance() {
		return PreBalance();
	}

	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(5) 
	private CThostFtdcTradingAccountField PreBalance(double PreBalance) {
		this.io.setDoubleField(this, 5, PreBalance);
		return this;
	}

	public void setPreBalance(double preBalance) {
		PreBalance(preBalance);
	}

	/**
	 * \u4e0a\u6b21\u5360\u7528\u7684\u4fdd\u8bc1\u91d1
	 */
	@Field(6) 
	private double PreMargin() {
		return this.io.getDoubleField(this, 6);
	}

	public double getPreMargin() {
		return PreMargin();
	}

	/**
	 * \u4e0a\u6b21\u5360\u7528\u7684\u4fdd\u8bc1\u91d1
	 */
	@Field(6) 
	private CThostFtdcTradingAccountField PreMargin(double PreMargin) {
		this.io.setDoubleField(this, 6, PreMargin);
		return this;
	}

	public void setPreMargin(double preMargin) {
		PreMargin(preMargin);
	}

	/**
	 * \u5229\u606f\u57fa\u6570
	 */
	@Field(7) 
	private double InterestBase() {
		return this.io.getDoubleField(this, 7);
	}

	public double getInterestBase() {
		return InterestBase();
	}

	/**
	 * \u5229\u606f\u57fa\u6570
	 */
	@Field(7) 
	private CThostFtdcTradingAccountField InterestBase(double InterestBase) {
		this.io.setDoubleField(this, 7, InterestBase);
		return this;
	}

	public void setInterestBase(double interestBase) {
		InterestBase(interestBase);
	}

	/**
	 * \u5229\u606f\u6536\u5165
	 */
	@Field(8) 
	private double Interest() {
		return this.io.getDoubleField(this, 8);
	}

	public double getInterest() {
		return Interest();
	}

	/**
	 * \u5229\u606f\u6536\u5165
	 */
	@Field(8) 
	private CThostFtdcTradingAccountField Interest(double Interest) {
		this.io.setDoubleField(this, 8, Interest);
		return this;
	}

	public void setInterest(double interest) {
		Interest(interest);
	}

	/**
	 * \u5165\u91d1\u91d1\u989d
	 */
	@Field(9) 
	private double Deposit() {
		return this.io.getDoubleField(this, 9);
	}

	public double getDeposit() {
		return Deposit();
	}

	/**
	 * \u5165\u91d1\u91d1\u989d
	 */
	@Field(9) 
	private CThostFtdcTradingAccountField Deposit(double Deposit) {
		this.io.setDoubleField(this, 9, Deposit);
		return this;
	}

	public void setDeposit(double deposit) {
		Deposit(deposit);
	}

	/**
	 * \u51fa\u91d1\u91d1\u989d
	 */
	@Field(10) 
	private double Withdraw() {
		return this.io.getDoubleField(this, 10);
	}

	public double getWithdraw() {
		return Withdraw();
	}

	/**
	 * \u51fa\u91d1\u91d1\u989d
	 */
	@Field(10) 
	private CThostFtdcTradingAccountField Withdraw(double Withdraw) {
		this.io.setDoubleField(this, 10, Withdraw);
		return this;
	}

	public void setWithdraw(double withdraw) {
		Withdraw(withdraw);
	}

	/**
	 * \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1
	 */
	@Field(11) 
	private double FrozenMargin() {
		return this.io.getDoubleField(this, 11);
	}

	public double getFrozenMargin() {
		return FrozenMargin();
	}

	/**
	 * \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1
	 */
	@Field(11) 
	private CThostFtdcTradingAccountField FrozenMargin(double FrozenMargin) {
		this.io.setDoubleField(this, 11, FrozenMargin);
		return this;
	}

	public void setFrozenMargin(double frozenMargin) {
		FrozenMargin(frozenMargin);
	}

	/**
	 * \u51bb\u7ed3\u7684\u8d44\u91d1
	 */
	@Field(12) 
	private double FrozenCash() {
		return this.io.getDoubleField(this, 12);
	}

	public double getFrozenCash() {
		return FrozenCash();
	}

	/**
	 * \u51bb\u7ed3\u7684\u8d44\u91d1
	 */
	@Field(12) 
	private CThostFtdcTradingAccountField FrozenCash(double FrozenCash) {
		this.io.setDoubleField(this, 12, FrozenCash);
		return this;
	}

	public void setFrozenCash(double frozenCash) {
		FrozenCash(frozenCash);
	}

	/**
	 * \u51bb\u7ed3\u7684\u624b\u7eed\u8d39
	 */
	@Field(13) 
	private double FrozenCommission() {
		return this.io.getDoubleField(this, 13);
	}

	public double getFrozenCommission() {
		return FrozenCommission();
	}

	/**
	 * \u51bb\u7ed3\u7684\u624b\u7eed\u8d39
	 */
	@Field(13) 
	private CThostFtdcTradingAccountField FrozenCommission(double FrozenCommission) {
		this.io.setDoubleField(this, 13, FrozenCommission);
		return this;
	}

	public void setFrozenCommission(double frozenCommission) {
		FrozenCommission(frozenCommission);
	}

	/**
	 * \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d
	 */
	@Field(14) 
	private double CurrMargin() {
		return this.io.getDoubleField(this, 14);
	}

	public double getCurrMargin() {
		return CurrMargin();
	}

	/**
	 * \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d
	 */
	@Field(14) 
	private CThostFtdcTradingAccountField CurrMargin(double CurrMargin) {
		this.io.setDoubleField(this, 14, CurrMargin);
		return this;
	}

	public void setCurrMargin(double currMargin) {
		CurrMargin(currMargin);
	}

	/**
	 * \u8d44\u91d1\u5dee\u989d
	 */
	@Field(15) 
	private double CashIn() {
		return this.io.getDoubleField(this, 15);
	}

	public double getCashIn() {
		return CashIn();
	}

	/**
	 * \u8d44\u91d1\u5dee\u989d
	 */
	@Field(15) 
	private CThostFtdcTradingAccountField CashIn(double CashIn) {
		this.io.setDoubleField(this, 15, CashIn);
		return this;
	}

	public void setCashIn(double cashIn) {
		CashIn(cashIn);
	}

	/**
	 * \u624b\u7eed\u8d39
	 */
	@Field(16) 
	private double Commission() {
		return this.io.getDoubleField(this, 16);
	}

	public double getCommission() {
		return Commission();
	}

	/**
	 * \u624b\u7eed\u8d39
	 */
	@Field(16) 
	private CThostFtdcTradingAccountField Commission(double Commission) {
		this.io.setDoubleField(this, 16, Commission);
		return this;
	}

	public void setCommission(double commission) {
		Commission(commission);
	}

	/**
	 * \u5e73\u4ed3\u76c8\u4e8f
	 */
	@Field(17) 
	private double CloseProfit() {
		return this.io.getDoubleField(this, 17);
	}

	public double getCloseProfit() {
		return CloseProfit();
	}

	/**
	 * \u5e73\u4ed3\u76c8\u4e8f
	 */
	@Field(17) 
	private CThostFtdcTradingAccountField CloseProfit(double CloseProfit) {
		this.io.setDoubleField(this, 17, CloseProfit);
		return this;
	}

	public void setCloseProfit(double closeProfit) {
		CloseProfit(closeProfit);
	}

	/**
	 * \u6301\u4ed3\u76c8\u4e8f
	 */
	@Field(18) 
	private double PositionProfit() {
		return this.io.getDoubleField(this, 18);
	}

	public double getPositionProfit() {
		return PositionProfit();
	}

	/**
	 * \u6301\u4ed3\u76c8\u4e8f
	 */
	@Field(18) 
	private CThostFtdcTradingAccountField PositionProfit(double PositionProfit) {
		this.io.setDoubleField(this, 18, PositionProfit);
		return this;
	}

	public void setPositionProfit(double positionProfit) {
		PositionProfit(positionProfit);
	}

	/**
	 * \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(19) 
	private double Balance() {
		return this.io.getDoubleField(this, 19);
	}

	public double getBalance() {
		return Balance();
	}

	/**
	 * \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(19) 
	private CThostFtdcTradingAccountField Balance(double Balance) {
		this.io.setDoubleField(this, 19, Balance);
		return this;
	}

	public void setBalance(double balance) {
		Balance(balance);
	}

	/**
	 * \u53ef\u7528\u8d44\u91d1
	 */
	@Field(20) 
	private double Available() {
		return this.io.getDoubleField(this, 20);
	}

	public double getAvailable() {
		return Available();
	}

	/**
	 * \u53ef\u7528\u8d44\u91d1
	 */
	@Field(20) 
	private CThostFtdcTradingAccountField Available(double Available) {
		this.io.setDoubleField(this, 20, Available);
		return this;
	}

	public void setAvailable(double available) {
		Available(available);
	}

	/**
	 * \u53ef\u53d6\u8d44\u91d1
	 */
	@Field(21) 
	private double WithdrawQuota() {
		return this.io.getDoubleField(this, 21);
	}

	public double getWithdrawQuota() {
		return WithdrawQuota();
	}

	/**
	 * \u53ef\u53d6\u8d44\u91d1
	 */
	@Field(21) 
	private CThostFtdcTradingAccountField WithdrawQuota(double WithdrawQuota) {
		this.io.setDoubleField(this, 21, WithdrawQuota);
		return this;
	}

	public void setWithdrawQuota(double withdrawQuota) {
		WithdrawQuota(withdrawQuota);
	}

	/**
	 * \u57fa\u672c\u51c6\u5907\u91d1
	 */
	@Field(22) 
	private double Reserve() {
		return this.io.getDoubleField(this, 22);
	}

	public double getReserve() {
		return Reserve();
	}

	/**
	 * \u57fa\u672c\u51c6\u5907\u91d1
	 */
	@Field(22) 
	private CThostFtdcTradingAccountField Reserve(double Reserve) {
		this.io.setDoubleField(this, 22, Reserve);
		return this;
	}

	public void setReserve(double reserve) {
		Reserve(reserve);
	}

	/**
	 * \u4ea4\u6613\u65e5
	 */
	@Array({9}) 
	@Field(23) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 23);
	}

	@Array({9})
	@Field(23)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 23).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(24) 
	private int SettlementID() {
		return this.io.getIntField(this, 24);
	}

	public int getSettlementID() {
		return SettlementID();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(24) 
	private CThostFtdcTradingAccountField SettlementID(int SettlementID) {
		this.io.setIntField(this, 24, SettlementID);
		return this;
	}

	public void setSettlementID(int settlementID) {
		SettlementID(settlementID);
	}

	/**
	 * \u4fe1\u7528\u989d\u5ea6
	 */
	@Field(25) 
	private double Credit() {
		return this.io.getDoubleField(this, 25);
	}

	public double getCredit() {
		return Credit();
	}

	/**
	 * \u4fe1\u7528\u989d\u5ea6
	 */
	@Field(25) 
	private CThostFtdcTradingAccountField Credit(double Credit) {
		this.io.setDoubleField(this, 25, Credit);
		return this;
	}

	public void setCredit(double credit) {
		Credit(credit);
	}

	/**
	 * \u8d28\u62bc\u91d1\u989d
	 */
	@Field(26) 
	private double Mortgage() {
		return this.io.getDoubleField(this, 26);
	}

	public double getMortgage() {
		return Mortgage();
	}

	/**
	 * \u8d28\u62bc\u91d1\u989d
	 */
	@Field(26) 
	private CThostFtdcTradingAccountField Mortgage(double Mortgage) {
		this.io.setDoubleField(this, 26, Mortgage);
		return this;
	}

	public void setMortgage(double mortgage) {
		Mortgage(mortgage);
	}

	/**
	 * \u4ea4\u6613\u6240\u4fdd\u8bc1\u91d1
	 */
	@Field(27) 
	private double ExchangeMargin() {
		return this.io.getDoubleField(this, 27);
	}

	public double getExchangeMargin() {
		return ExchangeMargin();
	}

	/**
	 * \u4ea4\u6613\u6240\u4fdd\u8bc1\u91d1
	 */
	@Field(27) 
	private CThostFtdcTradingAccountField ExchangeMargin(double ExchangeMargin) {
		this.io.setDoubleField(this, 27, ExchangeMargin);
		return this;
	}

	public void setExchangeMargin(double exchangeMargin) {
		ExchangeMargin(exchangeMargin);
	}

	/**
	 * \u6295\u8d44\u8005\u4ea4\u5272\u4fdd\u8bc1\u91d1
	 */
	@Field(28) 
	private double DeliveryMargin() {
		return this.io.getDoubleField(this, 28);
	}

	public double getDeliveryMargin() {
		return DeliveryMargin();
	}

	/**
	 * \u6295\u8d44\u8005\u4ea4\u5272\u4fdd\u8bc1\u91d1
	 */
	@Field(28) 
	private CThostFtdcTradingAccountField DeliveryMargin(double DeliveryMargin) {
		this.io.setDoubleField(this, 28, DeliveryMargin);
		return this;
	}

	public void setDeliveryMargin(double deliveryMargin) {
		DeliveryMargin(deliveryMargin);
	}

	/**
	 * \u4ea4\u6613\u6240\u4ea4\u5272\u4fdd\u8bc1\u91d1
	 */
	@Field(29) 
	private double ExchangeDeliveryMargin() {
		return this.io.getDoubleField(this, 29);
	}

	public double getExchangeDeliveryMargin() {
		return ExchangeDeliveryMargin();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ea4\u5272\u4fdd\u8bc1\u91d1
	 */
	@Field(29) 
	private CThostFtdcTradingAccountField ExchangeDeliveryMargin(double ExchangeDeliveryMargin) {
		this.io.setDoubleField(this, 29, ExchangeDeliveryMargin);
		return this;
	}

	public void setExchangeDeliveryMargin(double exchangeDeliveryMargin) {
		ExchangeDeliveryMargin(exchangeDeliveryMargin);
	}

	public CThostFtdcTradingAccountField(Pointer pointer) {
		super(pointer);
	}

}

