package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcSyncingInvestorField extends StructObject {
	public CThostFtdcSyncingInvestorField() {
		super();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(0) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({13})
	@Field(0)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 0).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(1) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({11})
	@Field(1)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 1).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u5206\u7ec4\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(2) 
	private Pointer<Byte> InvestorGroupID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({13})
	@Field(2)
	public void setInvestorGroupID(String investorGroupID) {
		this.io.getPointerField(this, 2).setCString(investorGroupID);
	}

	public String getInvestorGroupID() {
		return InvestorGroupID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u540d\u79f0
	 */
	@Array({81}) 
	@Field(3) 
	private Pointer<Byte> InvestorName() {
		return this.io.getPointerField(this, 3);
	}

	@Array({81})
	@Field(3)
	public void setInvestorName(String investorName) {
		this.io.getPointerField(this, 3).setCString(investorName);
	}

	public String getInvestorName() {
		return InvestorName().getCString();
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(4) 
	private byte IdentifiedCardType() {
		return this.io.getByteField(this, 4);
	}

	public char getIdentifiedCardType() {
		return (char)IdentifiedCardType();
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(4) 
	private CThostFtdcSyncingInvestorField IdentifiedCardType(byte IdentifiedCardType) {
		this.io.setByteField(this, 4, IdentifiedCardType);
		return this;
	}

	public void setIdentifiedCardType(char identifiedCardType) {
		IdentifiedCardType((byte)identifiedCardType);
	}

	/**
	 * \u8bc1\u4ef6\u53f7\u7801
	 */
	@Array({51}) 
	@Field(5) 
	private Pointer<Byte> IdentifiedCardNo() {
		return this.io.getPointerField(this, 5);
	}

	@Array({51})
	@Field(5)
	public void setIdentifiedCardNo(String identifiedCardNo) {
		this.io.getPointerField(this, 5).setCString(identifiedCardNo);
	}

	public String getIdentifiedCardNo() {
		return IdentifiedCardNo().getCString();
	}

	/**
	 * \u662f\u5426\u6d3b\u8dc3
	 */
	@Field(6) 
	private int IsActive() {
		return this.io.getIntField(this, 6);
	}

	public int getIsActive() {
		return IsActive();
	}

	/**
	 * \u662f\u5426\u6d3b\u8dc3
	 */
	@Field(6) 
	private CThostFtdcSyncingInvestorField IsActive(int IsActive) {
		this.io.setIntField(this, 6, IsActive);
		return this;
	}

	public void setIsActive(int isActive) {
		IsActive(isActive);
	}

	/**
	 * \u8054\u7cfb\u7535\u8bdd
	 */
	@Array({41}) 
	@Field(7) 
	private Pointer<Byte> Telephone() {
		return this.io.getPointerField(this, 7);
	}

	@Array({41})
	@Field(7)
	public void setTelephone(String telephone) {
		this.io.getPointerField(this, 7).setCString(telephone);
	}

	public String getTelephone() {
		return Telephone().getCString();
	}

	/**
	 * \u901a\u8baf\u5730\u5740
	 */
	@Array({101}) 
	@Field(8) 
	private Pointer<Byte> Address() {
		return this.io.getPointerField(this, 8);
	}

	@Array({101})
	@Field(8)
	public void setAddress(String address) {
		this.io.getPointerField(this, 8).setCString(address);
	}

	public String getAddress() {
		return Address().getCString();
	}

	/**
	 * \u5f00\u6237\u65e5\u671f
	 */
	@Array({9}) 
	@Field(9) 
	private Pointer<Byte> OpenDate() {
		return this.io.getPointerField(this, 9);
	}

	@Array({9})
	@Field(9)
	public void setOpenDate(String openDate) {
		this.io.getPointerField(this, 9).setCString(openDate);
	}

	public String getOpenDate() {
		return OpenDate().getCString();
	}

	/**
	 * \u624b\u673a
	 */
	@Array({41}) 
	@Field(10) 
	private Pointer<Byte> Mobile() {
		return this.io.getPointerField(this, 10);
	}

	@Array({41})
	@Field(10)
	public void setMobile(String mobile) {
		this.io.getPointerField(this, 10).setCString(mobile);
	}

	public String getMobile() {
		return Mobile().getCString();
	}

	/**
	 * \u624b\u7eed\u8d39\u7387\u6a21\u677f\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(11) 
	private Pointer<Byte> CommModelID() {
		return this.io.getPointerField(this, 11);
	}

	@Array({13})
	@Field(11)
	public void setCommModelID(String commModelID) {
		this.io.getPointerField(this, 11).setCString(commModelID);
	}

	public String getCommModelID() {
		return CommModelID().getCString();
	}

	/**
	 * \u4fdd\u8bc1\u91d1\u7387\u6a21\u677f\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(12) 
	private Pointer<Byte> MarginModelID() {
		return this.io.getPointerField(this, 12);
	}

	@Array({13})
	@Field(12)
	public void setMarginModelID(String marginModelID) {
		this.io.getPointerField(this, 12).setCString(marginModelID);
	}

	public String getMarginModelID() {
		return MarginModelID().getCString();
	}

	public CThostFtdcSyncingInvestorField(Pointer pointer) {
		super(pointer);
	}

}

