package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcMarketDataBestPriceField extends StructObject {
	public CThostFtdcMarketDataBestPriceField() {
		super();
	}

	/**
	 * \u7533\u4e70\u4ef7\u4e00
	 */
	@Field(0) 
	private double BidPrice1() {
		return this.io.getDoubleField(this, 0);
	}

	public double getBidPrice1() {
		return BidPrice1();
	}

	/**
	 * \u7533\u4e70\u4ef7\u4e00
	 */
	@Field(0) 
	private CThostFtdcMarketDataBestPriceField BidPrice1(double BidPrice1) {
		this.io.setDoubleField(this, 0, BidPrice1);
		return this;
	}

	public void setBidPrice1(double bidPrice1) {
		BidPrice1(bidPrice1);
	}

	/**
	 * \u7533\u4e70\u91cf\u4e00
	 */
	@Field(1) 
	private int BidVolume1() {
		return this.io.getIntField(this, 1);
	}

	public int getBidVolume1() {
		return BidVolume1();
	}

	/**
	 * \u7533\u4e70\u91cf\u4e00
	 */
	@Field(1) 
	private CThostFtdcMarketDataBestPriceField BidVolume1(int BidVolume1) {
		this.io.setIntField(this, 1, BidVolume1);
		return this;
	}

	public void setBidVolume1(int bidVolume1) {
		BidVolume1(bidVolume1);
	}

	/**
	 * \u7533\u5356\u4ef7\u4e00
	 */
	@Field(2) 
	private double AskPrice1() {
		return this.io.getDoubleField(this, 2);
	}

	public double getAskPrice1() {
		return AskPrice1();
	}

	/**
	 * \u7533\u5356\u4ef7\u4e00
	 */
	@Field(2) 
	private CThostFtdcMarketDataBestPriceField AskPrice1(double AskPrice1) {
		this.io.setDoubleField(this, 2, AskPrice1);
		return this;
	}

	public void setAskPrice1(double askPrice1) {
		AskPrice1(askPrice1);
	}

	/**
	 * \u7533\u5356\u91cf\u4e00
	 */
	@Field(3) 
	private int AskVolume1() {
		return this.io.getIntField(this, 3);
	}

	public int getAskVolume1() {
		return AskVolume1();
	}

	/**
	 * \u7533\u5356\u91cf\u4e00
	 */
	@Field(3) 
	private CThostFtdcMarketDataBestPriceField AskVolume1(int AskVolume1) {
		this.io.setIntField(this, 3, AskVolume1);
		return this;
	}

	public void setAskVolume1(int askVolume1) {
		AskVolume1(askVolume1);
	}

	public CThostFtdcMarketDataBestPriceField(Pointer pointer) {
		super(pointer);
	}

}

