package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcBrokerUserOTPParamField extends StructObject {
	public CThostFtdcBrokerUserOTPParamField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u7528\u6237\u4ee3\u7801
	 */
	@Array({16}) 
	@Field(1) 
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({16})
	@Field(1)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 1).setCString(userID);
	}

	public String getUserID() {
		return UserID().getCString();
	}

	/**
	 * \u52a8\u6001\u4ee4\u724c\u63d0\u4f9b\u5546
	 */
	@Array({2}) 
	@Field(2) 
	private Pointer<Byte> OTPVendorsID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({2})
	@Field(2)
	public void setOTPVendorsID(String oTPVendorsID) {
		this.io.getPointerField(this, 2).setCString(oTPVendorsID);
	}

	public String getOTPVendorsID() {
		return OTPVendorsID().getCString();
	}

	/**
	 * \u52a8\u6001\u4ee4\u724c\u5e8f\u5217\u53f7
	 */
	@Array({17}) 
	@Field(3) 
	private Pointer<Byte> SerialNumber() {
		return this.io.getPointerField(this, 3);
	}

	@Array({17})
	@Field(3)
	public void setSerialNumber(String serialNumber) {
		this.io.getPointerField(this, 3).setCString(serialNumber);
	}

	public String getSerialNumber() {
		return SerialNumber().getCString();
	}

	/**
	 * \u4ee4\u724c\u5bc6\u94a5
	 */
	@Array({41}) 
	@Field(4) 
	private Pointer<Byte> AuthKey() {
		return this.io.getPointerField(this, 4);
	}

	@Array({41})
	@Field(4)
	public void setAuthKey(String authKey) {
		this.io.getPointerField(this, 4).setCString(authKey);
	}

	public String getAuthKey() {
		return AuthKey().getCString();
	}

	/**
	 * \u6f02\u79fb\u503c
	 */
	@Field(5) 
	private int LastDrift() {
		return this.io.getIntField(this, 5);
	}

	public int getLastDrift() {
		return LastDrift();
	}

	/**
	 * \u6f02\u79fb\u503c
	 */
	@Field(5) 
	private CThostFtdcBrokerUserOTPParamField LastDrift(int LastDrift) {
		this.io.setIntField(this, 5, LastDrift);
		return this;
	}

	public void setLastDrift(int lastDrift) {
		LastDrift(lastDrift);
	}

	/**
	 * \u6210\u529f\u503c
	 */
	@Field(6) 
	private int LastSuccess() {
		return this.io.getIntField(this, 6);
	}

	public int getLastSuccess() {
		return LastSuccess();
	}

	/**
	 * \u6210\u529f\u503c
	 */
	@Field(6) 
	private CThostFtdcBrokerUserOTPParamField LastSuccess(int LastSuccess) {
		this.io.setIntField(this, 6, LastSuccess);
		return this;
	}

	public void setLastSuccess(int lastSuccess) {
		LastSuccess(lastSuccess);
	}

	/**
	 * \u52a8\u6001\u4ee4\u724c\u7c7b\u578b
	 */
	@Field(7) 
	private byte OTPType() {
		return this.io.getByteField(this, 7);
	}

	public char getOTPType() {
		return (char)OTPType();
	}

	/**
	 * \u52a8\u6001\u4ee4\u724c\u7c7b\u578b
	 */
	@Field(7) 
	private CThostFtdcBrokerUserOTPParamField OTPType(byte OTPType) {
		this.io.setByteField(this, 7, OTPType);
		return this;
	}

	public void setOTPType(char oTPType) {
		OTPType((byte)oTPType);
	}

	public CThostFtdcBrokerUserOTPParamField(Pointer pointer) {
		super(pointer);
	}

}

