package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcCombinationLegField extends StructObject {
	public CThostFtdcCombinationLegField() {
		super();
	}

	/**
	 * \u7ec4\u5408\u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(0) 
	private Pointer<Byte> CombInstrumentID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({31})
	@Field(0)
	public void setCombInstrumentID(String combInstrumentID) {
		this.io.getPointerField(this, 0).setCString(combInstrumentID);
	}

	public String getCombInstrumentID() {
		return CombInstrumentID().getCString();
	}

	/**
	 * \u5355\u817f\u7f16\u53f7
	 */
	@Field(1) 
	private int LegID() {
		return this.io.getIntField(this, 1);
	}

	public int getLegID() {
		return LegID();
	}

	/**
	 * \u5355\u817f\u7f16\u53f7
	 */
	@Field(1) 
	private CThostFtdcCombinationLegField LegID(int LegID) {
		this.io.setIntField(this, 1, LegID);
		return this;
	}

	public void setLegID(int legID) {
		LegID(legID);
	}

	/**
	 * \u5355\u817f\u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(2) 
	private Pointer<Byte> LegInstrumentID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({31})
	@Field(2)
	public void setLegInstrumentID(String legInstrumentID) {
		this.io.getPointerField(this, 2).setCString(legInstrumentID);
	}

	public String getLegInstrumentID() {
		return LegInstrumentID().getCString();
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(3) 
	private byte Direction() {
		return this.io.getByteField(this, 3);
	}

	public char getDirection() {
		return (char)Direction();
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(3) 
	private CThostFtdcCombinationLegField Direction(byte Direction) {
		this.io.setByteField(this, 3, Direction);
		return this;
	}

	public void setDirection(char direction) {
		Direction((byte)direction);
	}

	/**
	 * \u5355\u817f\u4e58\u6570
	 */
	@Field(4) 
	private int LegMultiple() {
		return this.io.getIntField(this, 4);
	}

	public int getLegMultiple() {
		return LegMultiple();
	}

	/**
	 * \u5355\u817f\u4e58\u6570
	 */
	@Field(4) 
	private CThostFtdcCombinationLegField LegMultiple(int LegMultiple) {
		this.io.setIntField(this, 4, LegMultiple);
		return this;
	}

	public void setLegMultiple(int legMultiple) {
		LegMultiple(legMultiple);
	}

	/**
	 * \u6d3e\u751f\u5c42\u6570
	 */
	@Field(5) 
	private int ImplyLevel() {
		return this.io.getIntField(this, 5);
	}

	public int getImplyLevel() {
		return ImplyLevel();
	}

	/**
	 * \u6d3e\u751f\u5c42\u6570
	 */
	@Field(5) 
	private CThostFtdcCombinationLegField ImplyLevel(int ImplyLevel) {
		this.io.setIntField(this, 5, ImplyLevel);
		return this;
	}

	public void setImplyLevel(int implyLevel) {
		ImplyLevel(implyLevel);
	}

	public CThostFtdcCombinationLegField(Pointer pointer) {
		super(pointer);
	}

}

