package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTraderOfferField extends StructObject {
	public CThostFtdcTraderOfferField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(0) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9})
	@Field(0)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 0).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801
	 */
	@Array({21}) 
	@Field(1) 
	private Pointer<Byte> TraderID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({21})
	@Field(1)
	public void setTraderID(String traderID) {
		this.io.getPointerField(this, 1).setCString(traderID);
	}

	public String getTraderID() {
		return TraderID().getCString();
	}

	/**
	 * \u4f1a\u5458\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(2) 
	private Pointer<Byte> ParticipantID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({11})
	@Field(2)
	public void setParticipantID(String participantID) {
		this.io.getPointerField(this, 2).setCString(participantID);
	}

	public String getParticipantID() {
		return ParticipantID().getCString();
	}

	/**
	 * \u5bc6\u7801
	 */
	@Array({41}) 
	@Field(3) 
	private Pointer<Byte> Password() {
		return this.io.getPointerField(this, 3);
	}

	@Array({41})
	@Field(3)
	public void setPassword(String password) {
		this.io.getPointerField(this, 3).setCString(password);
	}

	public String getPassword() {
		return Password().getCString();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(4) 
	private int InstallID() {
		return this.io.getIntField(this, 4);
	}

	public int getInstallID() {
		return InstallID();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(4) 
	private CThostFtdcTraderOfferField InstallID(int InstallID) {
		this.io.setIntField(this, 4, InstallID);
		return this;
	}

	public void setInstallID(int installID) {
		InstallID(installID);
	}

	/**
	 * \u672c\u5730\u62a5\u5355\u7f16\u53f7
	 */
	@Array({13}) 
	@Field(5) 
	private Pointer<Byte> OrderLocalID() {
		return this.io.getPointerField(this, 5);
	}

	@Array({13})
	@Field(5)
	public void setOrderLocalID(String orderLocalID) {
		this.io.getPointerField(this, 5).setCString(orderLocalID);
	}

	public String getOrderLocalID() {
		return OrderLocalID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u8fde\u63a5\u72b6\u6001
	 */
	@Field(6) 
	private byte TraderConnectStatus() {
		return this.io.getByteField(this, 6);
	}

	public char getTraderConnectStatus() {
		return (char)TraderConnectStatus();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u8fde\u63a5\u72b6\u6001
	 */
	@Field(6) 
	private CThostFtdcTraderOfferField TraderConnectStatus(byte TraderConnectStatus) {
		this.io.setByteField(this, 6, TraderConnectStatus);
		return this;
	}

	public void setTraderConnectStatus(char traderConnectStatus) {
		TraderConnectStatus((byte)traderConnectStatus);
	}

	/**
	 * \u53d1\u51fa\u8fde\u63a5\u8bf7\u6c42\u7684\u65e5\u671f
	 */
	@Array({9}) 
	@Field(7) 
	private Pointer<Byte> ConnectRequestDate() {
		return this.io.getPointerField(this, 7);
	}

	@Array({9})
	@Field(7)
	public void setConnectRequestDate(String connectRequestDate) {
		this.io.getPointerField(this, 7).setCString(connectRequestDate);
	}

	public String getConnectRequestDate() {
		return ConnectRequestDate().getCString();
	}

	/**
	 * \u53d1\u51fa\u8fde\u63a5\u8bf7\u6c42\u7684\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(8) 
	private Pointer<Byte> ConnectRequestTime() {
		return this.io.getPointerField(this, 8);
	}

	@Array({9})
	@Field(8)
	public void setConnectRequestTime(String connectRequestTime) {
		this.io.getPointerField(this, 8).setCString(connectRequestTime);
	}

	public String getConnectRequestTime() {
		return ConnectRequestTime().getCString();
	}

	/**
	 * \u4e0a\u6b21\u62a5\u544a\u65e5\u671f
	 */
	@Array({9}) 
	@Field(9) 
	private Pointer<Byte> LastReportDate() {
		return this.io.getPointerField(this, 9);
	}

	@Array({9})
	@Field(9)
	public void setLastReportDate(String lastReportDate) {
		this.io.getPointerField(this, 9).setCString(lastReportDate);
	}

	public String getLastReportDate() {
		return LastReportDate().getCString();
	}

	/**
	 * \u4e0a\u6b21\u62a5\u544a\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(10) 
	private Pointer<Byte> LastReportTime() {
		return this.io.getPointerField(this, 10);
	}

	@Array({9})
	@Field(10)
	public void setLastReportTime(String lastReportTime) {
		this.io.getPointerField(this, 10).setCString(lastReportTime);
	}

	public String getLastReportTime() {
		return LastReportTime().getCString();
	}

	/**
	 * \u5b8c\u6210\u8fde\u63a5\u65e5\u671f
	 */
	@Array({9}) 
	@Field(11) 
	private Pointer<Byte> ConnectDate() {
		return this.io.getPointerField(this, 11);
	}

	@Array({9})
	@Field(11)
	public void setConnectDate(String connectDate) {
		this.io.getPointerField(this, 11).setCString(connectDate);
	}

	public String getConnectDate() {
		return ConnectDate().getCString();
	}

	/**
	 * \u5b8c\u6210\u8fde\u63a5\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(12) 
	private Pointer<Byte> ConnectTime() {
		return this.io.getPointerField(this, 12);
	}

	@Array({9})
	@Field(12)
	public void setConnectTime(String connectTime) {
		this.io.getPointerField(this, 12).setCString(connectTime);
	}

	public String getConnectTime() {
		return ConnectTime().getCString();
	}

	/**
	 * \u542f\u52a8\u65e5\u671f
	 */
	@Array({9}) 
	@Field(13) 
	private Pointer<Byte> StartDate() {
		return this.io.getPointerField(this, 13);
	}

	@Array({9})
	@Field(13)
	public void setStartDate(String startDate) {
		this.io.getPointerField(this, 13).setCString(startDate);
	}

	public String getStartDate() {
		return StartDate().getCString();
	}

	/**
	 * \u542f\u52a8\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(14) 
	private Pointer<Byte> StartTime() {
		return this.io.getPointerField(this, 14);
	}

	@Array({9})
	@Field(14)
	public void setStartTime(String startTime) {
		this.io.getPointerField(this, 14).setCString(startTime);
	}

	public String getStartTime() {
		return StartTime().getCString();
	}

	/**
	 * \u4ea4\u6613\u65e5
	 */
	@Array({9}) 
	@Field(15) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 15);
	}

	@Array({9})
	@Field(15)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 15).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(16) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 16);
	}

	@Array({11})
	@Field(16)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 16).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u672c\u5e2d\u4f4d\u6700\u5927\u6210\u4ea4\u7f16\u53f7
	 */
	@Array({21}) 
	@Field(17) 
	private Pointer<Byte> MaxTradeID() {
		return this.io.getPointerField(this, 17);
	}

	@Array({21})
	@Field(17)
	public void setMaxTradeID(String maxTradeID) {
		this.io.getPointerField(this, 17).setCString(maxTradeID);
	}

	public String getMaxTradeID() {
		return MaxTradeID().getCString();
	}

	/**
	 * \u672c\u5e2d\u4f4d\u6700\u5927\u62a5\u5355\u5907\u62f7
	 */
	@Array({7}) 
	@Field(18) 
	private Pointer<Byte> MaxOrderMessageReference() {
		return this.io.getPointerField(this, 18);
	}

	@Array({7})
	@Field(18)
	public void setMaxOrderMessageReference(String maxOrderMessageReference) {
		this.io.getPointerField(this, 18).setCString(maxOrderMessageReference);
	}

	public String getMaxOrderMessageReference() {
		return MaxOrderMessageReference().getCString();
	}

	public CThostFtdcTraderOfferField(Pointer pointer) {
		super(pointer);
	}

}

