package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTransferQryDetailReqField extends StructObject {
	public CThostFtdcTransferQryDetailReqField() {
		super();
	}

	/**
	 * \u671f\u8d27\u8d44\u91d1\u8d26\u6237
	 */
	@Array({13}) 
	@Field(0) 
	private Pointer<Byte> FutureAccount() {
		return this.io.getPointerField(this, 0);
	}

	@Array({13})
	@Field(0)
	public void setFutureAccount(String futureAccount) {
		this.io.getPointerField(this, 0).setCString(futureAccount);
	}

	public String getFutureAccount() {
		return FutureAccount().getCString();
	}

	public CThostFtdcTransferQryDetailReqField(Pointer pointer) {
		super(pointer);
	}

}

