package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcBrokerUserField extends StructObject {
	public CThostFtdcBrokerUserField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u7528\u6237\u4ee3\u7801
	 */
	@Array({16}) 
	@Field(1) 
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({16})
	@Field(1)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 1).setCString(userID);
	}

	public String getUserID() {
		return UserID().getCString();
	}

	/**
	 * \u7528\u6237\u540d\u79f0
	 */
	@Array({81}) 
	@Field(2) 
	private Pointer<Byte> UserName() {
		return this.io.getPointerField(this, 2);
	}

	@Array({81})
	@Field(2)
	public void setUserName(String userName) {
		this.io.getPointerField(this, 2).setCString(userName);
	}

	public String getUserName() {
		return UserName().getCString();
	}

	/**
	 * \u7528\u6237\u7c7b\u578b
	 */
	@Field(3) 
	private byte UserType() {
		return this.io.getByteField(this, 3);
	}

	public char getUserType() {
		return (char)UserType();
	}

	/**
	 * \u7528\u6237\u7c7b\u578b
	 */
	@Field(3) 
	private CThostFtdcBrokerUserField UserType(byte UserType) {
		this.io.setByteField(this, 3, UserType);
		return this;
	}

	public void setUserType(char userType) {
		UserType((byte)userType);
	}

	/**
	 * \u662f\u5426\u6d3b\u8dc3
	 */
	@Field(4) 
	private int IsActive() {
		return this.io.getIntField(this, 4);
	}

	public int getIsActive() {
		return IsActive();
	}

	/**
	 * \u662f\u5426\u6d3b\u8dc3
	 */
	@Field(4) 
	private CThostFtdcBrokerUserField IsActive(int IsActive) {
		this.io.setIntField(this, 4, IsActive);
		return this;
	}

	public void setIsActive(int isActive) {
		IsActive(isActive);
	}

	/**
	 * \u662f\u5426\u4f7f\u7528\u4ee4\u724c
	 */
	@Field(5) 
	private int IsUsingOTP() {
		return this.io.getIntField(this, 5);
	}

	public int getIsUsingOTP() {
		return IsUsingOTP();
	}

	/**
	 * \u662f\u5426\u4f7f\u7528\u4ee4\u724c
	 */
	@Field(5) 
	private CThostFtdcBrokerUserField IsUsingOTP(int IsUsingOTP) {
		this.io.setIntField(this, 5, IsUsingOTP);
		return this;
	}

	public void setIsUsingOTP(int isUsingOTP) {
		IsUsingOTP(isUsingOTP);
	}

	public CThostFtdcBrokerUserField(Pointer pointer) {
		super(pointer);
	}

}

