package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcSettlementInfoField extends StructObject {
	public CThostFtdcSettlementInfoField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u65e5
	 */
	@Array({9}) 
	@Field(0) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9})
	@Field(0)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 0).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(1) 
	private int SettlementID() {
		return this.io.getIntField(this, 1);
	}

	public int getSettlementID() {
		return SettlementID();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(1) 
	private CThostFtdcSettlementInfoField SettlementID(int SettlementID) {
		this.io.setIntField(this, 1, SettlementID);
		return this;
	}

	public void setSettlementID(int settlementID) {
		SettlementID(settlementID);
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(2) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({11})
	@Field(2)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 2).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(3) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 3);
	}

	@Array({13})
	@Field(3)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 3).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(4) 
	private int SequenceNo() {
		return this.io.getIntField(this, 4);
	}

	public int getSequenceNo() {
		return SequenceNo();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(4) 
	private CThostFtdcSettlementInfoField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 4, SequenceNo);
		return this;
	}

	public void setSequenceNo(int sequenceNo) {
		SequenceNo(sequenceNo);
	}

	/**
	 * \u6d88\u606f\u6b63\u6587
	 */
	@Array({501}) 
	@Field(5) 
	private Pointer<Byte> Content() {
		return this.io.getPointerField(this, 5);
	}

	@Array({501})
	@Field(5)
	public void setContent(String content) {
		this.io.getPointerField(this, 5).setCString(content);
	}

	public String getContent() {
		return Content().getCString();
	}

	public CThostFtdcSettlementInfoField(Pointer pointer) {
		super(pointer);
	}

}

