package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcMarketDataBaseField extends StructObject {
	public CThostFtdcMarketDataBaseField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u65e5
	 */
	@Array({9}) 
	@Field(0) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9})
	@Field(0)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 0).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u4ef7
	 */
	@Field(1) 
	private double PreSettlementPrice() {
		return this.io.getDoubleField(this, 1);
	}

	public double getPreSettlementPrice() {
		return PreSettlementPrice();
	}

	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u4ef7
	 */
	@Field(1) 
	private CThostFtdcMarketDataBaseField PreSettlementPrice(double PreSettlementPrice) {
		this.io.setDoubleField(this, 1, PreSettlementPrice);
		return this;
	}

	public void setPreSettlementPrice(double preSettlementPrice) {
		PreSettlementPrice(preSettlementPrice);
	}

	/**
	 * \u6628\u6536\u76d8
	 */
	@Field(2) 
	private double PreClosePrice() {
		return this.io.getDoubleField(this, 2);
	}

	public double getPreClosePrice() {
		return PreClosePrice();
	}

	/**
	 * \u6628\u6536\u76d8
	 */
	@Field(2) 
	private CThostFtdcMarketDataBaseField PreClosePrice(double PreClosePrice) {
		this.io.setDoubleField(this, 2, PreClosePrice);
		return this;
	}

	public void setPreClosePrice(double preClosePrice) {
		PreClosePrice(preClosePrice);
	}

	/**
	 * \u6628\u6301\u4ed3\u91cf
	 */
	@Field(3) 
	private double PreOpenInterest() {
		return this.io.getDoubleField(this, 3);
	}

	public double getPreOpenInterest() {
		return PreOpenInterest();
	}

	/**
	 * \u6628\u6301\u4ed3\u91cf
	 */
	@Field(3) 
	private CThostFtdcMarketDataBaseField PreOpenInterest(double PreOpenInterest) {
		this.io.setDoubleField(this, 3, PreOpenInterest);
		return this;
	}

	public void setPreOpenInterest(double preOpenInterest) {
		PreOpenInterest(preOpenInterest);
	}

	/**
	 * \u6628\u865a\u5b9e\u5ea6
	 */
	@Field(4) 
	private double PreDelta() {
		return this.io.getDoubleField(this, 4);
	}

	public double getPreDelta() {
		return PreDelta();
	}

	/**
	 * \u6628\u865a\u5b9e\u5ea6
	 */
	@Field(4) 
	private CThostFtdcMarketDataBaseField PreDelta(double PreDelta) {
		this.io.setDoubleField(this, 4, PreDelta);
		return this;
	}

	public void setPreDelta(double preDelta) {
		PreDelta(preDelta);
	}

	public CThostFtdcMarketDataBaseField(Pointer pointer) {
		super(pointer);
	}

}

