package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcQryFrontStatusField extends StructObject {
	public CThostFtdcQryFrontStatusField() {
		super();
	}

	/**
	 * \u524d\u7f6e\u7f16\u53f7
	 */
	@Field(0) 
	private int FrontID() {
		return this.io.getIntField(this, 0);
	}

	public int getFrontID() {
		return FrontID();
	}

	/**
	 * \u524d\u7f6e\u7f16\u53f7
	 */
	@Field(0) 
	private CThostFtdcQryFrontStatusField FrontID(int FrontID) {
		this.io.setIntField(this, 0, FrontID);
		return this;
	}

	public void setFrontID(int frontID) {
		FrontID(frontID);
	}

	public CThostFtdcQryFrontStatusField(Pointer pointer) {
		super(pointer);
	}

}

