package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcQryTransferBankField extends StructObject {
	public CThostFtdcQryTransferBankField() {
		super();
	}

	/**
	 * \u94f6\u884c\u4ee3\u7801
	 */
	@Array({4}) 
	@Field(0) 
	private Pointer<Byte> BankID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({4})
	@Field(0)
	public void setBankID(String bankID) {
		this.io.getPointerField(this, 0).setCString(bankID);
	}

	public String getBankID() {
		return BankID().getCString();
	}

	/**
	 * \u94f6\u884c\u5206\u4e2d\u5fc3\u4ee3\u7801
	 */
	@Array({5}) 
	@Field(1) 
	private Pointer<Byte> BankBrchID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({5})
	@Field(1)
	public void setBankBrchID(String bankBrchID) {
		this.io.getPointerField(this, 1).setCString(bankBrchID);
	}

	public String getBankBrchID() {
		return BankBrchID().getCString();
	}

	public CThostFtdcQryTransferBankField(Pointer pointer) {
		super(pointer);
	}

}

