package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcQueryMaxOrderVolumeField extends StructObject {
	public CThostFtdcQueryMaxOrderVolumeField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(1) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({13})
	@Field(1)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 1).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(2) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({31})
	@Field(2)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 2).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(3) 
	private byte Direction() {
		return this.io.getByteField(this, 3);
	}

	public char getDirection() {
		return (char)Direction();
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(3) 
	private CThostFtdcQueryMaxOrderVolumeField Direction(byte Direction) {
		this.io.setByteField(this, 3, Direction);
		return this;
	}

	public void setDirection(char direction) {
		Direction((byte)direction);
	}

	/**
	 * \u5f00\u5e73\u6807\u5fd7
	 */
	@Field(4) 
	private byte OffsetFlag() {
		return this.io.getByteField(this, 4);
	}

	public char getOffsetFlag() {
		return (char)OffsetFlag();
	}

	/**
	 * \u5f00\u5e73\u6807\u5fd7
	 */
	@Field(4) 
	private CThostFtdcQueryMaxOrderVolumeField OffsetFlag(byte OffsetFlag) {
		this.io.setByteField(this, 4, OffsetFlag);
		return this;
	}

	public void setOffsetFlag(char offsetFlag) {
		OffsetFlag((byte)offsetFlag);
	}

	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Field(5) 
	private byte HedgeFlag() {
		return this.io.getByteField(this, 5);
	}

	public char getHedgeFlag() {
		return (char)HedgeFlag();
	}

	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Field(5) 
	private CThostFtdcQueryMaxOrderVolumeField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 5, HedgeFlag);
		return this;
	}

	public void setHedgeFlag(char hedgeFlag) {
		HedgeFlag((byte)hedgeFlag);
	}

	/**
	 * \u6700\u5927\u5141\u8bb8\u62a5\u5355\u6570\u91cf
	 */
	@Field(6) 
	private int MaxVolume() {
		return this.io.getIntField(this, 6);
	}

	public int getMaxVolume() {
		return MaxVolume();
	}

	/**
	 * \u6700\u5927\u5141\u8bb8\u62a5\u5355\u6570\u91cf
	 */
	@Field(6) 
	private CThostFtdcQueryMaxOrderVolumeField MaxVolume(int MaxVolume) {
		this.io.setIntField(this, 6, MaxVolume);
		return this;
	}

	public void setMaxVolume(int maxVolume) {
		MaxVolume(maxVolume);
	}

	public CThostFtdcQueryMaxOrderVolumeField(Pointer pointer) {
		super(pointer);
	}

}

