package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTransferBankToFutureRspField extends StructObject {
	public CThostFtdcTransferBankToFutureRspField() {
		super();
	}

	/**
	 * \u54cd\u5e94\u4ee3\u7801
	 */
	@Array({5}) 
	@Field(0) 
	private Pointer<Byte> RetCode() {
		return this.io.getPointerField(this, 0);
	}

	@Array({5})
	@Field(0)
	public void setRetCode(String retCode) {
		this.io.getPointerField(this, 0).setCString(retCode);
	}

	public String getRetCode() {
		return RetCode().getCString();
	}

	/**
	 * \u54cd\u5e94\u4fe1\u606f
	 */
	@Array({129}) 
	@Field(1) 
	private Pointer<Byte> RetInfo() {
		return this.io.getPointerField(this, 1);
	}

	@Array({129})
	@Field(1)
	public void setRetInfo(String retInfo) {
		this.io.getPointerField(this, 1).setCString(retInfo);
	}

	public String getRetInfo() {
		return RetInfo().getCString();
	}

	/**
	 * \u8d44\u91d1\u8d26\u6237
	 */
	@Array({13}) 
	@Field(2) 
	private Pointer<Byte> FutureAccount() {
		return this.io.getPointerField(this, 2);
	}

	@Array({13})
	@Field(2)
	public void setFutureAccount(String futureAccount) {
		this.io.getPointerField(this, 2).setCString(futureAccount);
	}

	public String getFutureAccount() {
		return FutureAccount().getCString();
	}

	/**
	 * \u8f6c\u5e10\u91d1\u989d
	 */
	@Field(3) 
	private double TradeAmt() {
		return this.io.getDoubleField(this, 3);
	}

	public double getTradeAmt() {
		return TradeAmt();
	}

	/**
	 * \u8f6c\u5e10\u91d1\u989d
	 */
	@Field(3) 
	private CThostFtdcTransferBankToFutureRspField TradeAmt(double TradeAmt) {
		this.io.setDoubleField(this, 3, TradeAmt);
		return this;
	}

	public void setTradeAmt(double tradeAmt) {
		TradeAmt(tradeAmt);
	}

	/**
	 * \u5e94\u6536\u5ba2\u6237\u624b\u7eed\u8d39
	 */
	@Field(4) 
	private double CustFee() {
		return this.io.getDoubleField(this, 4);
	}

	public double getCustFee() {
		return CustFee();
	}

	/**
	 * \u5e94\u6536\u5ba2\u6237\u624b\u7eed\u8d39
	 */
	@Field(4) 
	private CThostFtdcTransferBankToFutureRspField CustFee(double CustFee) {
		this.io.setDoubleField(this, 4, CustFee);
		return this;
	}

	public void setCustFee(double custFee) {
		CustFee(custFee);
	}

	/**
	 * \u5e01\u79cd
	 */
	@Array({4}) 
	@Field(5) 
	private Pointer<Byte> CurrencyCode() {
		return this.io.getPointerField(this, 5);
	}

	@Array({4})
	@Field(5)
	public void setCurrencyCode(String currencyCode) {
		this.io.getPointerField(this, 5).setCString(currencyCode);
	}

	public String getCurrencyCode() {
		return CurrencyCode().getCString();
	}

	public CThostFtdcTransferBankToFutureRspField(Pointer pointer) {
		super(pointer);
	}

}

