package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcLinkManField extends StructObject {
	public CThostFtdcLinkManField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(1) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({13})
	@Field(1)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 1).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u8054\u7cfb\u4eba\u7c7b\u578b
	 */
	@Field(2) 
	private byte PersonType() {
		return this.io.getByteField(this, 2);
	}

	public char getPersonType() {
		return (char)PersonType();
	}

	/**
	 * \u8054\u7cfb\u4eba\u7c7b\u578b
	 */
	@Field(2) 
	private CThostFtdcLinkManField PersonType(byte PersonType) {
		this.io.setByteField(this, 2, PersonType);
		return this;
	}

	public void setPersonType(char personType) {
		PersonType((byte)personType);
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(3) 
	private byte IdentifiedCardType() {
		return this.io.getByteField(this, 3);
	}

	public char getIdentifiedCardType() {
		return (char)IdentifiedCardType();
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(3) 
	private CThostFtdcLinkManField IdentifiedCardType(byte IdentifiedCardType) {
		this.io.setByteField(this, 3, IdentifiedCardType);
		return this;
	}

	public void setIdentifiedCardType(char identifiedCardType) {
		IdentifiedCardType((byte)identifiedCardType);
	}

	/**
	 * \u8bc1\u4ef6\u53f7\u7801
	 */
	@Array({51}) 
	@Field(4) 
	private Pointer<Byte> IdentifiedCardNo() {
		return this.io.getPointerField(this, 4);
	}

	@Array({51})
	@Field(4)
	public void setIdentifiedCardNo(String identifiedCardNo) {
		this.io.getPointerField(this, 4).setCString(identifiedCardNo);
	}

	public String getIdentifiedCardNo() {
		return IdentifiedCardNo().getCString();
	}

	/**
	 * \u540d\u79f0
	 */
	@Array({81}) 
	@Field(5) 
	private Pointer<Byte> PersonName() {
		return this.io.getPointerField(this, 5);
	}

	@Array({81})
	@Field(5)
	public void setPersonName(String personName) {
		this.io.getPointerField(this, 5).setCString(personName);
	}

	public String getPersonName() {
		return PersonName().getCString();
	}

	/**
	 * \u8054\u7cfb\u7535\u8bdd
	 */
	@Array({41}) 
	@Field(6) 
	private Pointer<Byte> Telephone() {
		return this.io.getPointerField(this, 6);
	}

	@Array({41})
	@Field(6)
	public void setTelephone(String telephone) {
		this.io.getPointerField(this, 6).setCString(telephone);
	}

	public String getTelephone() {
		return Telephone().getCString();
	}

	/**
	 * \u901a\u8baf\u5730\u5740
	 */
	@Array({101}) 
	@Field(7) 
	private Pointer<Byte> Address() {
		return this.io.getPointerField(this, 7);
	}

	@Array({101})
	@Field(7)
	public void setAddress(String address) {
		this.io.getPointerField(this, 7).setCString(address);
	}

	public String getAddress() {
		return Address().getCString();
	}

	/**
	 * \u90ae\u653f\u7f16\u7801
	 */
	@Array({7}) 
	@Field(8) 
	private Pointer<Byte> ZipCode() {
		return this.io.getPointerField(this, 8);
	}

	@Array({7})
	@Field(8)
	public void setZipCode(String zipCode) {
		this.io.getPointerField(this, 8).setCString(zipCode);
	}

	public String getZipCode() {
		return ZipCode().getCString();
	}

	/**
	 * \u4f18\u5148\u7ea7
	 */
	@Field(9) 
	private int Priority() {
		return this.io.getIntField(this, 9);
	}

	public int getPriority() {
		return Priority();
	}

	/**
	 * \u4f18\u5148\u7ea7
	 */
	@Field(9) 
	private CThostFtdcLinkManField Priority(int Priority) {
		this.io.setIntField(this, 9, Priority);
		return this;
	}

	public void setPriority(int priority) {
		Priority(priority);
	}

	public CThostFtdcLinkManField(Pointer pointer) {
		super(pointer);
	}

}

