package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcExchangeMarginRateField extends StructObject {
	public CThostFtdcExchangeMarginRateField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(1) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({31})
	@Field(1)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 1).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Field(2) 
	private byte HedgeFlag() {
		return this.io.getByteField(this, 2);
	}

	public char getHedgeFlag() {
		return (char)HedgeFlag();
	}

	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Field(2) 
	private CThostFtdcExchangeMarginRateField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 2, HedgeFlag);
		return this;
	}

	public void setHedgeFlag(char hedgeFlag) {
		HedgeFlag((byte)hedgeFlag);
	}

	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(3) 
	private double LongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 3);
	}

	public double getLongMarginRatioByMoney() {
		return LongMarginRatioByMoney();
	}

	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(3) 
	private CThostFtdcExchangeMarginRateField LongMarginRatioByMoney(double LongMarginRatioByMoney) {
		this.io.setDoubleField(this, 3, LongMarginRatioByMoney);
		return this;
	}

	public void setLongMarginRatioByMoney(double longMarginRatioByMoney) {
		LongMarginRatioByMoney(longMarginRatioByMoney);
	}

	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(4) 
	private double LongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 4);
	}

	public double getLongMarginRatioByVolume() {
		return LongMarginRatioByVolume();
	}

	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(4) 
	private CThostFtdcExchangeMarginRateField LongMarginRatioByVolume(double LongMarginRatioByVolume) {
		this.io.setDoubleField(this, 4, LongMarginRatioByVolume);
		return this;
	}

	public void setLongMarginRatioByVolume(double longMarginRatioByVolume) {
		LongMarginRatioByVolume(longMarginRatioByVolume);
	}

	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(5) 
	private double ShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 5);
	}

	public double getShortMarginRatioByMoney() {
		return ShortMarginRatioByMoney();
	}

	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	 */
	@Field(5) 
	private CThostFtdcExchangeMarginRateField ShortMarginRatioByMoney(double ShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 5, ShortMarginRatioByMoney);
		return this;
	}

	public void setShortMarginRatioByMoney(double shortMarginRatioByMoney) {
		ShortMarginRatioByMoney(shortMarginRatioByMoney);
	}

	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(6) 
	private double ShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 6);
	}

	public double getShortMarginRatioByVolume() {
		return ShortMarginRatioByVolume();
	}

	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	 */
	@Field(6) 
	private CThostFtdcExchangeMarginRateField ShortMarginRatioByVolume(double ShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 6, ShortMarginRatioByVolume);
		return this;
	}

	public void setShortMarginRatioByVolume(double shortMarginRatioByVolume) {
		ShortMarginRatioByVolume(shortMarginRatioByVolume);
	}

	public CThostFtdcExchangeMarginRateField(Pointer pointer) {
		super(pointer);
	}

}

