package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcQryOrderField extends StructObject {
	public CThostFtdcQryOrderField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(1) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({13})
	@Field(1)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 1).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(2) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({31})
	@Field(2)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 2).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(3) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 3);
	}

	@Array({9})
	@Field(3)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 3).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u62a5\u5355\u7f16\u53f7
	 */
	@Array({21}) 
	@Field(4) 
	private Pointer<Byte> OrderSysID() {
		return this.io.getPointerField(this, 4);
	}

	@Array({21})
	@Field(4)
	public void setOrderSysID(String orderSysID) {
		this.io.getPointerField(this, 4).setCString(orderSysID);
	}

	public String getOrderSysID() {
		return OrderSysID().getCString();
	}

	/**
	 * \u5f00\u59cb\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(5) 
	private Pointer<Byte> InsertTimeStart() {
		return this.io.getPointerField(this, 5);
	}

	@Array({9})
	@Field(5)
	public void setInsertTimeStart(String insertTimeStart) {
		this.io.getPointerField(this, 5).setCString(insertTimeStart);
	}

	public String getInsertTimeStart() {
		return InsertTimeStart().getCString();
	}

	/**
	 * \u7ed3\u675f\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(6) 
	private Pointer<Byte> InsertTimeEnd() {
		return this.io.getPointerField(this, 6);
	}

	@Array({9})
	@Field(6)
	public void setInsertTimeEnd(String insertTimeEnd) {
		this.io.getPointerField(this, 6).setCString(insertTimeEnd);
	}

	public String getInsertTimeEnd() {
		return InsertTimeEnd().getCString();
	}

	public CThostFtdcQryOrderField(Pointer pointer) {
		super(pointer);
	}

}

