package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcSuperUserField extends StructObject {
	public CThostFtdcSuperUserField() {
		super();
	}

	/**
	 * \u7528\u6237\u4ee3\u7801
	 */
	@Array({16}) 
	@Field(0) 
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({16})
	@Field(0)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 0).setCString(userID);
	}

	public String getUserID() {
		return UserID().getCString();
	}

	/**
	 * \u7528\u6237\u540d\u79f0
	 */
	@Array({81}) 
	@Field(1) 
	private Pointer<Byte> UserName() {
		return this.io.getPointerField(this, 1);
	}

	@Array({81})
	@Field(1)
	public void setUserName(String userName) {
		this.io.getPointerField(this, 1).setCString(userName);
	}

	public String getUserName() {
		return UserName().getCString();
	}

	/**
	 * \u5bc6\u7801
	 */
	@Array({41}) 
	@Field(2) 
	private Pointer<Byte> Password() {
		return this.io.getPointerField(this, 2);
	}

	@Array({41})
	@Field(2)
	public void setPassword(String password) {
		this.io.getPointerField(this, 2).setCString(password);
	}

	public String getPassword() {
		return Password().getCString();
	}

	/**
	 * \u662f\u5426\u6d3b\u8dc3
	 */
	@Field(3) 
	private int IsActive() {
		return this.io.getIntField(this, 3);
	}

	public int getIsActive() {
		return IsActive();
	}

	/**
	 * \u662f\u5426\u6d3b\u8dc3
	 */
	@Field(3) 
	private CThostFtdcSuperUserField IsActive(int IsActive) {
		this.io.setIntField(this, 3, IsActive);
		return this;
	}

	public void setIsActive(int isActive) {
		IsActive(isActive);
	}

	public CThostFtdcSuperUserField(Pointer pointer) {
		super(pointer);
	}

}

