package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcErrorConditionalOrderField extends StructObject {
	public CThostFtdcErrorConditionalOrderField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(1) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({13})
	@Field(1)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 1).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(2) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({31})
	@Field(2)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 2).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u62a5\u5355\u5f15\u7528
	 */
	@Array({13}) 
	@Field(3) 
	private Pointer<Byte> OrderRef() {
		return this.io.getPointerField(this, 3);
	}

	@Array({13})
	@Field(3)
	public void setOrderRef(String orderRef) {
		this.io.getPointerField(this, 3).setCString(orderRef);
	}

	public String getOrderRef() {
		return OrderRef().getCString();
	}

	/**
	 * \u7528\u6237\u4ee3\u7801
	 */
	@Array({16}) 
	@Field(4) 
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 4);
	}

	@Array({16})
	@Field(4)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 4).setCString(userID);
	}

	public String getUserID() {
		return UserID().getCString();
	}

	/**
	 * \u62a5\u5355\u4ef7\u683c\u6761\u4ef6
	 */
	@Field(5) 
	private byte OrderPriceType() {
		return this.io.getByteField(this, 5);
	}

	public char getOrderPriceType() {
		return (char)OrderPriceType();
	}

	/**
	 * \u62a5\u5355\u4ef7\u683c\u6761\u4ef6
	 */
	@Field(5) 
	private CThostFtdcErrorConditionalOrderField OrderPriceType(byte OrderPriceType) {
		this.io.setByteField(this, 5, OrderPriceType);
		return this;
	}

	public void setOrderPriceType(char orderPriceType) {
		OrderPriceType((byte)orderPriceType);
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(6) 
	private byte Direction() {
		return this.io.getByteField(this, 6);
	}

	public char getDirection() {
		return (char)Direction();
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(6) 
	private CThostFtdcErrorConditionalOrderField Direction(byte Direction) {
		this.io.setByteField(this, 6, Direction);
		return this;
	}

	public void setDirection(char direction) {
		Direction((byte)direction);
	}

	/**
	 * \u7ec4\u5408\u5f00\u5e73\u6807\u5fd7
	 */
	@Array({5}) 
	@Field(7) 
	private Pointer<Byte> CombOffsetFlag() {
		return this.io.getPointerField(this, 7);
	}

	@Array({5})
	@Field(7)
	public void setCombOffsetFlag(String combOffsetFlag) {
		this.io.getPointerField(this, 7).setCString(combOffsetFlag);
	}

	public String getCombOffsetFlag() {
		return CombOffsetFlag().getCString();
	}

	/**
	 * \u7ec4\u5408\u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Array({5}) 
	@Field(8) 
	private Pointer<Byte> CombHedgeFlag() {
		return this.io.getPointerField(this, 8);
	}

	@Array({5})
	@Field(8)
	public void setCombHedgeFlag(String combHedgeFlag) {
		this.io.getPointerField(this, 8).setCString(combHedgeFlag);
	}

	public String getCombHedgeFlag() {
		return CombHedgeFlag().getCString();
	}

	/**
	 * \u4ef7\u683c
	 */
	@Field(9) 
	private double LimitPrice() {
		return this.io.getDoubleField(this, 9);
	}

	public double getLimitPrice() {
		return LimitPrice();
	}

	/**
	 * \u4ef7\u683c
	 */
	@Field(9) 
	private CThostFtdcErrorConditionalOrderField LimitPrice(double LimitPrice) {
		this.io.setDoubleField(this, 9, LimitPrice);
		return this;
	}

	public void setLimitPrice(double limitPrice) {
		LimitPrice(limitPrice);
	}

	/**
	 * \u6570\u91cf
	 */
	@Field(10) 
	private int VolumeTotalOriginal() {
		return this.io.getIntField(this, 10);
	}

	public int getVolumeTotalOriginal() {
		return VolumeTotalOriginal();
	}

	/**
	 * \u6570\u91cf
	 */
	@Field(10) 
	private CThostFtdcErrorConditionalOrderField VolumeTotalOriginal(int VolumeTotalOriginal) {
		this.io.setIntField(this, 10, VolumeTotalOriginal);
		return this;
	}

	public void setVolumeTotalOriginal(int volumeTotalOriginal) {
		VolumeTotalOriginal(volumeTotalOriginal);
	}

	/**
	 * \u6709\u6548\u671f\u7c7b\u578b
	 */
	@Field(11) 
	private byte TimeCondition() {
		return this.io.getByteField(this, 11);
	}

	public char getTimeCondition() {
		return (char)TimeCondition();
	}

	/**
	 * \u6709\u6548\u671f\u7c7b\u578b
	 */
	@Field(11) 
	private CThostFtdcErrorConditionalOrderField TimeCondition(byte TimeCondition) {
		this.io.setByteField(this, 11, TimeCondition);
		return this;
	}

	public void setTimeCondition(char timeCondition) {
		TimeCondition((byte)timeCondition);
	}

	/// GTD\u65e5\u671f
	@Array({9}) 
	@Field(12) 
	private Pointer<Byte> GTDDate() {
		return this.io.getPointerField(this, 12);
	}

	@Array({9})
	@Field(12)
	public void setGTDDate(String gTDDate) {
		this.io.getPointerField(this, 12).setCString(gTDDate);
	}

	public String getGTDDate() {
		return GTDDate().getCString();
	}

	/**
	 * \u6210\u4ea4\u91cf\u7c7b\u578b
	 */
	@Field(13) 
	private byte VolumeCondition() {
		return this.io.getByteField(this, 13);
	}

	public char getVolumeCondition() {
		return (char)VolumeCondition();
	}

	/**
	 * \u6210\u4ea4\u91cf\u7c7b\u578b
	 */
	@Field(13) 
	private CThostFtdcErrorConditionalOrderField VolumeCondition(byte VolumeCondition) {
		this.io.setByteField(this, 13, VolumeCondition);
		return this;
	}

	public void setVolumeCondition(char volumeCondition) {
		VolumeCondition((byte)volumeCondition);
	}

	/**
	 * \u6700\u5c0f\u6210\u4ea4\u91cf
	 */
	@Field(14) 
	private int MinVolume() {
		return this.io.getIntField(this, 14);
	}

	public int getMinVolume() {
		return MinVolume();
	}

	/**
	 * \u6700\u5c0f\u6210\u4ea4\u91cf
	 */
	@Field(14) 
	private CThostFtdcErrorConditionalOrderField MinVolume(int MinVolume) {
		this.io.setIntField(this, 14, MinVolume);
		return this;
	}

	public void setMinVolume(int minVolume) {
		MinVolume(minVolume);
	}

	/**
	 * \u89e6\u53d1\u6761\u4ef6
	 */
	@Field(15) 
	private byte ContingentCondition() {
		return this.io.getByteField(this, 15);
	}

	public char getContingentCondition() {
		return (char)ContingentCondition();
	}

	/**
	 * \u89e6\u53d1\u6761\u4ef6
	 */
	@Field(15) 
	private CThostFtdcErrorConditionalOrderField ContingentCondition(byte ContingentCondition) {
		this.io.setByteField(this, 15, ContingentCondition);
		return this;
	}

	public void setContingentCondition(char contingentCondition) {
		ContingentCondition((byte)contingentCondition);
	}

	/**
	 * \u6b62\u635f\u4ef7
	 */
	@Field(16) 
	private double StopPrice() {
		return this.io.getDoubleField(this, 16);
	}

	public double getStopPrice() {
		return StopPrice();
	}

	/**
	 * \u6b62\u635f\u4ef7
	 */
	@Field(16) 
	private CThostFtdcErrorConditionalOrderField StopPrice(double StopPrice) {
		this.io.setDoubleField(this, 16, StopPrice);
		return this;
	}

	public void setStopPrice(double stopPrice) {
		StopPrice(stopPrice);
	}

	/**
	 * \u5f3a\u5e73\u539f\u56e0
	 */
	@Field(17) 
	private byte ForceCloseReason() {
		return this.io.getByteField(this, 17);
	}

	public char getForceCloseReason() {
		return (char)ForceCloseReason();
	}

	/**
	 * \u5f3a\u5e73\u539f\u56e0
	 */
	@Field(17) 
	private CThostFtdcErrorConditionalOrderField ForceCloseReason(byte ForceCloseReason) {
		this.io.setByteField(this, 17, ForceCloseReason);
		return this;
	}

	public void setForceCloseReason(char forceCloseReason) {
		ForceCloseReason((byte)forceCloseReason);
	}

	/**
	 * \u81ea\u52a8\u6302\u8d77\u6807\u5fd7
	 */
	@Field(18) 
	private int IsAutoSuspend() {
		return this.io.getIntField(this, 18);
	}

	public int getIsAutoSuspend() {
		return IsAutoSuspend();
	}

	/**
	 * \u81ea\u52a8\u6302\u8d77\u6807\u5fd7
	 */
	@Field(18) 
	private CThostFtdcErrorConditionalOrderField IsAutoSuspend(int IsAutoSuspend) {
		this.io.setIntField(this, 18, IsAutoSuspend);
		return this;
	}

	public void setIsAutoSuspend(int isAutoSuspend) {
		IsAutoSuspend(isAutoSuspend);
	}

	/**
	 * \u4e1a\u52a1\u5355\u5143
	 */
	@Array({21}) 
	@Field(19) 
	private Pointer<Byte> BusinessUnit() {
		return this.io.getPointerField(this, 19);
	}

	@Array({21})
	@Field(19)
	public void setBusinessUnit(String businessUnit) {
		this.io.getPointerField(this, 19).setCString(businessUnit);
	}

	public String getBusinessUnit() {
		return BusinessUnit().getCString();
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(20) 
	private int RequestID() {
		return this.io.getIntField(this, 20);
	}

	public int getRequestID() {
		return RequestID();
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(20) 
	private CThostFtdcErrorConditionalOrderField RequestID(int RequestID) {
		this.io.setIntField(this, 20, RequestID);
		return this;
	}

	public void setRequestID(int requestID) {
		RequestID(requestID);
	}

	/**
	 * \u672c\u5730\u62a5\u5355\u7f16\u53f7
	 */
	@Array({13}) 
	@Field(21) 
	private Pointer<Byte> OrderLocalID() {
		return this.io.getPointerField(this, 21);
	}

	@Array({13})
	@Field(21)
	public void setOrderLocalID(String orderLocalID) {
		this.io.getPointerField(this, 21).setCString(orderLocalID);
	}

	public String getOrderLocalID() {
		return OrderLocalID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(22) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 22);
	}

	@Array({9})
	@Field(22)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 22).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u4f1a\u5458\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(23) 
	private Pointer<Byte> ParticipantID() {
		return this.io.getPointerField(this, 23);
	}

	@Array({11})
	@Field(23)
	public void setParticipantID(String participantID) {
		this.io.getPointerField(this, 23).setCString(participantID);
	}

	public String getParticipantID() {
		return ParticipantID().getCString();
	}

	/**
	 * \u5ba2\u6237\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(24) 
	private Pointer<Byte> ClientID() {
		return this.io.getPointerField(this, 24);
	}

	@Array({11})
	@Field(24)
	public void setClientID(String clientID) {
		this.io.getPointerField(this, 24).setCString(clientID);
	}

	public String getClientID() {
		return ClientID().getCString();
	}

	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(25) 
	private Pointer<Byte> ExchangeInstID() {
		return this.io.getPointerField(this, 25);
	}

	@Array({31})
	@Field(25)
	public void setExchangeInstID(String exchangeInstID) {
		this.io.getPointerField(this, 25).setCString(exchangeInstID);
	}

	public String getExchangeInstID() {
		return ExchangeInstID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801
	 */
	@Array({21}) 
	@Field(26) 
	private Pointer<Byte> TraderID() {
		return this.io.getPointerField(this, 26);
	}

	@Array({21})
	@Field(26)
	public void setTraderID(String traderID) {
		this.io.getPointerField(this, 26).setCString(traderID);
	}

	public String getTraderID() {
		return TraderID().getCString();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(27) 
	private int InstallID() {
		return this.io.getIntField(this, 27);
	}

	public int getInstallID() {
		return InstallID();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(27) 
	private CThostFtdcErrorConditionalOrderField InstallID(int InstallID) {
		this.io.setIntField(this, 27, InstallID);
		return this;
	}

	public void setInstallID(int installID) {
		InstallID(installID);
	}

	/**
	 * \u62a5\u5355\u63d0\u4ea4\u72b6\u6001
	 */
	@Field(28) 
	private byte OrderSubmitStatus() {
		return this.io.getByteField(this, 28);
	}

	public char getOrderSubmitStatus() {
		return (char)OrderSubmitStatus();
	}

	/**
	 * \u62a5\u5355\u63d0\u4ea4\u72b6\u6001
	 */
	@Field(28) 
	private CThostFtdcErrorConditionalOrderField OrderSubmitStatus(byte OrderSubmitStatus) {
		this.io.setByteField(this, 28, OrderSubmitStatus);
		return this;
	}

	public void setOrderSubmitStatus(char orderSubmitStatus) {
		OrderSubmitStatus((byte)orderSubmitStatus);
	}

	/**
	 * \u62a5\u5355\u63d0\u793a\u5e8f\u53f7
	 */
	@Field(29) 
	private int NotifySequence() {
		return this.io.getIntField(this, 29);
	}

	public int getNotifySequence() {
		return NotifySequence();
	}

	/**
	 * \u62a5\u5355\u63d0\u793a\u5e8f\u53f7
	 */
	@Field(29) 
	private CThostFtdcErrorConditionalOrderField NotifySequence(int NotifySequence) {
		this.io.setIntField(this, 29, NotifySequence);
		return this;
	}

	public void setNotifySequence(int notifySequence) {
		NotifySequence(notifySequence);
	}

	/**
	 * \u4ea4\u6613\u65e5
	 */
	@Array({9}) 
	@Field(30) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 30);
	}

	@Array({9})
	@Field(30)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 30).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(31) 
	private int SettlementID() {
		return this.io.getIntField(this, 31);
	}

	public int getSettlementID() {
		return SettlementID();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(31) 
	private CThostFtdcErrorConditionalOrderField SettlementID(int SettlementID) {
		this.io.setIntField(this, 31, SettlementID);
		return this;
	}

	public void setSettlementID(int settlementID) {
		SettlementID(settlementID);
	}

	/**
	 * \u62a5\u5355\u7f16\u53f7
	 */
	@Array({21}) 
	@Field(32) 
	private Pointer<Byte> OrderSysID() {
		return this.io.getPointerField(this, 32);
	}

	@Array({21})
	@Field(32)
	public void setOrderSysID(String orderSysID) {
		this.io.getPointerField(this, 32).setCString(orderSysID);
	}

	public String getOrderSysID() {
		return OrderSysID().getCString();
	}

	/**
	 * \u62a5\u5355\u6765\u6e90
	 */
	@Field(33) 
	private byte OrderSource() {
		return this.io.getByteField(this, 33);
	}

	public char getOrderSource() {
		return (char)OrderSource();
	}

	/**
	 * \u62a5\u5355\u6765\u6e90
	 */
	@Field(33) 
	private CThostFtdcErrorConditionalOrderField OrderSource(byte OrderSource) {
		this.io.setByteField(this, 33, OrderSource);
		return this;
	}

	public void setOrderSource(char orderSource) {
		OrderSource((byte)orderSource);
	}

	/**
	 * \u62a5\u5355\u72b6\u6001
	 */
	@Field(34) 
	private byte OrderStatus() {
		return this.io.getByteField(this, 34);
	}

	public char getOrderStatus() {
		return (char)OrderStatus();
	}

	/**
	 * \u62a5\u5355\u72b6\u6001
	 */
	@Field(34) 
	private CThostFtdcErrorConditionalOrderField OrderStatus(byte OrderStatus) {
		this.io.setByteField(this, 34, OrderStatus);
		return this;
	}

	public void setOrderStatus(char orderStatus) {
		OrderStatus((byte)orderStatus);
	}

	/**
	 * \u62a5\u5355\u7c7b\u578b
	 */
	@Field(35) 
	private byte OrderType() {
		return this.io.getByteField(this, 35);
	}

	public char getOrderType() {
		return (char)OrderType();
	}

	/**
	 * \u62a5\u5355\u7c7b\u578b
	 */
	@Field(35) 
	private CThostFtdcErrorConditionalOrderField OrderType(byte OrderType) {
		this.io.setByteField(this, 35, OrderType);
		return this;
	}

	public void setOrderType(char orderType) {
		OrderType((byte)orderType);
	}

	/**
	 * \u4eca\u6210\u4ea4\u6570\u91cf
	 */
	@Field(36) 
	private int VolumeTraded() {
		return this.io.getIntField(this, 36);
	}

	public int getVolumeTraded() {
		return VolumeTraded();
	}

	/**
	 * \u4eca\u6210\u4ea4\u6570\u91cf
	 */
	@Field(36) 
	private CThostFtdcErrorConditionalOrderField VolumeTraded(int VolumeTraded) {
		this.io.setIntField(this, 36, VolumeTraded);
		return this;
	}

	public void setVolumeTraded(int volumeTraded) {
		VolumeTraded(volumeTraded);
	}

	/**
	 * \u5269\u4f59\u6570\u91cf
	 */
	@Field(37) 
	private int VolumeTotal() {
		return this.io.getIntField(this, 37);
	}

	public int getVolumeTotal() {
		return VolumeTotal();
	}

	/**
	 * \u5269\u4f59\u6570\u91cf
	 */
	@Field(37) 
	private CThostFtdcErrorConditionalOrderField VolumeTotal(int VolumeTotal) {
		this.io.setIntField(this, 37, VolumeTotal);
		return this;
	}

	public void setVolumeTotal(int volumeTotal) {
		VolumeTotal(volumeTotal);
	}

	/**
	 * \u62a5\u5355\u65e5\u671f
	 */
	@Array({9}) 
	@Field(38) 
	private Pointer<Byte> InsertDate() {
		return this.io.getPointerField(this, 38);
	}

	@Array({9})
	@Field(38)
	public void setInsertDate(String insertDate) {
		this.io.getPointerField(this, 38).setCString(insertDate);
	}

	public String getInsertDate() {
		return InsertDate().getCString();
	}

	/**
	 * \u59d4\u6258\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(39) 
	private Pointer<Byte> InsertTime() {
		return this.io.getPointerField(this, 39);
	}

	@Array({9})
	@Field(39)
	public void setInsertTime(String insertTime) {
		this.io.getPointerField(this, 39).setCString(insertTime);
	}

	public String getInsertTime() {
		return InsertTime().getCString();
	}

	/**
	 * \u6fc0\u6d3b\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(40) 
	private Pointer<Byte> ActiveTime() {
		return this.io.getPointerField(this, 40);
	}

	@Array({9})
	@Field(40)
	public void setActiveTime(String activeTime) {
		this.io.getPointerField(this, 40).setCString(activeTime);
	}

	public String getActiveTime() {
		return ActiveTime().getCString();
	}

	/**
	 * \u6302\u8d77\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(41) 
	private Pointer<Byte> SuspendTime() {
		return this.io.getPointerField(this, 41);
	}

	@Array({9})
	@Field(41)
	public void setSuspendTime(String suspendTime) {
		this.io.getPointerField(this, 41).setCString(suspendTime);
	}

	public String getSuspendTime() {
		return SuspendTime().getCString();
	}

	/**
	 * \u6700\u540e\u4fee\u6539\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(42) 
	private Pointer<Byte> UpdateTime() {
		return this.io.getPointerField(this, 42);
	}

	@Array({9})
	@Field(42)
	public void setUpdateTime(String updateTime) {
		this.io.getPointerField(this, 42).setCString(updateTime);
	}

	public String getUpdateTime() {
		return UpdateTime().getCString();
	}

	/**
	 * \u64a4\u9500\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(43) 
	private Pointer<Byte> CancelTime() {
		return this.io.getPointerField(this, 43);
	}

	@Array({9})
	@Field(43)
	public void setCancelTime(String cancelTime) {
		this.io.getPointerField(this, 43).setCString(cancelTime);
	}

	public String getCancelTime() {
		return CancelTime().getCString();
	}

	/**
	 * \u6700\u540e\u4fee\u6539\u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801
	 */
	@Array({21}) 
	@Field(44) 
	private Pointer<Byte> ActiveTraderID() {
		return this.io.getPointerField(this, 44);
	}

	@Array({21})
	@Field(44)
	public void setActiveTraderID(String activeTraderID) {
		this.io.getPointerField(this, 44).setCString(activeTraderID);
	}

	public String getActiveTraderID() {
		return ActiveTraderID().getCString();
	}

	/**
	 * \u7ed3\u7b97\u4f1a\u5458\u7f16\u53f7
	 */
	@Array({11}) 
	@Field(45) 
	private Pointer<Byte> ClearingPartID() {
		return this.io.getPointerField(this, 45);
	}

	@Array({11})
	@Field(45)
	public void setClearingPartID(String clearingPartID) {
		this.io.getPointerField(this, 45).setCString(clearingPartID);
	}

	public String getClearingPartID() {
		return ClearingPartID().getCString();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(46) 
	private int SequenceNo() {
		return this.io.getIntField(this, 46);
	}

	public int getSequenceNo() {
		return SequenceNo();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(46) 
	private CThostFtdcErrorConditionalOrderField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 46, SequenceNo);
		return this;
	}

	public void setSequenceNo(int sequenceNo) {
		SequenceNo(sequenceNo);
	}

	/**
	 * \u524d\u7f6e\u7f16\u53f7
	 */
	@Field(47) 
	private int FrontID() {
		return this.io.getIntField(this, 47);
	}

	public int getFrontID() {
		return FrontID();
	}

	/**
	 * \u524d\u7f6e\u7f16\u53f7
	 */
	@Field(47) 
	private CThostFtdcErrorConditionalOrderField FrontID(int FrontID) {
		this.io.setIntField(this, 47, FrontID);
		return this;
	}

	public void setFrontID(int frontID) {
		FrontID(frontID);
	}

	/**
	 * \u4f1a\u8bdd\u7f16\u53f7
	 */
	@Field(48) 
	private int SessionID() {
		return this.io.getIntField(this, 48);
	}

	public int getSessionID() {
		return SessionID();
	}

	/**
	 * \u4f1a\u8bdd\u7f16\u53f7
	 */
	@Field(48) 
	private CThostFtdcErrorConditionalOrderField SessionID(int SessionID) {
		this.io.setIntField(this, 48, SessionID);
		return this;
	}

	public void setSessionID(int sessionID) {
		SessionID(sessionID);
	}

	/**
	 * \u7528\u6237\u7aef\u4ea7\u54c1\u4fe1\u606f
	 */
	@Array({11}) 
	@Field(49) 
	private Pointer<Byte> UserProductInfo() {
		return this.io.getPointerField(this, 49);
	}

	@Array({11})
	@Field(49)
	public void setUserProductInfo(String userProductInfo) {
		this.io.getPointerField(this, 49).setCString(userProductInfo);
	}

	public String getUserProductInfo() {
		return UserProductInfo().getCString();
	}

	/**
	 * \u72b6\u6001\u4fe1\u606f
	 */
	@Array({81}) 
	@Field(50) 
	private Pointer<Byte> StatusMsg() {
		return this.io.getPointerField(this, 50);
	}

	@Array({81})
	@Field(50)
	public void setStatusMsg(String statusMsg) {
		this.io.getPointerField(this, 50).setCString(statusMsg);
	}

	public String getStatusMsg() {
		return StatusMsg().getCString();
	}

	/**
	 * \u7528\u6237\u5f3a\u8bc4\u6807\u5fd7
	 */
	@Field(51) 
	private int UserForceClose() {
		return this.io.getIntField(this, 51);
	}

	public int getUserForceClose() {
		return UserForceClose();
	}

	/**
	 * \u7528\u6237\u5f3a\u8bc4\u6807\u5fd7
	 */
	@Field(51) 
	private CThostFtdcErrorConditionalOrderField UserForceClose(int UserForceClose) {
		this.io.setIntField(this, 51, UserForceClose);
		return this;
	}

	public void setUserForceClose(int userForceClose) {
		UserForceClose(userForceClose);
	}

	/**
	 * \u64cd\u4f5c\u7528\u6237\u4ee3\u7801
	 */
	@Array({16}) 
	@Field(52) 
	private Pointer<Byte> ActiveUserID() {
		return this.io.getPointerField(this, 52);
	}

	@Array({16})
	@Field(52)
	public void setActiveUserID(String activeUserID) {
		this.io.getPointerField(this, 52).setCString(activeUserID);
	}

	public String getActiveUserID() {
		return ActiveUserID().getCString();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u62a5\u5355\u7f16\u53f7
	 */
	@Field(53) 
	private int BrokerOrderSeq() {
		return this.io.getIntField(this, 53);
	}

	public int getBrokerOrderSeq() {
		return BrokerOrderSeq();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u62a5\u5355\u7f16\u53f7
	 */
	@Field(53) 
	private CThostFtdcErrorConditionalOrderField BrokerOrderSeq(int BrokerOrderSeq) {
		this.io.setIntField(this, 53, BrokerOrderSeq);
		return this;
	}

	public void setBrokerOrderSeq(int brokerOrderSeq) {
		BrokerOrderSeq(brokerOrderSeq);
	}

	/**
	 * \u76f8\u5173\u62a5\u5355
	 */
	@Array({21}) 
	@Field(54) 
	private Pointer<Byte> RelativeOrderSysID() {
		return this.io.getPointerField(this, 54);
	}

	@Array({21})
	@Field(54)
	public void setRelativeOrderSysID(String relativeOrderSysID) {
		this.io.getPointerField(this, 54).setCString(relativeOrderSysID);
	}

	public String getRelativeOrderSysID() {
		return RelativeOrderSysID().getCString();
	}

	/**
	 * \u90d1\u5546\u6240\u6210\u4ea4\u6570\u91cf
	 */
	@Field(55) 
	private int ZCETotalTradedVolume() {
		return this.io.getIntField(this, 55);
	}

	public int getZCETotalTradedVolume() {
		return ZCETotalTradedVolume();
	}

	/**
	 * \u90d1\u5546\u6240\u6210\u4ea4\u6570\u91cf
	 */
	@Field(55) 
	private CThostFtdcErrorConditionalOrderField ZCETotalTradedVolume(int ZCETotalTradedVolume) {
		this.io.setIntField(this, 55, ZCETotalTradedVolume);
		return this;
	}

	public void setZCETotalTradedVolume(int zCETotalTradedVolume) {
		ZCETotalTradedVolume(zCETotalTradedVolume);
	}

	/**
	 * \u9519\u8bef\u4ee3\u7801
	 */
	@Field(56) 
	private int ErrorID() {
		return this.io.getIntField(this, 56);
	}

	public int getErrorID() {
		return ErrorID();
	}

	/**
	 * \u9519\u8bef\u4ee3\u7801
	 */
	@Field(56) 
	private CThostFtdcErrorConditionalOrderField ErrorID(int ErrorID) {
		this.io.setIntField(this, 56, ErrorID);
		return this;
	}

	public void setErrorID(int errorID) {
		ErrorID(errorID);
	}

	/**
	 * \u9519\u8bef\u4fe1\u606f
	 */
	@Array({81}) 
	@Field(57) 
	private Pointer<Byte> ErrorMsg() {
		return this.io.getPointerField(this, 57);
	}

	@Array({81})
	@Field(57)
	public void setErrorMsg(String errorMsg) {
		this.io.getPointerField(this, 57).setCString(errorMsg);
	}

	public String getErrorMsg() {
		return ErrorMsg().getCString();
	}

	/**
	 * \u4e92\u6362\u5355\u6807\u5fd7
	 */
	@Field(58) 
	private int IsSwapOrder() {
		return this.io.getIntField(this, 58);
	}

	public int getIsSwapOrder() {
		return IsSwapOrder();
	}

	/**
	 * \u4e92\u6362\u5355\u6807\u5fd7
	 */
	@Field(58) 
	private CThostFtdcErrorConditionalOrderField IsSwapOrder(int IsSwapOrder) {
		this.io.setIntField(this, 58, IsSwapOrder);
		return this;
	}

	public void setIsSwapOrder(int isSwapOrder) {
		IsSwapOrder(isSwapOrder);
	}

	public CThostFtdcErrorConditionalOrderField(Pointer pointer) {
		super(pointer);
	}

}

