package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcBrokerUserRightAssignField extends StructObject {
	public CThostFtdcBrokerUserRightAssignField() {
		super();
	}

	/**
	 * \u5e94\u7528\u5355\u5143\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801
	 */
	@Field(1) 
	private int DRIdentityID() {
		return this.io.getIntField(this, 1);
	}

	public int getDRIdentityID() {
		return DRIdentityID();
	}

	/**
	 * \u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801
	 */
	@Field(1) 
	private CThostFtdcBrokerUserRightAssignField DRIdentityID(int DRIdentityID) {
		this.io.setIntField(this, 1, DRIdentityID);
		return this;
	}

	public void setDRIdentityID(int dRIdentityID) {
		DRIdentityID(dRIdentityID);
	}

	/**
	 * \u80fd\u5426\u4ea4\u6613
	 */
	@Field(2) 
	private int Tradeable() {
		return this.io.getIntField(this, 2);
	}

	public int getTradeable() {
		return Tradeable();
	}

	/**
	 * \u80fd\u5426\u4ea4\u6613
	 */
	@Field(2) 
	private CThostFtdcBrokerUserRightAssignField Tradeable(int Tradeable) {
		this.io.setIntField(this, 2, Tradeable);
		return this;
	}

	public void setTradeable(int tradeable) {
		Tradeable(tradeable);
	}

	public CThostFtdcBrokerUserRightAssignField(Pointer pointer) {
		super(pointer);
	}

}

