package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcDepositResultInformField extends StructObject {
	public CThostFtdcDepositResultInformField() {
		super();
	}

	/**
	 * \u51fa\u5165\u91d1\u6d41\u6c34\u53f7\uff0c\u8be5\u6d41\u6c34\u53f7\u4e3a\u94f6\u671f\u62a5\u76d8\u8fd4\u56de\u7684\u6d41\u6c34\u53f7
	 */
	@Array({15}) 
	@Field(0) 
	private Pointer<Byte> DepositSeqNo() {
		return this.io.getPointerField(this, 0);
	}

	@Array({15})
	@Field(0)
	public void setDepositSeqNo(String depositSeqNo) {
		this.io.getPointerField(this, 0).setCString(depositSeqNo);
	}

	public String getDepositSeqNo() {
		return DepositSeqNo().getCString();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(1) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({11})
	@Field(1)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 1).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(2) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({13})
	@Field(2)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 2).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u5165\u91d1\u91d1\u989d
	 */
	@Field(3) 
	private double Deposit() {
		return this.io.getDoubleField(this, 3);
	}

	public double getDeposit() {
		return Deposit();
	}

	/**
	 * \u5165\u91d1\u91d1\u989d
	 */
	@Field(3) 
	private CThostFtdcDepositResultInformField Deposit(double Deposit) {
		this.io.setDoubleField(this, 3, Deposit);
		return this;
	}

	public void setDeposit(double deposit) {
		Deposit(deposit);
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(4) 
	private int RequestID() {
		return this.io.getIntField(this, 4);
	}

	public int getRequestID() {
		return RequestID();
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(4) 
	private CThostFtdcDepositResultInformField RequestID(int RequestID) {
		this.io.setIntField(this, 4, RequestID);
		return this;
	}

	public void setRequestID(int requestID) {
		RequestID(requestID);
	}

	/**
	 * \u8fd4\u56de\u4ee3\u7801
	 */
	@Array({7}) 
	@Field(5) 
	private Pointer<Byte> ReturnCode() {
		return this.io.getPointerField(this, 5);
	}

	@Array({7})
	@Field(5)
	public void setReturnCode(String returnCode) {
		this.io.getPointerField(this, 5).setCString(returnCode);
	}

	public String getReturnCode() {
		return ReturnCode().getCString();
	}

	/**
	 * \u8fd4\u56de\u7801\u63cf\u8ff0
	 */
	@Array({129}) 
	@Field(6) 
	private Pointer<Byte> DescrInfoForReturnCode() {
		return this.io.getPointerField(this, 6);
	}

	@Array({129})
	@Field(6)
	public void setDescrInfoForReturnCode(String descrInfoForReturnCode) {
		this.io.getPointerField(this, 6).setCString(descrInfoForReturnCode);
	}

	public String getDescrInfoForReturnCode() {
		return DescrInfoForReturnCode().getCString();
	}

	public CThostFtdcDepositResultInformField(Pointer pointer) {
		super(pointer);
	}

}

