package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcExchangeOrderField extends StructObject {
	public CThostFtdcExchangeOrderField() {
		super();
	}

	/**
	 * \u62a5\u5355\u4ef7\u683c\u6761\u4ef6
	 */
	@Field(0) 
	private byte OrderPriceType() {
		return this.io.getByteField(this, 0);
	}

	public char getOrderPriceType() {
		return (char)OrderPriceType();
	}

	/**
	 * \u62a5\u5355\u4ef7\u683c\u6761\u4ef6
	 */
	@Field(0) 
	private CThostFtdcExchangeOrderField OrderPriceType(byte OrderPriceType) {
		this.io.setByteField(this, 0, OrderPriceType);
		return this;
	}

	public void setOrderPriceType(char orderPriceType) {
		OrderPriceType((byte)orderPriceType);
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(1) 
	private byte Direction() {
		return this.io.getByteField(this, 1);
	}

	public char getDirection() {
		return (char)Direction();
	}

	/**
	 * \u4e70\u5356\u65b9\u5411
	 */
	@Field(1) 
	private CThostFtdcExchangeOrderField Direction(byte Direction) {
		this.io.setByteField(this, 1, Direction);
		return this;
	}

	public void setDirection(char direction) {
		Direction((byte)direction);
	}

	/**
	 * \u7ec4\u5408\u5f00\u5e73\u6807\u5fd7
	 */
	@Array({5}) 
	@Field(2) 
	private Pointer<Byte> CombOffsetFlag() {
		return this.io.getPointerField(this, 2);
	}

	@Array({5})
	@Field(2)
	public void setCombOffsetFlag(String combOffsetFlag) {
		this.io.getPointerField(this, 2).setCString(combOffsetFlag);
	}

	public String getCombOffsetFlag() {
		return CombOffsetFlag().getCString();
	}

	/**
	 * \u7ec4\u5408\u6295\u673a\u5957\u4fdd\u6807\u5fd7
	 */
	@Array({5}) 
	@Field(3) 
	private Pointer<Byte> CombHedgeFlag() {
		return this.io.getPointerField(this, 3);
	}

	@Array({5})
	@Field(3)
	public void setCombHedgeFlag(String combHedgeFlag) {
		this.io.getPointerField(this, 3).setCString(combHedgeFlag);
	}

	public String getCombHedgeFlag() {
		return CombHedgeFlag().getCString();
	}

	/**
	 * \u4ef7\u683c
	 */
	@Field(4) 
	private double LimitPrice() {
		return this.io.getDoubleField(this, 4);
	}

	public double getLimitPrice() {
		return LimitPrice();
	}

	/**
	 * \u4ef7\u683c
	 */
	@Field(4) 
	private CThostFtdcExchangeOrderField LimitPrice(double LimitPrice) {
		this.io.setDoubleField(this, 4, LimitPrice);
		return this;
	}

	public void setLimitPrice(double limitPrice) {
		LimitPrice(limitPrice);
	}

	/**
	 * \u6570\u91cf
	 */
	@Field(5) 
	private int VolumeTotalOriginal() {
		return this.io.getIntField(this, 5);
	}

	public int getVolumeTotalOriginal() {
		return VolumeTotalOriginal();
	}

	/**
	 * \u6570\u91cf
	 */
	@Field(5) 
	private CThostFtdcExchangeOrderField VolumeTotalOriginal(int VolumeTotalOriginal) {
		this.io.setIntField(this, 5, VolumeTotalOriginal);
		return this;
	}

	public void setVolumeTotalOriginal(int volumeTotalOriginal) {
		VolumeTotalOriginal(volumeTotalOriginal);
	}

	/**
	 * \u6709\u6548\u671f\u7c7b\u578b
	 */
	@Field(6) 
	private byte TimeCondition() {
		return this.io.getByteField(this, 6);
	}

	public char getTimeCondition() {
		return (char)TimeCondition();
	}

	/**
	 * \u6709\u6548\u671f\u7c7b\u578b
	 */
	@Field(6) 
	private CThostFtdcExchangeOrderField TimeCondition(byte TimeCondition) {
		this.io.setByteField(this, 6, TimeCondition);
		return this;
	}

	public void setTimeCondition(char timeCondition) {
		TimeCondition((byte)timeCondition);
	}

	/// GTD\u65e5\u671f
	@Array({9}) 
	@Field(7) 
	private Pointer<Byte> GTDDate() {
		return this.io.getPointerField(this, 7);
	}

	@Array({9})
	@Field(7)
	public void setGTDDate(String gTDDate) {
		this.io.getPointerField(this, 7).setCString(gTDDate);
	}

	public String getGTDDate() {
		return GTDDate().getCString();
	}

	/**
	 * \u6210\u4ea4\u91cf\u7c7b\u578b
	 */
	@Field(8) 
	private byte VolumeCondition() {
		return this.io.getByteField(this, 8);
	}

	public char getVolumeCondition() {
		return (char)VolumeCondition();
	}

	/**
	 * \u6210\u4ea4\u91cf\u7c7b\u578b
	 */
	@Field(8) 
	private CThostFtdcExchangeOrderField VolumeCondition(byte VolumeCondition) {
		this.io.setByteField(this, 8, VolumeCondition);
		return this;
	}

	public void setVolumeCondition(char volumeCondition) {
		VolumeCondition((byte)volumeCondition);
	}

	/**
	 * \u6700\u5c0f\u6210\u4ea4\u91cf
	 */
	@Field(9) 
	private int MinVolume() {
		return this.io.getIntField(this, 9);
	}

	public int getMinVolume() {
		return MinVolume();
	}

	/**
	 * \u6700\u5c0f\u6210\u4ea4\u91cf
	 */
	@Field(9) 
	private CThostFtdcExchangeOrderField MinVolume(int MinVolume) {
		this.io.setIntField(this, 9, MinVolume);
		return this;
	}

	public void setMinVolume(int minVolume) {
		MinVolume(minVolume);
	}

	/**
	 * \u89e6\u53d1\u6761\u4ef6
	 */
	@Field(10) 
	private byte ContingentCondition() {
		return this.io.getByteField(this, 10);
	}

	public char getContingentCondition() {
		return (char)ContingentCondition();
	}

	/**
	 * \u89e6\u53d1\u6761\u4ef6
	 */
	@Field(10) 
	private CThostFtdcExchangeOrderField ContingentCondition(byte ContingentCondition) {
		this.io.setByteField(this, 10, ContingentCondition);
		return this;
	}

	public void setContingentCondition(char contingentCondition) {
		ContingentCondition((byte)contingentCondition);
	}

	/**
	 * \u6b62\u635f\u4ef7
	 */
	@Field(11) 
	private double StopPrice() {
		return this.io.getDoubleField(this, 11);
	}

	public double getStopPrice() {
		return StopPrice();
	}

	/**
	 * \u6b62\u635f\u4ef7
	 */
	@Field(11) 
	private CThostFtdcExchangeOrderField StopPrice(double StopPrice) {
		this.io.setDoubleField(this, 11, StopPrice);
		return this;
	}

	public void setStopPrice(double stopPrice) {
		StopPrice(stopPrice);
	}

	/**
	 * \u5f3a\u5e73\u539f\u56e0
	 */
	@Field(12) 
	private byte ForceCloseReason() {
		return this.io.getByteField(this, 12);
	}

	public char getForceCloseReason() {
		return (char)ForceCloseReason();
	}

	/**
	 * \u5f3a\u5e73\u539f\u56e0
	 */
	@Field(12) 
	private CThostFtdcExchangeOrderField ForceCloseReason(byte ForceCloseReason) {
		this.io.setByteField(this, 12, ForceCloseReason);
		return this;
	}

	public void setForceCloseReason(char forceCloseReason) {
		ForceCloseReason((byte)forceCloseReason);
	}

	/**
	 * \u81ea\u52a8\u6302\u8d77\u6807\u5fd7
	 */
	@Field(13) 
	private int IsAutoSuspend() {
		return this.io.getIntField(this, 13);
	}

	public int getIsAutoSuspend() {
		return IsAutoSuspend();
	}

	/**
	 * \u81ea\u52a8\u6302\u8d77\u6807\u5fd7
	 */
	@Field(13) 
	private CThostFtdcExchangeOrderField IsAutoSuspend(int IsAutoSuspend) {
		this.io.setIntField(this, 13, IsAutoSuspend);
		return this;
	}

	public void setIsAutoSuspend(int isAutoSuspend) {
		IsAutoSuspend(isAutoSuspend);
	}

	/**
	 * \u4e1a\u52a1\u5355\u5143
	 */
	@Array({21}) 
	@Field(14) 
	private Pointer<Byte> BusinessUnit() {
		return this.io.getPointerField(this, 14);
	}

	@Array({21})
	@Field(14)
	public void setBusinessUnit(String businessUnit) {
		this.io.getPointerField(this, 14).setCString(businessUnit);
	}

	public String getBusinessUnit() {
		return BusinessUnit().getCString();
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(15) 
	private int RequestID() {
		return this.io.getIntField(this, 15);
	}

	public int getRequestID() {
		return RequestID();
	}

	/**
	 * \u8bf7\u6c42\u7f16\u53f7
	 */
	@Field(15) 
	private CThostFtdcExchangeOrderField RequestID(int RequestID) {
		this.io.setIntField(this, 15, RequestID);
		return this;
	}

	public void setRequestID(int requestID) {
		RequestID(requestID);
	}

	/**
	 * \u672c\u5730\u62a5\u5355\u7f16\u53f7
	 */
	@Array({13}) 
	@Field(16) 
	private Pointer<Byte> OrderLocalID() {
		return this.io.getPointerField(this, 16);
	}

	@Array({13})
	@Field(16)
	public void setOrderLocalID(String orderLocalID) {
		this.io.getPointerField(this, 16).setCString(orderLocalID);
	}

	public String getOrderLocalID() {
		return OrderLocalID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(17) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 17);
	}

	@Array({9})
	@Field(17)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 17).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u4f1a\u5458\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(18) 
	private Pointer<Byte> ParticipantID() {
		return this.io.getPointerField(this, 18);
	}

	@Array({11})
	@Field(18)
	public void setParticipantID(String participantID) {
		this.io.getPointerField(this, 18).setCString(participantID);
	}

	public String getParticipantID() {
		return ParticipantID().getCString();
	}

	/**
	 * \u5ba2\u6237\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(19) 
	private Pointer<Byte> ClientID() {
		return this.io.getPointerField(this, 19);
	}

	@Array({11})
	@Field(19)
	public void setClientID(String clientID) {
		this.io.getPointerField(this, 19).setCString(clientID);
	}

	public String getClientID() {
		return ClientID().getCString();
	}

	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(20) 
	private Pointer<Byte> ExchangeInstID() {
		return this.io.getPointerField(this, 20);
	}

	@Array({31})
	@Field(20)
	public void setExchangeInstID(String exchangeInstID) {
		this.io.getPointerField(this, 20).setCString(exchangeInstID);
	}

	public String getExchangeInstID() {
		return ExchangeInstID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801
	 */
	@Array({21}) 
	@Field(21) 
	private Pointer<Byte> TraderID() {
		return this.io.getPointerField(this, 21);
	}

	@Array({21})
	@Field(21)
	public void setTraderID(String traderID) {
		this.io.getPointerField(this, 21).setCString(traderID);
	}

	public String getTraderID() {
		return TraderID().getCString();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(22) 
	private int InstallID() {
		return this.io.getIntField(this, 22);
	}

	public int getInstallID() {
		return InstallID();
	}

	/**
	 * \u5b89\u88c5\u7f16\u53f7
	 */
	@Field(22) 
	private CThostFtdcExchangeOrderField InstallID(int InstallID) {
		this.io.setIntField(this, 22, InstallID);
		return this;
	}

	public void setInstallID(int installID) {
		InstallID(installID);
	}

	/**
	 * \u62a5\u5355\u63d0\u4ea4\u72b6\u6001
	 */
	@Field(23) 
	private byte OrderSubmitStatus() {
		return this.io.getByteField(this, 23);
	}

	public char getOrderSubmitStatus() {
		return (char)OrderSubmitStatus();
	}

	/**
	 * \u62a5\u5355\u63d0\u4ea4\u72b6\u6001
	 */
	@Field(23) 
	private CThostFtdcExchangeOrderField OrderSubmitStatus(byte OrderSubmitStatus) {
		this.io.setByteField(this, 23, OrderSubmitStatus);
		return this;
	}

	public void setOrderSubmitStatus(char orderSubmitStatus) {
		OrderSubmitStatus((byte)orderSubmitStatus);
	}

	/**
	 * \u62a5\u5355\u63d0\u793a\u5e8f\u53f7
	 */
	@Field(24) 
	private int NotifySequence() {
		return this.io.getIntField(this, 24);
	}

	public int getNotifySequence() {
		return NotifySequence();
	}

	/**
	 * \u62a5\u5355\u63d0\u793a\u5e8f\u53f7
	 */
	@Field(24) 
	private CThostFtdcExchangeOrderField NotifySequence(int NotifySequence) {
		this.io.setIntField(this, 24, NotifySequence);
		return this;
	}

	public void setNotifySequence(int notifySequence) {
		NotifySequence(notifySequence);
	}

	/**
	 * \u4ea4\u6613\u65e5
	 */
	@Array({9}) 
	@Field(25) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 25);
	}

	@Array({9})
	@Field(25)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 25).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(26) 
	private int SettlementID() {
		return this.io.getIntField(this, 26);
	}

	public int getSettlementID() {
		return SettlementID();
	}

	/**
	 * \u7ed3\u7b97\u7f16\u53f7
	 */
	@Field(26) 
	private CThostFtdcExchangeOrderField SettlementID(int SettlementID) {
		this.io.setIntField(this, 26, SettlementID);
		return this;
	}

	public void setSettlementID(int settlementID) {
		SettlementID(settlementID);
	}

	/**
	 * \u62a5\u5355\u7f16\u53f7
	 */
	@Array({21}) 
	@Field(27) 
	private Pointer<Byte> OrderSysID() {
		return this.io.getPointerField(this, 27);
	}

	@Array({21})
	@Field(27)
	public void setOrderSysID(String orderSysID) {
		this.io.getPointerField(this, 27).setCString(orderSysID);
	}

	public String getOrderSysID() {
		return OrderSysID().getCString();
	}

	/**
	 * \u62a5\u5355\u6765\u6e90
	 */
	@Field(28) 
	private byte OrderSource() {
		return this.io.getByteField(this, 28);
	}

	public char getOrderSource() {
		return (char)OrderSource();
	}

	/**
	 * \u62a5\u5355\u6765\u6e90
	 */
	@Field(28) 
	private CThostFtdcExchangeOrderField OrderSource(byte OrderSource) {
		this.io.setByteField(this, 28, OrderSource);
		return this;
	}

	public void setOrderSource(char orderSource) {
		OrderSource((byte)orderSource);
	}

	/**
	 * \u62a5\u5355\u72b6\u6001
	 */
	@Field(29) 
	private byte OrderStatus() {
		return this.io.getByteField(this, 29);
	}

	public char getOrderStatus() {
		return (char)OrderStatus();
	}

	/**
	 * \u62a5\u5355\u72b6\u6001
	 */
	@Field(29) 
	private CThostFtdcExchangeOrderField OrderStatus(byte OrderStatus) {
		this.io.setByteField(this, 29, OrderStatus);
		return this;
	}

	public void setOrderStatus(char orderStatus) {
		OrderStatus((byte)orderStatus);
	}

	/**
	 * \u62a5\u5355\u7c7b\u578b
	 */
	@Field(30) 
	private byte OrderType() {
		return this.io.getByteField(this, 30);
	}

	public char getOrderType() {
		return (char)OrderType();
	}

	/**
	 * \u62a5\u5355\u7c7b\u578b
	 */
	@Field(30) 
	private CThostFtdcExchangeOrderField OrderType(byte OrderType) {
		this.io.setByteField(this, 30, OrderType);
		return this;
	}

	public void setOrderType(char orderType) {
		OrderType((byte)orderType);
	}

	/**
	 * \u4eca\u6210\u4ea4\u6570\u91cf
	 */
	@Field(31) 
	private int VolumeTraded() {
		return this.io.getIntField(this, 31);
	}

	public int getVolumeTraded() {
		return VolumeTraded();
	}

	/**
	 * \u4eca\u6210\u4ea4\u6570\u91cf
	 */
	@Field(31) 
	private CThostFtdcExchangeOrderField VolumeTraded(int VolumeTraded) {
		this.io.setIntField(this, 31, VolumeTraded);
		return this;
	}

	public void setVolumeTraded(int volumeTraded) {
		VolumeTraded(volumeTraded);
	}

	/**
	 * \u5269\u4f59\u6570\u91cf
	 */
	@Field(32) 
	private int VolumeTotal() {
		return this.io.getIntField(this, 32);
	}

	public int getVolumeTotal() {
		return VolumeTotal();
	}

	/**
	 * \u5269\u4f59\u6570\u91cf
	 */
	@Field(32) 
	private CThostFtdcExchangeOrderField VolumeTotal(int VolumeTotal) {
		this.io.setIntField(this, 32, VolumeTotal);
		return this;
	}

	public void setVolumeTotal(int volumeTotal) {
		VolumeTotal(volumeTotal);
	}

	/**
	 * \u62a5\u5355\u65e5\u671f
	 */
	@Array({9}) 
	@Field(33) 
	private Pointer<Byte> InsertDate() {
		return this.io.getPointerField(this, 33);
	}

	@Array({9})
	@Field(33)
	public void setInsertDate(String insertDate) {
		this.io.getPointerField(this, 33).setCString(insertDate);
	}

	public String getInsertDate() {
		return InsertDate().getCString();
	}

	/**
	 * \u59d4\u6258\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(34) 
	private Pointer<Byte> InsertTime() {
		return this.io.getPointerField(this, 34);
	}

	@Array({9})
	@Field(34)
	public void setInsertTime(String insertTime) {
		this.io.getPointerField(this, 34).setCString(insertTime);
	}

	public String getInsertTime() {
		return InsertTime().getCString();
	}

	/**
	 * \u6fc0\u6d3b\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(35) 
	private Pointer<Byte> ActiveTime() {
		return this.io.getPointerField(this, 35);
	}

	@Array({9})
	@Field(35)
	public void setActiveTime(String activeTime) {
		this.io.getPointerField(this, 35).setCString(activeTime);
	}

	public String getActiveTime() {
		return ActiveTime().getCString();
	}

	/**
	 * \u6302\u8d77\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(36) 
	private Pointer<Byte> SuspendTime() {
		return this.io.getPointerField(this, 36);
	}

	@Array({9})
	@Field(36)
	public void setSuspendTime(String suspendTime) {
		this.io.getPointerField(this, 36).setCString(suspendTime);
	}

	public String getSuspendTime() {
		return SuspendTime().getCString();
	}

	/**
	 * \u6700\u540e\u4fee\u6539\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(37) 
	private Pointer<Byte> UpdateTime() {
		return this.io.getPointerField(this, 37);
	}

	@Array({9})
	@Field(37)
	public void setUpdateTime(String updateTime) {
		this.io.getPointerField(this, 37).setCString(updateTime);
	}

	public String getUpdateTime() {
		return UpdateTime().getCString();
	}

	/**
	 * \u64a4\u9500\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(38) 
	private Pointer<Byte> CancelTime() {
		return this.io.getPointerField(this, 38);
	}

	@Array({9})
	@Field(38)
	public void setCancelTime(String cancelTime) {
		this.io.getPointerField(this, 38).setCString(cancelTime);
	}

	public String getCancelTime() {
		return CancelTime().getCString();
	}

	/**
	 * \u6700\u540e\u4fee\u6539\u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801
	 */
	@Array({21}) 
	@Field(39) 
	private Pointer<Byte> ActiveTraderID() {
		return this.io.getPointerField(this, 39);
	}

	@Array({21})
	@Field(39)
	public void setActiveTraderID(String activeTraderID) {
		this.io.getPointerField(this, 39).setCString(activeTraderID);
	}

	public String getActiveTraderID() {
		return ActiveTraderID().getCString();
	}

	/**
	 * \u7ed3\u7b97\u4f1a\u5458\u7f16\u53f7
	 */
	@Array({11}) 
	@Field(40) 
	private Pointer<Byte> ClearingPartID() {
		return this.io.getPointerField(this, 40);
	}

	@Array({11})
	@Field(40)
	public void setClearingPartID(String clearingPartID) {
		this.io.getPointerField(this, 40).setCString(clearingPartID);
	}

	public String getClearingPartID() {
		return ClearingPartID().getCString();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(41) 
	private int SequenceNo() {
		return this.io.getIntField(this, 41);
	}

	public int getSequenceNo() {
		return SequenceNo();
	}

	/**
	 * \u5e8f\u53f7
	 */
	@Field(41) 
	private CThostFtdcExchangeOrderField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 41, SequenceNo);
		return this;
	}

	public void setSequenceNo(int sequenceNo) {
		SequenceNo(sequenceNo);
	}

	public CThostFtdcExchangeOrderField(Pointer pointer) {
		super(pointer);
	}

}

