package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcCommPhaseField extends StructObject {
	public CThostFtdcCommPhaseField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u65e5
	 */
	@Array({9}) 
	@Field(0) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9})
	@Field(0)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 0).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u901a\u8baf\u65f6\u6bb5\u7f16\u53f7
	 */
	@Field(1) 
	private short CommPhaseNo() {
		return this.io.getShortField(this, 1);
	}

	public short getCommPhaseNo() {
		return CommPhaseNo();
	}

	/**
	 * \u901a\u8baf\u65f6\u6bb5\u7f16\u53f7
	 */
	@Field(1) 
	private CThostFtdcCommPhaseField CommPhaseNo(short CommPhaseNo) {
		this.io.setShortField(this, 1, CommPhaseNo);
		return this;
	}

	public void setCommPhaseNo(short commPhaseNo) {
		CommPhaseNo(commPhaseNo);
	}

	public CThostFtdcCommPhaseField(Pointer pointer) {
		super(pointer);
	}

}

