package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTradingNoticeField extends StructObject {
	public CThostFtdcTradingNoticeField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6295\u8d44\u8005\u8303\u56f4
	 */
	@Field(1) 
	private byte InvestorRange() {
		return this.io.getByteField(this, 1);
	}

	public char getInvestorRange() {
		return (char)InvestorRange();
	}

	/**
	 * \u6295\u8d44\u8005\u8303\u56f4
	 */
	@Field(1) 
	private CThostFtdcTradingNoticeField InvestorRange(byte InvestorRange) {
		this.io.setByteField(this, 1, InvestorRange);
		return this;
	}

	public void setInvestorRange(char investorRange) {
		InvestorRange((byte)investorRange);
	}

	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801
	 */
	@Array({13}) 
	@Field(2) 
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({13})
	@Field(2)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 2).setCString(investorID);
	}

	public String getInvestorID() {
		return InvestorID().getCString();
	}

	/**
	 * \u5e8f\u5217\u7cfb\u5217\u53f7
	 */
	@Field(3) 
	private short SequenceSeries() {
		return this.io.getShortField(this, 3);
	}

	public short getSequenceSeries() {
		return SequenceSeries();
	}

	/**
	 * \u5e8f\u5217\u7cfb\u5217\u53f7
	 */
	@Field(3) 
	private CThostFtdcTradingNoticeField SequenceSeries(short SequenceSeries) {
		this.io.setShortField(this, 3, SequenceSeries);
		return this;
	}

	public void setSequenceSeries(short sequenceSeries) {
		SequenceSeries(sequenceSeries);
	}

	/**
	 * \u7528\u6237\u4ee3\u7801
	 */
	@Array({16}) 
	@Field(4) 
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 4);
	}

	@Array({16})
	@Field(4)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 4).setCString(userID);
	}

	public String getUserID() {
		return UserID().getCString();
	}

	/**
	 * \u53d1\u9001\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(5) 
	private Pointer<Byte> SendTime() {
		return this.io.getPointerField(this, 5);
	}

	@Array({9})
	@Field(5)
	public void setSendTime(String sendTime) {
		this.io.getPointerField(this, 5).setCString(sendTime);
	}

	public String getSendTime() {
		return SendTime().getCString();
	}

	/**
	 * \u5e8f\u5217\u53f7
	 */
	@Field(6) 
	private int SequenceNo() {
		return this.io.getIntField(this, 6);
	}

	public int getSequenceNo() {
		return SequenceNo();
	}

	/**
	 * \u5e8f\u5217\u53f7
	 */
	@Field(6) 
	private CThostFtdcTradingNoticeField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 6, SequenceNo);
		return this;
	}

	public void setSequenceNo(int sequenceNo) {
		SequenceNo(sequenceNo);
	}

	/**
	 * \u6d88\u606f\u6b63\u6587
	 */
	@Array({501}) 
	@Field(7) 
	private Pointer<Byte> FieldContent() {
		return this.io.getPointerField(this, 7);
	}

	@Array({501})
	@Field(7)
	public void setFieldContent(String fieldContent) {
		this.io.getPointerField(this, 7).setCString(fieldContent);
	}

	public String getFieldContent() {
		return FieldContent().getCString();
	}

	public CThostFtdcTradingNoticeField(Pointer pointer) {
		super(pointer);
	}

}

