package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcInstrumentStatusField extends StructObject {
	public CThostFtdcInstrumentStatusField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(0) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9})
	@Field(0)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 0).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(1) 
	private Pointer<Byte> ExchangeInstID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({31})
	@Field(1)
	public void setExchangeInstID(String exchangeInstID) {
		this.io.getPointerField(this, 1).setCString(exchangeInstID);
	}

	public String getExchangeInstID() {
		return ExchangeInstID().getCString();
	}

	/**
	 * \u7ed3\u7b97\u7ec4\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(2) 
	private Pointer<Byte> SettlementGroupID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({9})
	@Field(2)
	public void setSettlementGroupID(String settlementGroupID) {
		this.io.getPointerField(this, 2).setCString(settlementGroupID);
	}

	public String getSettlementGroupID() {
		return SettlementGroupID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ee3\u7801
	 */
	@Array({31}) 
	@Field(3) 
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 3);
	}

	@Array({31})
	@Field(3)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 3).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return InstrumentID().getCString();
	}

	/**
	 * \u5408\u7ea6\u4ea4\u6613\u72b6\u6001
	 */
	@Field(4) 
	private byte InstrumentStatus() {
		return this.io.getByteField(this, 4);
	}

	public char getInstrumentStatus() {
		return (char)InstrumentStatus();
	}

	/**
	 * \u5408\u7ea6\u4ea4\u6613\u72b6\u6001
	 */
	@Field(4) 
	private CThostFtdcInstrumentStatusField InstrumentStatus(byte InstrumentStatus) {
		this.io.setByteField(this, 4, InstrumentStatus);
		return this;
	}

	public void setInstrumentStatus(char instrumentStatus) {
		InstrumentStatus((byte)instrumentStatus);
	}

	/**
	 * \u4ea4\u6613\u9636\u6bb5\u7f16\u53f7
	 */
	@Field(5) 
	private int TradingSegmentSN() {
		return this.io.getIntField(this, 5);
	}

	public int getTradingSegmentSN() {
		return TradingSegmentSN();
	}

	/**
	 * \u4ea4\u6613\u9636\u6bb5\u7f16\u53f7
	 */
	@Field(5) 
	private CThostFtdcInstrumentStatusField TradingSegmentSN(int TradingSegmentSN) {
		this.io.setIntField(this, 5, TradingSegmentSN);
		return this;
	}

	public void setTradingSegmentSN(int tradingSegmentSN) {
		TradingSegmentSN(tradingSegmentSN);
	}

	/**
	 * \u8fdb\u5165\u672c\u72b6\u6001\u65f6\u95f4
	 */
	@Array({9}) 
	@Field(6) 
	private Pointer<Byte> EnterTime() {
		return this.io.getPointerField(this, 6);
	}

	@Array({9})
	@Field(6)
	public void setEnterTime(String enterTime) {
		this.io.getPointerField(this, 6).setCString(enterTime);
	}

	public String getEnterTime() {
		return EnterTime().getCString();
	}

	/**
	 * \u8fdb\u5165\u672c\u72b6\u6001\u539f\u56e0
	 */
	@Field(7) 
	private byte EnterReason() {
		return this.io.getByteField(this, 7);
	}

	public char getEnterReason() {
		return (char)EnterReason();
	}

	/**
	 * \u8fdb\u5165\u672c\u72b6\u6001\u539f\u56e0
	 */
	@Field(7) 
	private CThostFtdcInstrumentStatusField EnterReason(byte EnterReason) {
		this.io.setByteField(this, 7, EnterReason);
		return this;
	}

	public void setEnterReason(char enterReason) {
		EnterReason((byte)enterReason);
	}

	public CThostFtdcInstrumentStatusField(Pointer pointer) {
		super(pointer);
	}

}

