package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcMarketDataLastMatchField extends StructObject {
	public CThostFtdcMarketDataLastMatchField() {
		super();
	}

	/**
	 * \u6700\u65b0\u4ef7
	 */
	@Field(0) 
	private double LastPrice() {
		return this.io.getDoubleField(this, 0);
	}

	public double getLastPrice() {
		return LastPrice();
	}

	/**
	 * \u6700\u65b0\u4ef7
	 */
	@Field(0) 
	private CThostFtdcMarketDataLastMatchField LastPrice(double LastPrice) {
		this.io.setDoubleField(this, 0, LastPrice);
		return this;
	}

	public void setLastPrice(double lastPrice) {
		LastPrice(lastPrice);
	}

	/**
	 * \u6570\u91cf
	 */
	@Field(1) 
	private int Volume() {
		return this.io.getIntField(this, 1);
	}

	public int getVolume() {
		return Volume();
	}

	/**
	 * \u6570\u91cf
	 */
	@Field(1) 
	private CThostFtdcMarketDataLastMatchField Volume(int Volume) {
		this.io.setIntField(this, 1, Volume);
		return this;
	}

	public void setVolume(int volume) {
		Volume(volume);
	}

	/**
	 * \u6210\u4ea4\u91d1\u989d
	 */
	@Field(2) 
	private double Turnover() {
		return this.io.getDoubleField(this, 2);
	}

	public double getTurnover() {
		return Turnover();
	}

	/**
	 * \u6210\u4ea4\u91d1\u989d
	 */
	@Field(2) 
	private CThostFtdcMarketDataLastMatchField Turnover(double Turnover) {
		this.io.setDoubleField(this, 2, Turnover);
		return this;
	}

	public void setTurnover(double turnover) {
		Turnover(turnover);
	}

	/**
	 * \u6301\u4ed3\u91cf
	 */
	@Field(3) 
	private double OpenInterest() {
		return this.io.getDoubleField(this, 3);
	}

	public double getOpenInterest() {
		return OpenInterest();
	}

	/**
	 * \u6301\u4ed3\u91cf
	 */
	@Field(3) 
	private CThostFtdcMarketDataLastMatchField OpenInterest(double OpenInterest) {
		this.io.setDoubleField(this, 3, OpenInterest);
		return this;
	}

	public void setOpenInterest(double openInterest) {
		OpenInterest(openInterest);
	}

	public CThostFtdcMarketDataLastMatchField(Pointer pointer) {
		super(pointer);
	}

}

