package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcBrokerDepositField extends StructObject {
	public CThostFtdcBrokerDepositField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u65e5\u671f
	 */
	@Array({9}) 
	@Field(0) 
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9})
	@Field(0)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 0).setCString(tradingDay);
	}

	public String getTradingDay() {
		return TradingDay().getCString();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(1) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({11})
	@Field(1)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 1).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u4f1a\u5458\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(2) 
	private Pointer<Byte> ParticipantID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({11})
	@Field(2)
	public void setParticipantID(String participantID) {
		this.io.getPointerField(this, 2).setCString(participantID);
	}

	public String getParticipantID() {
		return ParticipantID().getCString();
	}

	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801
	 */
	@Array({9}) 
	@Field(3) 
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 3);
	}

	@Array({9})
	@Field(3)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 3).setCString(exchangeID);
	}

	public String getExchangeID() {
		return ExchangeID().getCString();
	}

	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(4) 
	private double PreBalance() {
		return this.io.getDoubleField(this, 4);
	}

	public double getPreBalance() {
		return PreBalance();
	}

	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(4) 
	private CThostFtdcBrokerDepositField PreBalance(double PreBalance) {
		this.io.setDoubleField(this, 4, PreBalance);
		return this;
	}

	public void setPreBalance(double preBalance) {
		PreBalance(preBalance);
	}

	/**
	 * \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d
	 */
	@Field(5) 
	private double CurrMargin() {
		return this.io.getDoubleField(this, 5);
	}

	public double getCurrMargin() {
		return CurrMargin();
	}

	/**
	 * \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d
	 */
	@Field(5) 
	private CThostFtdcBrokerDepositField CurrMargin(double CurrMargin) {
		this.io.setDoubleField(this, 5, CurrMargin);
		return this;
	}

	public void setCurrMargin(double currMargin) {
		CurrMargin(currMargin);
	}

	/**
	 * \u5e73\u4ed3\u76c8\u4e8f
	 */
	@Field(6) 
	private double CloseProfit() {
		return this.io.getDoubleField(this, 6);
	}

	public double getCloseProfit() {
		return CloseProfit();
	}

	/**
	 * \u5e73\u4ed3\u76c8\u4e8f
	 */
	@Field(6) 
	private CThostFtdcBrokerDepositField CloseProfit(double CloseProfit) {
		this.io.setDoubleField(this, 6, CloseProfit);
		return this;
	}

	public void setCloseProfit(double closeProfit) {
		CloseProfit(closeProfit);
	}

	/**
	 * \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(7) 
	private double Balance() {
		return this.io.getDoubleField(this, 7);
	}

	public double getBalance() {
		return Balance();
	}

	/**
	 * \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1
	 */
	@Field(7) 
	private CThostFtdcBrokerDepositField Balance(double Balance) {
		this.io.setDoubleField(this, 7, Balance);
		return this;
	}

	public void setBalance(double balance) {
		Balance(balance);
	}

	/**
	 * \u5165\u91d1\u91d1\u989d
	 */
	@Field(8) 
	private double Deposit() {
		return this.io.getDoubleField(this, 8);
	}

	public double getDeposit() {
		return Deposit();
	}

	/**
	 * \u5165\u91d1\u91d1\u989d
	 */
	@Field(8) 
	private CThostFtdcBrokerDepositField Deposit(double Deposit) {
		this.io.setDoubleField(this, 8, Deposit);
		return this;
	}

	public void setDeposit(double deposit) {
		Deposit(deposit);
	}

	/**
	 * \u51fa\u91d1\u91d1\u989d
	 */
	@Field(9) 
	private double Withdraw() {
		return this.io.getDoubleField(this, 9);
	}

	public double getWithdraw() {
		return Withdraw();
	}

	/**
	 * \u51fa\u91d1\u91d1\u989d
	 */
	@Field(9) 
	private CThostFtdcBrokerDepositField Withdraw(double Withdraw) {
		this.io.setDoubleField(this, 9, Withdraw);
		return this;
	}

	public void setWithdraw(double withdraw) {
		Withdraw(withdraw);
	}

	/**
	 * \u53ef\u63d0\u8d44\u91d1
	 */
	@Field(10) 
	private double Available() {
		return this.io.getDoubleField(this, 10);
	}

	public double getAvailable() {
		return Available();
	}

	/**
	 * \u53ef\u63d0\u8d44\u91d1
	 */
	@Field(10) 
	private CThostFtdcBrokerDepositField Available(double Available) {
		this.io.setDoubleField(this, 10, Available);
		return this;
	}

	public void setAvailable(double available) {
		Available(available);
	}

	/**
	 * \u57fa\u672c\u51c6\u5907\u91d1
	 */
	@Field(11) 
	private double Reserve() {
		return this.io.getDoubleField(this, 11);
	}

	public double getReserve() {
		return Reserve();
	}

	/**
	 * \u57fa\u672c\u51c6\u5907\u91d1
	 */
	@Field(11) 
	private CThostFtdcBrokerDepositField Reserve(double Reserve) {
		this.io.setDoubleField(this, 11, Reserve);
		return this;
	}

	public void setReserve(double reserve) {
		Reserve(reserve);
	}

	/**
	 * \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1
	 */
	@Field(12) 
	private double FrozenMargin() {
		return this.io.getDoubleField(this, 12);
	}

	public double getFrozenMargin() {
		return FrozenMargin();
	}

	/**
	 * \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1
	 */
	@Field(12) 
	private CThostFtdcBrokerDepositField FrozenMargin(double FrozenMargin) {
		this.io.setDoubleField(this, 12, FrozenMargin);
		return this;
	}

	public void setFrozenMargin(double frozenMargin) {
		FrozenMargin(frozenMargin);
	}

	public CThostFtdcBrokerDepositField(Pointer pointer) {
		super(pointer);
	}

}

