package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcDRTransferField extends StructObject {
	public CThostFtdcDRTransferField() {
		super();
	}

	/**
	 * \u539f\u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801
	 */
	@Field(0) 
	private int OrigDRIdentityID() {
		return this.io.getIntField(this, 0);
	}

	public int getOrigDRIdentityID() {
		return OrigDRIdentityID();
	}

	/**
	 * \u539f\u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801
	 */
	@Field(0) 
	private CThostFtdcDRTransferField OrigDRIdentityID(int OrigDRIdentityID) {
		this.io.setIntField(this, 0, OrigDRIdentityID);
		return this;
	}

	public void setOrigDRIdentityID(int origDRIdentityID) {
		OrigDRIdentityID(origDRIdentityID);
	}

	/**
	 * \u76ee\u6807\u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801
	 */
	@Field(1) 
	private int DestDRIdentityID() {
		return this.io.getIntField(this, 1);
	}

	public int getDestDRIdentityID() {
		return DestDRIdentityID();
	}

	/**
	 * \u76ee\u6807\u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801
	 */
	@Field(1) 
	private CThostFtdcDRTransferField DestDRIdentityID(int DestDRIdentityID) {
		this.io.setIntField(this, 1, DestDRIdentityID);
		return this;
	}

	public void setDestDRIdentityID(int destDRIdentityID) {
		DestDRIdentityID(destDRIdentityID);
	}

	/**
	 * \u539f\u5e94\u7528\u5355\u5143\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(2) 
	private Pointer<Byte> OrigBrokerID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({11})
	@Field(2)
	public void setOrigBrokerID(String origBrokerID) {
		this.io.getPointerField(this, 2).setCString(origBrokerID);
	}

	public String getOrigBrokerID() {
		return OrigBrokerID().getCString();
	}

	/**
	 * \u76ee\u6807\u6613\u7528\u5355\u5143\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(3) 
	private Pointer<Byte> DestBrokerID() {
		return this.io.getPointerField(this, 3);
	}

	@Array({11})
	@Field(3)
	public void setDestBrokerID(String destBrokerID) {
		this.io.getPointerField(this, 3).setCString(destBrokerID);
	}

	public String getDestBrokerID() {
		return DestBrokerID().getCString();
	}

	public CThostFtdcDRTransferField(Pointer pointer) {
		super(pointer);
	}

}

