package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcVerifyFuturePasswordAndCustInfoField extends StructObject {
	public CThostFtdcVerifyFuturePasswordAndCustInfoField() {
		super();
	}

	/**
	 * \u5ba2\u6237\u59d3\u540d
	 */
	@Array({51}) 
	@Field(0) 
	private Pointer<Byte> CustomerName() {
		return this.io.getPointerField(this, 0);
	}

	@Array({51})
	@Field(0)
	public void setCustomerName(String customerName) {
		this.io.getPointerField(this, 0).setCString(customerName);
	}

	public String getCustomerName() {
		return CustomerName().getCString();
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(1) 
	private byte IdCardType() {
		return this.io.getByteField(this, 1);
	}

	public char getIdCardType() {
		return (char)IdCardType();
	}

	/**
	 * \u8bc1\u4ef6\u7c7b\u578b
	 */
	@Field(1) 
	private CThostFtdcVerifyFuturePasswordAndCustInfoField IdCardType(byte IdCardType) {
		this.io.setByteField(this, 1, IdCardType);
		return this;
	}

	public void setIdCardType(char idCardType) {
		IdCardType((byte)idCardType);
	}

	/**
	 * \u8bc1\u4ef6\u53f7\u7801
	 */
	@Array({51}) 
	@Field(2) 
	private Pointer<Byte> IdentifiedCardNo() {
		return this.io.getPointerField(this, 2);
	}

	@Array({51})
	@Field(2)
	public void setIdentifiedCardNo(String identifiedCardNo) {
		this.io.getPointerField(this, 2).setCString(identifiedCardNo);
	}

	public String getIdentifiedCardNo() {
		return IdentifiedCardNo().getCString();
	}

	/**
	 * \u5ba2\u6237\u7c7b\u578b
	 */
	@Field(3) 
	private byte CustType() {
		return this.io.getByteField(this, 3);
	}

	public char getCustType() {
		return (char)CustType();
	}

	/**
	 * \u5ba2\u6237\u7c7b\u578b
	 */
	@Field(3) 
	private CThostFtdcVerifyFuturePasswordAndCustInfoField CustType(byte CustType) {
		this.io.setByteField(this, 3, CustType);
		return this;
	}

	public void setCustType(char custType) {
		CustType((byte)custType);
	}

	/**
	 * \u6295\u8d44\u8005\u5e10\u53f7
	 */
	@Array({13}) 
	@Field(4) 
	private Pointer<Byte> AccountID() {
		return this.io.getPointerField(this, 4);
	}

	@Array({13})
	@Field(4)
	public void setAccountID(String accountID) {
		this.io.getPointerField(this, 4).setCString(accountID);
	}

	public String getAccountID() {
		return AccountID().getCString();
	}

	/**
	 * \u671f\u8d27\u5bc6\u7801
	 */
	@Array({41}) 
	@Field(5) 
	private Pointer<Byte> Password() {
		return this.io.getPointerField(this, 5);
	}

	@Array({41})
	@Field(5)
	public void setPassword(String password) {
		this.io.getPointerField(this, 5).setCString(password);
	}

	public String getPassword() {
		return Password().getCString();
	}

	public CThostFtdcVerifyFuturePasswordAndCustInfoField(Pointer pointer) {
		super(pointer);
	}

}

