package sims2016derive.quotationtranscode.context.struct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcNoticeField extends StructObject {
	public CThostFtdcNoticeField() {
		super();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	 */
	@Array({11}) 
	@Field(0) 
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({11})
	@Field(0)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 0).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u6d88\u606f\u6b63\u6587
	 */
	@Array({501}) 
	@Field(1) 
	private Pointer<Byte> Content() {
		return this.io.getPointerField(this, 1);
	}

	@Array({501})
	@Field(1)
	public void setContent(String content) {
		this.io.getPointerField(this, 1).setCString(content);
	}

	public String getContent() {
		return Content().getCString();
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u901a\u77e5\u5185\u5bb9\u5e8f\u5217\u53f7
	 */
	@Array({2}) 
	@Field(2) 
	private Pointer<Byte> SequenceLabel() {
		return this.io.getPointerField(this, 2);
	}

	@Array({2})
	@Field(2)
	public void setSequenceLabel(String sequenceLabel) {
		this.io.getPointerField(this, 2).setCString(sequenceLabel);
	}

	public String getSequenceLabel() {
		return SequenceLabel().getCString();
	}

	public CThostFtdcNoticeField(Pointer pointer) {
		super(pointer);
	}

}

